#!/usr/bin/env node
'use strict';
const crypto=require('node:crypto');

const SECRET_RE=/(bearer\s+[a-z0-9._~+/=-]{6,}|basic\s+[a-z0-9+/=]{8,}|(?:api[_-]?key|password|secret|token|cookie)\s*[:=]\s*(?!<redacted>)[^\s,;}]{6,})/i;
function stable(v){if(Array.isArray(v))return v.map(stable);if(v&&typeof v==='object')return Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k])]));return v;}
function sha256(v){return crypto.createHash('sha256').update(JSON.stringify(stable(v))).digest('hex');}
function uniq(v){return [...new Set(v)].sort();}
function unknown(reason,evidence_pointer='UNKNOWN'){return {status:'UNKNOWN',reason,evidence_pointer};}
function rejectSecrets(v){if(SECRET_RE.test(JSON.stringify(v)))throw Object.assign(new Error('RAW_SECRET_VALUE_REJECTED'),{code:'RAW_SECRET_VALUE_REJECTED'});}
function normName(s=''){return String(s).toLowerCase().replace(/[^a-z0-9]/g,'');}
function leaf(path=''){return String(path).replace(/\[\]/g,'').split('.').pop().replace(/[^A-Za-z0-9_-]/g,'');}
function generalizeUrl(raw=''){try{const u=new URL(raw);const segs=u.pathname.split('/').filter(Boolean).map((s,i)=>/^\d+$/.test(s)?`{id_${i+1}}`:s.toLowerCase());return {origin:u.origin.toLowerCase(),path_pattern:'/'+segs.join('/'),query_names:uniq([...u.searchParams.keys()])};}catch{return {origin:'UNKNOWN',path_pattern:String(raw||''),query_names:[]};}}
function asArray(v){return Array.isArray(v)?v:[];}
function eventType(e){return e.type||e.event_type||e.schema_event_type||'';}
function payload(e){return e.payload||e.data||{};}
function eventPage(e){return e.page_id||payload(e).page_id||payload(e).correlation?.page_id||null;}
function eventAction(e){return e.action_id||payload(e).action_id||payload(e).correlation?.action_id||null;}
function eventCommand(e,bundle){return e.command_id||payload(e).command_id||payload(e).correlation?.command_id||bundle.command_id||null;}
function eventRequest(e){return e.request_id||payload(e).request_id||null;}
function evidencePtr(e,bundle){return e.evidence_pointer||payload(e).evidence_pointer||bundle.a3_evidence_pointer||'UNKNOWN';}
function dedupe(arr,key){const m=new Map();for(const x of arr)if(!m.has(x[key]))m.set(x[key],x);return [...m.values()];}

function normalizeA3(bundle){
  const receipt=bundle.a3_observation_receipt||{};
  const events=asArray(bundle.a3_events||bundle.a3_observation_events||bundle.a3_resolved_artifacts?.events||bundle.a3_resolved_artifacts?.request_response_metadata);
  const actions=[],requests=[],responses=[],bodies=[],states=[];
  for(const e of events){const t=eventType(e);const p=payload(e);const common={command_id:eventCommand(e,bundle),page_id:eventPage(e)||receipt.page_identity?.page_id||null,action_id:eventAction(e),evidence_pointer:evidencePtr(e,bundle),sequence:e.sequence??null};
    if(['analyzer.action','action.started','action.completed','ui.action'].includes(t)) actions.push({...common,event_type:t,action_kind:p.kind||p.action_kind||e.kind||'UNKNOWN',target:p.target||p.locator||p.selector||e.target||null,state_before:p.state_before??e.state_before??null,state_after:p.state_after??e.state_after??null,component_id:p.component_id||e.component_id||null,form_id:p.form_id||e.form_id||null});
    else if(['network.request','network.requestWillBeSent'].includes(t)) requests.push({...common,request_id:eventRequest(e)||p.request_id||`req-${requests.length+1}`,method:String(p.method||e.method||'GET').toUpperCase(),url:p.url||p.request_url||e.url||'',headers:p.headers||p.request_headers||e.headers||{},body:p.post_data??p.body??e.body??null});
    else if(['network.response','network.responseReceived'].includes(t)) responses.push({...common,request_id:eventRequest(e)||p.request_id,status:p.status??e.status??null,mime_type:p.mime_type||p.content_type||e.mime_type||null});
    else if(['network.responseBody','network.response_body'].includes(t)) bodies.push({...common,request_id:eventRequest(e)||p.request_id,body:p.redacted_body??p.body??e.redacted_body??e.body??null,mime_type:p.mime_type||e.mime_type||null});
    else if(['ui.state','state.transition','component.state'].includes(t)) states.push({...common,component_id:p.component_id||e.component_id||null,state_before:p.state_before??e.state_before??null,state_after:p.state_after??e.state_after??null});
  }
  return {receipt,events,actions,requests,responses,bodies,states};
}
function normalizeA4(bundle){
  const r=bundle.a4_structure_receipt||{};
  const fields=asArray(r.fields||r.fieldCandidates||r.inference?.fieldCandidates);
  const locators=asArray(r.locator_candidates||r.locatorCandidates||r.inference?.locatorCandidates);
  const regions=asArray(r.repeated_regions||r.repeatedRegions||r.inference?.repeatedRegions);
  const pagination=asArray(r.pagination_candidates).sort((a,b)=>(b.confidence||0)-(a.confidence||0))[0]||r.pagination||r.inference?.pagination||null;
  const components=asArray(r.components||r.component_candidates||r.page_components);
  const forms=asArray(r.forms||r.form_candidates||r.formCandidates);
  return {receipt:r,fields,locators,regions,pagination,components,forms,page_id:r.page_identity?.page_id||r.page_id||null,evidence_pointer:typeof r.evidence_pointer==='string'?r.evidence_pointer:(r.evidence_pointer?.path||bundle.a4_evidence_pointer||'UNKNOWN')};
}
function safeHeaderRequirements(requests){
  const set=new Set();for(const r of requests){const h=r.headers||{};for(const k of Array.isArray(h)?h.map(x=>x?.name):Object.keys(h))if(k)set.add(String(k).toLowerCase());}
  const requirements=[];for(const n of [...set].sort()){if(n==='cookie')requirements.push({type:'COOKIE_JAR_REFERENCE',header_name:n});else if(['authorization','proxy-authorization','x-api-key','api-key'].includes(n))requirements.push({type:'CREDENTIAL_REFERENCE',header_name:n});else if(/csrf|xsrf/.test(n))requirements.push({type:'CSRF_TOKEN_REFERENCE',header_name:n});}
  return {reference_type:'SESSION_REQUIREMENTS_ONLY',requirements,raw_value_storage:false};
}
function flattenBody(v,path='$',out=[]){const type=v===null?'null':Array.isArray(v)?'array':Number.isInteger(v)?'integer':typeof v;out.push({path,type});if(Array.isArray(v)){for(const x of v.slice(0,3))flattenBody(x,path+'[]',out);}else if(v&&typeof v==='object'){for(const[k,x]of Object.entries(v))flattenBody(x,path+'.'+k,out);}return out;}
function responseEntities(a3){const result=[];for(const b of a3.bodies){if(b.body===null||b.body===undefined)continue;let body=b.body;if(typeof body==='string'){try{body=JSON.parse(body);}catch{continue;}}const fields=flattenBody(body);const paths=[];for(const p of fields.filter(f=>f.type==='array').map(f=>f.path))paths.push({record_path:p,field_prefix:p+'[]'});for(const idField of fields.filter(f=>/(^|\.)(id|.*_id|.*Id)$/.test(f.path))){const parent=idField.path.includes('.')?idField.path.slice(0,idField.path.lastIndexOf('.')):'$';if(parent!=='$'&&!paths.some(x=>x.record_path===parent))paths.push({record_path:parent,field_prefix:parent+'.'});}for(const item of paths){const prefixes=fields.filter(f=>f.path.startsWith(item.field_prefix)).map(f=>f.path);const ids=prefixes.filter(x=>/(^|\.)(id|.*_id|.*Id)$/.test(x));if(!prefixes.length)continue;result.push({entity_id:'ENT-'+sha256([b.request_id,item.record_path]).slice(0,12).toUpperCase(),request_id:b.request_id,record_path:item.record_path,identifier_paths:ids,field_paths:uniq(prefixes),authority:'OBSERVED_REDACTED_BODY',evidence_pointer:b.evidence_pointer,command_id:b.command_id,page_id:b.page_id,action_id:b.action_id});}}return dedupe(result,'entity_id');}
function endpointForRequest(r){const u=generalizeUrl(r.url);return {endpoint_id:'EP-'+sha256([r.method,u.origin,u.path_pattern]).slice(0,12).toUpperCase(),method:r.method,url_template:u.origin+u.path_pattern,query_names:u.query_names};}
function actionNetworkBinding(a3){const rows=[];for(const a of a3.actions){const linked=a3.requests.filter(r=>r.action_id&&a.action_id&&r.action_id===a.action_id);rows.push({action_id:a.action_id||'UNKNOWN',command_id:a.command_id||'UNKNOWN',page_id:a.page_id||'UNKNOWN',action_kind:a.action_kind,target:a.target||'UNKNOWN',network_requests:linked.map(r=>({...endpointForRequest(r),request_id:r.request_id,evidence_pointer:r.evidence_pointer})),binding_status:linked.length?'OBSERVED':'UNKNOWN',evidence_pointer:a.evidence_pointer});}return {schema_version:'ACTION_NETWORK_BINDING_V1',bindings:rows,unbound_requests:a3.requests.filter(r=>!r.action_id).map(r=>({request_id:r.request_id,reason:'ACTION_ID_NOT_OBSERVED',evidence_pointer:r.evidence_pointer}))};}
function componentCandidates(a4){if(a4.components.length)return a4.components.map((c,i)=>({component_id:c.component_id||c.id||`component-${i+1}`,locator:c.locator||c.selector||c.source_locator||null,kind:c.kind||c.type||'UNKNOWN',evidence_pointer:a4.evidence_pointer}));return a4.regions.map((r,i)=>({component_id:r.region_id||r.id||`region-${i+1}`,locator:r.locator||r.semanticLocator||null,kind:r.kind||'REPEATED_REGION',evidence_pointer:a4.evidence_pointer}));}
function apiUiGraph(a3,a4,entities){const comps=componentCandidates(a4),nodes=[],edges=[];for(const r of a3.requests){const ep=endpointForRequest(r);nodes.push({node_id:ep.endpoint_id,node_type:'API_ENDPOINT',...ep,evidence_pointer:r.evidence_pointer});}for(const c of comps)nodes.push({node_id:c.component_id,node_type:'UI_COMPONENT',...c});for(const e of entities)nodes.push({node_id:e.entity_id,node_type:'DATA_ENTITY',record_path:e.record_path,evidence_pointer:e.evidence_pointer});for(const e of entities){for(const c of comps){const exact=a4.fields.some(f=>{const n=normName(f.name||f.field||f.label);return e.field_paths.some(p=>normName(leaf(p))===n);});if(exact)edges.push({from:e.entity_id,to:c.component_id,relation:'ENTITY_FIELD_TO_COMPONENT_CANDIDATE',authority:'CANDIDATE',confidence:0.78,evidence_pointer:[e.evidence_pointer,c.evidence_pointer]});}}return {schema_version:'API_UI_BINDING_GRAPH_V1',nodes:dedupe(nodes,'node_id'),edges};}
function stateGraph(a3,a4){const transitions=[];for(const s of [...a3.states,...a3.actions.filter(a=>a.state_before!==null||a.state_after!==null)]){if(s.state_before===null||s.state_after===null)transitions.push({action_id:s.action_id||'UNKNOWN',component_id:s.component_id||'UNKNOWN',transition:unknown('BEFORE_OR_AFTER_STATE_NOT_OBSERVED',s.evidence_pointer),evidence_pointer:s.evidence_pointer});else transitions.push({action_id:s.action_id||'UNKNOWN',component_id:s.component_id||'UNKNOWN',state_before:s.state_before,state_after:s.state_after,authority:'OBSERVED',evidence_pointer:s.evidence_pointer});}return {schema_version:'UI_STATE_TRANSITION_GRAPH_V1',transitions:transitions.length?transitions:[unknown('NO_EXPLICIT_UI_STATE_TRANSITION_OBSERVED',a4.evidence_pointer)]};}
function entityGraph(entities){const nodes=entities.map(e=>({entity_id:e.entity_id,record_path:e.record_path,identifier_paths:e.identifier_paths,authority:e.authority,evidence_pointer:e.evidence_pointer}));const edges=[];for(const a of entities)for(const b of entities)if(a!==b&&b.record_path.startsWith(a.record_path+'[].'))edges.push({from:a.entity_id,to:b.entity_id,relation:'NESTED_ENTITY',authority:'OBSERVED_PATH',confidence:0.9});return {schema_version:'DATA_ENTITY_RELATIONSHIP_GRAPH_V1',nodes,edges,business_rules:unknown('BUSINESS_RULES_NOT_OBSERVED')};}
function formCandidates(a3,a4,entities){const schemaPaths=uniq(entities.flatMap(e=>e.field_paths));const forms=a4.forms.length?a4.forms:[{form_id:'UNKNOWN',fields:a4.fields}];const candidates=[];for(const form of forms){for(const f of asArray(form.fields||form.field_candidates||a4.fields)){const name=f.name||f.field||f.label;if(!name)continue;const match=schemaPaths.find(p=>normName(leaf(p))===normName(name));const reqParam=a3.requests.flatMap(r=>{const u=generalizeUrl(r.url);const q=u.query_names.map(q=>({request:r,name:q,location:'query'}));const body=(r.body&&typeof r.body==='object'&&!Array.isArray(r.body))?Object.keys(r.body).map(k=>({request:r,name:k,location:'body'})):[];return [...q,...body];}).find(x=>normName(x.name)===normName(name));candidates.push({form_id:form.form_id||form.id||'UNKNOWN',field_name:name,canonical_candidate:match?{json_path:match,authority:'CANDIDATE',confidence:0.95,evidence_pointer:[a4.evidence_pointer,entities.find(e=>e.field_paths.includes(match))?.evidence_pointer||'UNKNOWN']}:unknown('NO_MATCHING_RESPONSE_SCHEMA_FIELD',a4.evidence_pointer),read_transform:match?{from:match,to:name,transform:'IDENTITY_CANDIDATE',authority:'CANDIDATE',confidence:0.9}:unknown('READ_TRANSFORM_NOT_EVIDENCED'),write_transform:reqParam?{from:name,to:reqParam.name,location:reqParam.location,transform:'IDENTITY_CANDIDATE',authority:'CANDIDATE',confidence:0.82,evidence_pointer:reqParam.request.evidence_pointer}:unknown('WRITE_TRANSFORM_NOT_EVIDENCED')});}}return {schema_version:'FORM_FIELD_CANONICAL_CANDIDATE_V1',candidates,business_rule_policy:'UNOBSERVED_RULES_REMAIN_UNKNOWN'};}
function featureGraph(actionBinding,apiUi){const nodes=[],edges=[];for(const b of actionBinding.bindings){const aid='ACT-'+sha256([b.command_id,b.page_id,b.action_id]).slice(0,12).toUpperCase();nodes.push({node_id:aid,node_type:'FEATURE_ACTION',action_id:b.action_id,command_id:b.command_id,page_id:b.page_id});for(const r of b.network_requests)edges.push({from:aid,to:r.endpoint_id,relation:'ACTION_REQUIRES_ENDPOINT',authority:'OBSERVED',confidence:1,evidence_pointer:r.evidence_pointer});}for(const e of apiUi.edges)if(e.relation==='ENTITY_FIELD_TO_COMPONENT_CANDIDATE')edges.push({from:e.from,to:e.to,relation:'FEATURE_DATA_PRESENTATION_DEPENDENCY',authority:'CANDIDATE',confidence:e.confidence,evidence_pointer:e.evidence_pointer});return {schema_version:'FEATURE_DEPENDENCY_GRAPH_V1',nodes:dedupe(nodes,'node_id'),edges,business_rules:unknown('BUSINESS_RULES_NOT_OBSERVED')};}
function build(bundle){rejectSecrets(bundle);if(bundle?.schema_version!=='A5_ACTION_STATE_API_ENTITY_EVIDENCE_BUNDLE_V1')throw Object.assign(new Error('INVALID_INPUT_SCHEMA'),{code:'INVALID_INPUT_SCHEMA'});const a3=normalizeA3(bundle),a4=normalizeA4(bundle);const entities=responseEntities(a3);const actionBinding=actionNetworkBinding(a3);const apiUi=apiUiGraph(a3,a4,entities);const uiState=stateGraph(a3,a4);const entityRel=entityGraph(entities);const feature=featureGraph(actionBinding,apiUi);const forms=formCandidates(a3,a4,entities);const provenance={command_id:bundle.command_id||'UNKNOWN',page_id:a3.receipt.page_identity?.page_id||a4.page_id||'UNKNOWN',action_ids:uniq(a3.actions.map(a=>a.action_id).filter(Boolean)),evidence_pointer:{a3:bundle.a3_evidence_pointer||'UNKNOWN',a4:bundle.a4_evidence_pointer||a4.evidence_pointer||'UNKNOWN'}};const out={schema_version:'A5_ACTION_STATE_API_ENTITY_BINDING_RESULT_V1',provenance,action_network_binding:actionBinding,api_ui_binding_graph:apiUi,ui_state_transition_graph:uiState,data_entity_relationship_graph:entityRel,feature_dependency_graph:feature,form_field_canonical_candidate:forms,session_requirements_reference:safeHeaderRequirements(a3.requests),consumers:{A6:{contract:'ACTION_STATE_API_ENTITY_RECIPE_INPUT_V1',direct_consume:true},B5:{contract:'ENTITY_TRANSFORM_LINEAGE_INPUT_V1',direct_consume:true}},raw_secret_value_count:0};out.decision_digest=sha256(out);return out;}
module.exports={build,normalizeA3,normalizeA4,responseEntities,actionNetworkBinding,apiUiGraph,stateGraph,entityGraph,formCandidates,featureGraph,sha256};
if(require.main===module){let raw='';process.stdin.setEncoding('utf8');process.stdin.on('data',c=>raw+=c);process.stdin.on('end',()=>{try{process.stdout.write(JSON.stringify(build(JSON.parse(raw||'{}')),null,2)+'\n')}catch(e){process.stderr.write(JSON.stringify({status:'ERROR',code:e.code||'BUILD_FAILED',message:e.message})+'\n');process.exitCode=e.code==='RAW_SECRET_VALUE_REJECTED'?40:30;}})}
