'use strict';
const assert=require('node:assert/strict');
const {build}=require('./action_state_api_entity_binding.cjs');
let n=0;const eq=(a,b)=>{assert.deepEqual(a,b);n++};const ok=x=>{assert.ok(x);n++};
const fixture={schema_version:'A5_ACTION_STATE_API_ENTITY_EVIDENCE_BUNDLE_V1',command_id:'CMD-WRITE-1',a3_evidence_pointer:'github://a3/obs',a4_evidence_pointer:'github://a4/structure',a3_observation_receipt:{schema_version:'CDP_OBSERVATION_RUN_RECEIPT_V1',status:'PASS',run_id:'A3-C4-1',page_identity:{page_id:'page-1',url:'https://fixture.local/items'}},a3_events:[
{type:'action.started',action_id:'ACT-1',command_id:'CMD-WRITE-1',page_id:'page-1',payload:{kind:'submit',target:'#item-form',component_id:'form-item',state_before:'FORM_DIRTY',state_after:'SUBMITTING'}},
{type:'network.request',action_id:'ACT-1',command_id:'CMD-WRITE-1',page_id:'page-1',request_id:'REQ-1',payload:{method:'POST',url:'https://fixture.local/api/items?mode=create',headers:{Cookie:'<REDACTED>'},body:{name:'Alpha',value:100}}},
{type:'network.response',action_id:'ACT-1',command_id:'CMD-WRITE-1',page_id:'page-1',request_id:'REQ-1',payload:{status:200,mime_type:'application/json'}},
{type:'network.responseBody',action_id:'ACT-1',command_id:'CMD-WRITE-1',page_id:'page-1',request_id:'REQ-1',payload:{redacted_body:{record:{record_id:'R1',name:'Alpha',value:100}}}},
{type:'ui.state',action_id:'ACT-1',command_id:'CMD-WRITE-1',page_id:'page-1',payload:{component_id:'item-list',state_before:'COUNT_1',state_after:'COUNT_2'}}
],a4_structure_receipt:{schema_version:'STRUCTURE_INFERENCE_RUN_RECEIPT_V1',request_id:'A4-C4-1',page_identity:{page_id:'page-1'},fields:[{name:'record_id'},{name:'name'},{name:'value'}],repeated_regions:[{region_id:'item-list',kind:'CARD_LIST'}],components:[{component_id:'item-list',kind:'LIST',locator:'#items'}],forms:[{form_id:'item-form',fields:[{name:'name'},{name:'value'}]}],evidence_pointer:{path:'a4.json'}}};
const a=build(fixture),b=build(fixture);
eq(a.schema_version,'A5_ACTION_STATE_API_ENTITY_BINDING_RESULT_V1');eq(a.action_network_binding.bindings[0].network_requests.length,1);eq(a.action_network_binding.bindings[0].binding_status,'OBSERVED');eq(a.ui_state_transition_graph.transitions.filter(x=>x.authority==='OBSERVED').length,2);eq(a.data_entity_relationship_graph.nodes.length,1);eq(a.data_entity_relationship_graph.business_rules.status,'UNKNOWN');eq(a.form_field_canonical_candidate.candidates.find(x=>x.field_name==='name').canonical_candidate.confidence,.95);eq(a.form_field_canonical_candidate.candidates.find(x=>x.field_name==='name').write_transform.location,'body');eq(a.form_field_canonical_candidate.candidates.find(x=>x.field_name==='name').write_transform.confidence,.82);eq(a.session_requirements_reference.requirements[0].type,'COOKIE_JAR_REFERENCE');eq(a.provenance.command_id,'CMD-WRITE-1');eq(a.provenance.page_id,'page-1');eq(a.consumers.A6.direct_consume,true);eq(a.consumers.B5.direct_consume,true);eq(a.raw_secret_value_count,0);eq(a.decision_digest,b.decision_digest);ok(/^[a-f0-9]{64}$/.test(a.decision_digest));
const noState=JSON.parse(JSON.stringify(fixture));noState.a3_events=noState.a3_events.filter(e=>e.type!=='ui.state'&&e.type!=='action.started');const c=build(noState);eq(c.ui_state_transition_graph.transitions[0].status,'UNKNOWN');
const secret=JSON.parse(JSON.stringify(fixture));secret.a3_events[1].payload.headers.Authorization='Bearer SECRETSECRET';assert.throws(()=>build(secret),/RAW_SECRET_VALUE_REJECTED/);n++;
console.log(JSON.stringify({status:'PASS',assertions:n,digest1:a.decision_digest,digest2:b.decision_digest,entity_count:a.data_entity_relationship_graph.nodes.length,action_binding_count:a.action_network_binding.bindings.length}));
