'use strict';
const fs=require('node:fs');
const path=require('node:path');
const crypto=require('node:crypto');
const {sha256,stepIdempotencyKey,loadCheckpoint,saveCheckpoint,markStepComplete}=require('./ADAPTER_CHECKPOINT_RESUME_V1.cjs');
const EXIT=Object.freeze({PASS:0,INVALID_REQUEST:10,UPSTREAM_RECEIPT_INVALID:11,BUILD_FAILED:20,RUN_FAILED:30,RESUME_FAILED:31,CLEANUP_FAILED:40,PARTIAL_REPAIR_FAILED:50,UNKNOWN_COMMAND:64});
function stable(v){return Array.isArray(v)?v.map(stable):v&&typeof v==='object'?Object.keys(v).sort().reduce((a,k)=>(a[k]=stable(v[k]),a),{}):v}
function digest(v){return crypto.createHash('sha256').update(JSON.stringify(stable(v))).digest('hex')}
function readJson(p){return JSON.parse(fs.readFileSync(p,'utf8'))}
function writeJson(p,v){fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,JSON.stringify(v,null,2)+'\n')}
function validateRequest(r){const req=['schema_version','command_id','checkpoint_id','recipe_version','adapter_version','paths'];for(const k of req)if(!r?.[k])throw Object.assign(new Error(`MISSING_${k}`),{exitCode:EXIT.INVALID_REQUEST});if(r.schema_version!=='ADAPTER_BUILD_RUN_REQUEST_V1')throw Object.assign(new Error('BAD_SCHEMA_VERSION'),{exitCode:EXIT.INVALID_REQUEST});}
function validateUpstream(a4,a5){const a4ok=a4?.checks?.json_parse==='PASS'&&a4?.checks?.locator_entry_count==='PASS_7_OF_7'&&a4?.checks?.automated_pagination==='PASS_FALSE'&&a4?.result?.decision==='PASS';const a5ok=a5?.status==='PASS'&&a5?.positive_checks?.active_profile_count==='PASS_7_OF_7'&&a5?.validator_contract?.required_method==='GET'&&a5?.validator_contract?.required_mime_type==='text/html';if(!a4ok||!a5ok)throw Object.assign(new Error(`UPSTREAM_RECEIPT_INVALID:A4=${a4ok}:A5=${a5ok}`),{exitCode:EXIT.UPSTREAM_RECEIPT_INVALID});}
function recipeFromReceipts(request,a4,a5){const profiles=a5.validator_contract.required_profile_set;return {schema_version:'EXTRACTION_RECIPE_V1',recipe_id:`${request.command_id}:recipe`,recipe_version:request.recipe_version,adapter_version:request.adapter_version,source_receipts:{a4:{blob:request.upstream.a4_receipt_blob,decision:a4.result.decision},a5:{blob:request.upstream.a5_receipt_blob,status:a5.status}},runtime:{browser_action_runtime:'PLAYWRIGHT',queue_retry_resume_runtime:'CRAWLEE',max_request_retries:2},profiles,start_url:a5.validator_contract.required_official_origin,steps:[{step_id:'s01',type:'Navigate',url:'${start_url}'},{step_id:'s02',type:'Wait',locator:{strategy:'css',value:'body'},state:'visible'},{step_id:'s03',type:'Extract',fields:[{name:'html_document_text',locator:{strategy:'css_text',value:'body'}},{name:'outbound_links',locator:{strategy:'css_links',value:'a[href]'}}]}],pagination:{automated:false,max_documents_per_profile:1},safety:{production:false,ready:false,merge:false}};}
function compileAdapter(recipe){const source=`'use strict';\nconst { PlaywrightCrawler, RequestQueue }=require('crawlee');\nasync function run({startUrl,onReceipt}){const q=await RequestQueue.open(${JSON.stringify('a6-cycle2-'+recipe.adapter_version)});await q.addRequest({url:startUrl});const crawler=new PlaywrightCrawler({requestQueue:q,maxRequestRetries:2,requestHandler:async({page,request})=>{await page.locator('body').waitFor({state:'visible'});const html_document_text=await page.locator('body').innerText();const outbound_links=await page.locator('a[href]').evaluateAll(xs=>xs.map(x=>x.href));await onReceipt({request_url:request.url,html_document_text,outbound_links});}});await crawler.run();}\nmodule.exports={run};\n`;return {source,sha256:sha256(source)};}
function ledgerPath(request){return path.join(request.paths.runtime_dir,'command-ledger.json')}
function loadLedger(request){const p=ledgerPath(request);return fs.existsSync(p)?readJson(p):{schema_version:'A6_COMMAND_LEDGER_V1',commands:{}}}
function saveLedger(request,l){writeJson(ledgerPath(request),l)}
function duplicateCommandReceipt(request,ledger){const old=ledger.commands[request.command_id];return old?{schema_version:'ADAPTER_BUILD_RUN_RECEIPT_V1',command_id:request.command_id,status:'NOOP_DUPLICATE_COMMAND',duplicate_command:true,reused_receipt_sha256:old.receipt_sha256,executed_step_count:0,exit_code:EXIT.PASS}:null}
function build(request){validateRequest(request);const a4=readJson(request.paths.a4_receipt);const a5=readJson(request.paths.a5_receipt);validateUpstream(a4,a5);const recipe=recipeFromReceipts(request,a4,a5);const compiled=compileAdapter(recipe);writeJson(request.paths.generated_recipe,recipe);fs.mkdirSync(path.dirname(request.paths.generated_adapter),{recursive:true});fs.writeFileSync(request.paths.generated_adapter,compiled.source);const manifest={schema_version:'A6_EXECUTABLE_ADAPTER_PACKAGE_V1',recipe_path:request.paths.generated_recipe,adapter_path:request.paths.generated_adapter,recipe_sha256:digest(recipe),adapter_sha256:compiled.sha256,runtime:['playwright','crawlee'],commands:['build','run','resume','cleanup','repair-step'],recipe_version:request.recipe_version,adapter_version:request.adapter_version};writeJson(request.paths.package_manifest,manifest);return manifest;}
function fixtureStep(step,state){if(step.type==='Navigate'){state.url=state.start_url;return {kind:'Navigate',url:state.url}}if(step.type==='Wait')return {kind:'Wait',locator:step.locator.value,state:step.state};if(step.type==='Extract'){const outputs={html_document_text:'Fixture Document',outbound_links:['https://example.invalid/a']};state.outputs.push(outputs);return {kind:'Extract',outputs_sha256:digest(outputs)}}throw new Error(`UNSUPPORTED_FIXTURE_STEP:${step.type}`)}
function runFixture(request,{resume=false,stopAfter=null}={}){validateRequest(request);const ledger=loadLedger(request);if(!resume){const dup=duplicateCommandReceipt(request,ledger);if(dup)return dup;}const recipe=readJson(request.paths.generated_recipe);const cpPath=path.join(request.paths.runtime_dir,'checkpoints',`${request.checkpoint_id}.json`);let cp=loadCheckpoint(cpPath,{checkpoint_id:request.checkpoint_id,command_id:request.command_id,recipe_id:recipe.recipe_id,recipe_version:request.recipe_version,adapter_version:request.adapter_version});const state={start_url:recipe.start_url,url:null,outputs:[]};let executed=0,skipped=0;const start=resume?cp.resume_from_step:0;for(let i=start;i<recipe.steps.length;i++){const step=recipe.steps[i];const key=stepIdempotencyKey({recipe_id:recipe.recipe_id,recipe_version:request.recipe_version,adapter_version:request.adapter_version,step_id:step.step_id,normalized_input:step,cursor:cp.cursor});if((cp.completed_idempotency_keys||[]).includes(key)){skipped++;continue;}const result=fixtureStep(step,state);const receipt={step_id:step.step_id,status:'PASS',idempotency_key:key,result};markStepComplete(cp,{step_index:i,step_id:step.step_id,idempotency_key:key,receipt,cursor:cp.cursor});cp=saveCheckpoint(cpPath,cp);executed++;if(stopAfter&&executed>=stopAfter){cp.status='INTERRUPTED_FOR_SMOKE';cp=saveCheckpoint(cpPath,cp);break;}}if(cp.resume_from_step>=recipe.steps.length){cp.status='COMPLETED';cp=saveCheckpoint(cpPath,cp)}const receipt={schema_version:'ADAPTER_BUILD_RUN_RECEIPT_V1',command_id:request.command_id,checkpoint_id:request.checkpoint_id,status:cp.status==='COMPLETED'?'PASS':'CHECKPOINTED',action:resume?'resume':'run',recipe_version:request.recipe_version,adapter_version:request.adapter_version,last_completed_step:cp.last_completed_step,resume_from_step:cp.resume_from_step,executed_step_count:executed,skipped_completed_step_count:skipped,completed_idempotency_key_count:cp.completed_idempotency_keys.length,output_sha256:digest(state.outputs),checkpoint_sha256:cp.checkpoint_sha256,exit_code:EXIT.PASS};writeJson(request.paths.run_receipt,receipt);if(receipt.status==='PASS'){ledger.commands[request.command_id]={receipt_sha256:digest(receipt),checkpoint_id:request.checkpoint_id,status:'PASS'};saveLedger(request,ledger)}return receipt;}
function cleanup(request){try{if(fs.existsSync(request.paths.runtime_dir))fs.rmSync(request.paths.runtime_dir,{recursive:true,force:true});return {status:'PASS',exit_code:EXIT.PASS}}catch(e){throw Object.assign(e,{exitCode:EXIT.CLEANUP_FAILED})}}
function repairStep(request,stepId,replacementPath){try{const recipe=readJson(request.paths.generated_recipe);const repl=readJson(replacementPath);const idx=recipe.steps.findIndex(s=>s.step_id===stepId);if(idx<0)throw new Error('STEP_NOT_FOUND');const before=recipe.steps[idx];if(repl.step_id!==stepId)throw new Error('STEP_ID_MISMATCH');recipe.steps[idx]=repl;writeJson(request.paths.generated_recipe,recipe);const receipt={schema_version:'A6_PARTIAL_REPAIR_RECEIPT_V1',step_id:stepId,before_sha256:digest(before),after_sha256:digest(repl),scope:'FAILED_STEP_ONLY',full_recipe_regeneration:false,status:'PASS'};writeJson(path.join(request.paths.runtime_dir,'partial-repair-receipt.json'),receipt);return receipt}catch(e){throw Object.assign(e,{exitCode:EXIT.PARTIAL_REPAIR_FAILED})}}
function main(){const [command,requestPath,...rest]=process.argv.slice(2);let exit=EXIT.PASS;try{if(!command||!requestPath)throw Object.assign(new Error('usage: node SUCCESSOR_ADAPTER_BUILD_RUNNER_V1.cjs <build|run|resume|cleanup|repair-step|build-run-resume> <request.json> [...]'),{exitCode:EXIT.INVALID_REQUEST});const request=readJson(requestPath);let out;if(command==='build')out=build(request);else if(command==='run')out=runFixture(request);else if(command==='resume')out=runFixture(request,{resume:true});else if(command==='cleanup')out=cleanup(request);else if(command==='repair-step')out=repairStep(request,rest[0],rest[1]);else if(command==='build-run-resume'){const b=build(request);const r=runFixture(request,{stopAfter:1});const rr=runFixture(request,{resume:true});out={build:b,checkpoint_run:r,resume:rr,status:rr.status==='PASS'?'PASS':'FAILED'};}else throw Object.assign(new Error('UNKNOWN_COMMAND'),{exitCode:EXIT.UNKNOWN_COMMAND});console.log(JSON.stringify(out));}catch(e){exit=e.exitCode??EXIT.RUN_FAILED;console.error(JSON.stringify({status:'ERROR',message:e.message,exit_code:exit}));}process.exitCode=exit;}
module.exports={EXIT,validateRequest,validateUpstream,recipeFromReceipts,compileAdapter,build,runFixture,cleanup,repairStep,digest};
if(require.main===module)main();
