'use strict';
const assert=require('node:assert/strict');
const {buildImplementationContract}=require('./product_api_data_form_contract.cjs');
let n=0;const eq=(a,b)=>{assert.deepEqual(a,b);n++};const ok=x=>{assert.ok(x);n++};
const c5={schema_version:'A5_API_UI_STATE_ENTITY_SEMANTIC_BINDING_RESULT_V1',semantic_digest:'c5digest',evidence_pointer:['github://a3','github://a4'],api_ui_state_binding_graph:{nodes:[
{node_id:'ACTION:CMD-1:page-1:ACT-1',node_type:'ACTION',command_id:'CMD-1',page_id:'page-1',action_id:'ACT-1',action_kind:'submit',evidence_pointer:'github://a3/action'},
{node_id:'ENDPOINT:EP-1',node_type:'API_ENDPOINT',endpoint_id:'EP-1',request_id:'REQ-1',method:'POST',url_template:'https://fixture.local/api/items',evidence_pointer:'github://a3/request'},
{node_id:'ENTITY:ENT-1',node_type:'DATA_ENTITY',entity_id:'ENT-1',record_path:'$.record',request_id:'REQ-1',evidence_pointer:'github://a3/body'},
{node_id:'STATE:item-list:s1',node_type:'UI_STATE_TRANSITION',component_id:'item-list',state_before:'COUNT_1',state_after:'COUNT_2',evidence_pointer:'github://a3/state'}],edges:[
{from:'ACTION:CMD-1:page-1:ACT-1',to:'ENDPOINT:EP-1',relation:'ACTION_TRIGGERS_ENDPOINT',authority:'OBSERVED',confidence:1,evidence_pointer:['github://a3/action','github://a3/request']},
{from:'ENDPOINT:EP-1',to:'ENTITY:ENT-1',relation:'ENDPOINT_RETURNS_ENTITY',authority:'OBSERVED',confidence:1,evidence_pointer:'github://a3/body'},
{from:'ACTION:CMD-1:page-1:ACT-1',to:'STATE:item-list:s1',relation:'ACTION_TRANSITIONS_UI_STATE',authority:'OBSERVED',confidence:1,evidence_pointer:'github://a3/state'}],unresolved_bindings:[{relation:'ENTITY_PRESENTED_BY_COMPONENT',status:'INSUFFICIENT_EVIDENCE',evidence_pointer:'github://a4'}]},data_entity_graph:{nodes:[{entity_id:'ENT-1',record_path:'$.record',request_id:'REQ-1',identifier_paths:['$.record.record_id'],authority:'OBSERVED_REDACTED_BODY',evidence_pointer:'github://a3/body',application_fields:[{source_field:'price',json_path:'$.record.price',application_canonical_candidate:'price',authority:'APPLICATION_CANDIDATE_ONLY',confidence:.95,evidence_pointer:'github://a3/body',d_canonical_authority:false}]}],edges:[],business_rules:{status:'UNKNOWN',reason:'BUSINESS_RULES_NOT_OBSERVED'}},form_field_semantic_candidate:{candidates:[{form_id:'item-form',field_name:'price',application_canonical_candidate:{name:'price',json_path:'$.record.price',authority:'APPLICATION_CANDIDATE_ONLY',confidence:.95,evidence_pointer:'github://a3/body',d_canonical_authority:false},read_transform:{from:'$.record.price',to:'price',transform:'IDENTITY_CANDIDATE',authority:'CANDIDATE',confidence:.9,evidence_pointer:'github://a3/body'},write_transform:{from:'price',to:'price',location:'body',transform:'IDENTITY_CANDIDATE',authority:'CANDIDATE',confidence:.82,evidence_pointer:'github://a3/request'},business_rule:{status:'UNKNOWN',reason:'BUSINESS_RULE_NOT_OBSERVED'}}]},raw_secret_value_count:0};
const a=buildImplementationContract(c5),b=buildImplementationContract(c5);
eq(a.schema_version,'A5_PRODUCT_API_DATA_FORM_IMPLEMENTATION_CONTRACT_RESULT_V1');eq(a.product_api_contract.schema_version,'PRODUCT_API_CONTRACT_V1');eq(a.data_model_implementation_spec.schema_version,'DATA_MODEL_IMPLEMENTATION_SPEC_V1');eq(a.form_write_binding_spec.schema_version,'FORM_WRITE_BINDING_SPEC_V1');eq(a.product_api_contract.operations.length,1);eq(a.product_api_contract.operations[0].semantic_status,'OBSERVED');eq(a.product_api_contract.operations[0].response_entities[0].semantic_status,'OBSERVED');eq(a.product_api_contract.operations[0].ui_state_updates[0].state_after,'COUNT_2');eq(a.data_model_implementation_spec.entities[0].fields[0].semantic_status,'INFERRED');eq(a.data_model_implementation_spec.entities[0].fields[0].d_canonical_authority,false);eq(a.form_write_binding_spec.bindings[0].canonical_semantic_status,'INFERRED');eq(a.form_write_binding_spec.bindings[0].write_transform.semantic_status,'INFERRED');eq(a.form_write_binding_spec.bindings[0].business_rule.status,'UNKNOWN');eq(a.d_canonical_schema_decision,false);eq(a.production_db_write,false);eq(a.raw_secret_value_count,0);eq(a.raw_pii_value_count,0);eq(a.implementation_digest,b.implementation_digest);ok(/^[a-f0-9]{64}$/.test(a.implementation_digest));eq(a.decision_status,'READY_WITH_INSUFFICIENT_EVIDENCE');
const unknown=JSON.parse(JSON.stringify(c5));unknown.api_ui_state_binding_graph.edges=unknown.api_ui_state_binding_graph.edges.filter(e=>e.relation==='ACTION_TRIGGERS_ENDPOINT');const u=buildImplementationContract(unknown);eq(u.product_api_contract.operations[0].response_entities[0].status,'UNKNOWN');eq(u.product_api_contract.operations[0].ui_state_updates[0].status,'UNKNOWN');
const secret=JSON.parse(JSON.stringify(c5));secret.extra='Bearer SECRETSECRET';assert.throws(()=>buildImplementationContract(secret),/RAW_SECRET_VALUE_REJECTED/);n++;
const pii=JSON.parse(JSON.stringify(c5));pii.customer={email:'person@example.com'};assert.throws(()=>buildImplementationContract(pii),/RAW_PII_VALUE_REJECTED/);n++;
console.log(JSON.stringify({status:'PASS',fixture_replay_count:2,assertions:n,digest1:a.implementation_digest,digest2:b.implementation_digest,decision_status:a.decision_status}));
