'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
const {recover}=require('../RECOVER_WORK_BOOTSTRAP_V1.cjs');
function w(root,rel,obj){const f=path.join(root,rel);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,JSON.stringify(obj,null,2));}
function build({state,taskPass=null,blocked=false,withDup=false}){
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'a7-v3-'));
 const cmd={schema_version:'AI001_ACTIVE_COMMAND_V1',command_id:'CMD-X',worker_id:'A-3',idempotency_key:'KEY-X',status:'RUNNING',safe_rerun:true,non_idempotent_side_effect_committed:false};
 const events=[];
 if(withDup){events.push({schema_version:'WORKER_BROWSER_STATE_EVENT_V1',worker_id:'A-3',command_id:'CMD-X',event_id:'e1',sequence_no:1,state:'GENERATING',task_pass:null});events.push({...events[0]});events.push({...events[0],event_id:'e2',sequence_no:2});events.push({...events[0],event_id:'stale',sequence_no:1});}
 else events.push({schema_version:'WORKER_BROWSER_STATE_EVENT_V1',worker_id:'A-3',command_id:'CMD-X',event_id:'e1',sequence_no:1,state,task_pass:taskPass,blocker:blocked?{code:'FIXTURE_BLOCKER'}:null});
 const pointer={schema_version:'LATEST_AI001_MISSION_POINTER_V1',mission_id:'M',current_mission_state:'state/CURRENT_MISSION_STATE.json',active_command:'state/ACTIVE_COMMAND.json',worker_state_events:'state/WORKER_EVENTS.json',latest_result:'state/LATEST_RESULT.json',checkpoint_directory:'checkpoints',recovery_brief:'AI001_RECOVERY_BRIEF_V1.json',late_binding:{}};
 w(root,'LATEST_AI001_MISSION_POINTER_V1.json',pointer);w(root,'state/CURRENT_MISSION_STATE.json',{phase:'P',last_completed_command_id:'CMD-PREV'});w(root,'state/ACTIVE_COMMAND.json',cmd);w(root,'state/WORKER_EVENTS.json',events);w(root,'state/LATEST_RESULT.json',{status:'PENDING',idempotency_key:null});w(root,'checkpoints/0001.json',{checkpoint_id:'CP-1',sequence_no:1,command_id:'CMD-X',idempotency_key:'KEY-X',durable:true,artifact_manifest:[]});w(root,'AI001_RECOVERY_BRIEF_V1.json',{next_work:'NEXT'});return root;
}
test('smoke 1: context loss during GENERATING suppresses duplicate command',()=>{const r=build({state:'GENERATING',withDup:true});const x=recover(path.join(r,'LATEST_AI001_MISSION_POINTER_V1.json'));assert.equal(x.worker_state.state,'GENERATING');assert.equal(x.recovery_decision.decision,'SAFE_TO_RESUME');assert.equal(x.recovery_decision.command_reissue,false);assert.equal(x.next_action,'OBSERVE_EXISTING_WORKER_GENERATION');assert.ok(x.worker_event_suppressed_count>=2);});
test('smoke 2: COMPLETE before review is not TASK PASS',()=>{const r=build({state:'COMPLETE',taskPass:null});const x=recover(path.join(r,'LATEST_AI001_MISSION_POINTER_V1.json'));assert.equal(x.complete_is_task_pass,false);assert.equal(x.recovery_decision.decision,'SAFE_TO_RESUME');assert.equal(x.next_action,'REVIEW_COMPLETED_WORKER_RESULT');});
test('smoke 3: BLOCKED reconstructs blocker next action',()=>{const r=build({state:'BLOCKED',blocked:true});const x=recover(path.join(r,'LATEST_AI001_MISSION_POINTER_V1.json'));assert.equal(x.recovery_decision.decision,'BLOCKED');assert.match(x.recovery_decision.reason,/FIXTURE_BLOCKER/);assert.equal(x.next_action,'SURFACE_WORKER_BLOCKER');});
test('smoke 4: UNKNOWN never reissues command',()=>{const r=build({state:'UNKNOWN'});const x=recover(path.join(r,'LATEST_AI001_MISSION_POINTER_V1.json'));assert.equal(x.recovery_decision.decision,'BLOCKED');assert.equal(x.recovery_decision.command_reissue,false);assert.equal(x.next_action,'REFRESH_WORKER_STATE_BEFORE_ANY_REISSUE');});
