'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const stable=v=>Array.isArray(v)?v.map(stable):v&&typeof v==='object'?Object.keys(v).sort().reduce((a,k)=>(a[k]=stable(v[k]),a),{}):v;
const sha=v=>crypto.createHash('sha256').update(JSON.stringify(stable(v))).digest('hex');
const read=p=>JSON.parse(fs.readFileSync(p,'utf8')); const write=(p,v)=>{fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,JSON.stringify(v,null,2)+'\n')};
function validate(a4,a5){if(a4?.schema_version!=='STRUCTURE_INFERENCE_RUN_RECEIPT_V1'||!Array.isArray(a4.fields)||!a4.fields.length)throw Error('A4_STRUCTURE_INVALID');if(a5?.status!=='PASS'||a5?.validation?.fixture_smoke!=='PASS')throw Error('A5_DECISION_INPUT_INVALID')}
function bestLocator(a4,f){return (a4.locator_candidates||[]).filter(x=>x.field_id===f.field_id).sort((a,b)=>b.stability_score-a.stability_score)[0]?.locator||`locator(${JSON.stringify(f.source_locator)})`}
function makeDecision(a4,a5,commandId){return{schema_version:'A5_RECIPE_DECISION_INPUT_CONSUMED_V1',command_id:commandId,decision_status:'PASS',recommended_mode:a5.validation.full_evidence_mode||'DOM',structure_confidence:a4.confidence,fields:a4.fields.map(f=>({name:f.name,source_locator:f.source_locator,compiled_locator:bestLocator(a4,f)})),pagination:(a4.pagination_candidates||[])[0]||{detected:false},unevidenced_endpoint_or_response_body_fields:'NOT_INVENTED',source:{a4_receipt_sha256:a4.receipt_sha256||null,a5_validation_directive:a5.directive_id}}}
function makeRecipe(a4,d,commandId){const pageId=a4.page_identity.page_id;return{schema_version:'EXTRACTION_RECIPE_V1',recipe_version:'1.0.0-cycle3',adapter_version:'1.0.0-cycle3',recipe_id:`${commandId}:recipe`,command_id:commandId,page_id:pageId,recommended_mode:d.recommended_mode,steps:[{step_id:'s01',action_id:`${commandId}:a01`,page_id:pageId,type:'Navigate',url:a4.page_identity.url},{step_id:'s02',action_id:`${commandId}:a02`,page_id:pageId,type:'Wait',locator:a4.repeated_regions?.[0]?.parent_node_id||'records',state:'visible'},{step_id:'s03',action_id:`${commandId}:a03`,page_id:pageId,type:'Extract',fields:d.fields},{step_id:'s04',action_id:`${commandId}:a04`,page_id:pageId,type:'Pagination',mode:d.pagination.type||'NONE',evidence:d.pagination.evidence||null,stop_condition:d.pagination.stop_condition||'NONE'}],safety:{fixture_only:true,live_site_call:false,production:false,ready:false,merge:false}}}
function compile(r){const source=`'use strict';\nconst {PlaywrightCrawler,RequestQueue}=require('crawlee');\nasync function run({startUrl,onReceipt}){const q=await RequestQueue.open(${JSON.stringify('a6-c3-') }+${JSON.stringify(r.recipe_id)});await q.addRequest({url:startUrl});const crawler=new PlaywrightCrawler({requestQueue:q,maxRequestRetries:2,requestHandler:async({page,request})=>{await page.locator('body').waitFor({state:'visible'});await onReceipt({command_id:${JSON.stringify(r.command_id)},page_id:${JSON.stringify(r.page_id)},request_url:request.url,status:'PASS'});}});await crawler.run();}\nmodule.exports={run};\n`;return{source,sha256:sha(source)}}
function idem(r,s){return sha({command_id:r.command_id,recipe_version:r.recipe_version,adapter_version:r.adapter_version,action_id:s.action_id,page_id:s.page_id,step_id:s.step_id,step:s})}
function execute(r,{checkpoint=null,failAtStep=null}={}){let cp=checkpoint||{schema_version:'ADAPTER_CHECKPOINT_RESUME_V1',checkpoint_id:`cp-${r.command_id}`,command_id:r.command_id,recipe_version:r.recipe_version,adapter_version:r.adapter_version,last_completed_step:null,resume_from_step:0,completed_idempotency_keys:[],receipts:[],status:'RUNNING'};let executed=0,skipped=0;for(let i=cp.resume_from_step;i<r.steps.length;i++){const s=r.steps[i],k=idem(r,s);if(failAtStep===s.step_id){cp.status='FAILED';cp.failed_step=s.step_id;cp.resume_from_step=i;cp.checkpoint_sha256=sha({...cp,checkpoint_sha256:undefined});return{checkpoint:cp,receipt:{schema_version:'ADAPTER_REPLAY_RECEIPT_V1',command_id:r.command_id,checkpoint_id:cp.checkpoint_id,status:'FAILED',failed_step:s.step_id,executed_step_count:executed,last_completed_step:cp.last_completed_step,resume_from_step:i,recipe_version:r.recipe_version,adapter_version:r.adapter_version}}}if(cp.completed_idempotency_keys.includes(k)){skipped++;continue}cp.receipts.push({command_id:r.command_id,action_id:s.action_id,page_id:s.page_id,step_id:s.step_id,status:'PASS',idempotency_key:k});cp.completed_idempotency_keys.push(k);cp.last_completed_step=s.step_id;cp.resume_from_step=i+1;executed++}cp.status='COMPLETED';cp.checkpoint_sha256=sha({...cp,checkpoint_sha256:undefined});return{checkpoint:cp,receipt:{schema_version:'ADAPTER_REPLAY_RECEIPT_V1',command_id:r.command_id,checkpoint_id:cp.checkpoint_id,status:'COMPLETED',executed_step_count:executed,skipped_completed_step_count:skipped,last_completed_step:cp.last_completed_step,resume_from_step:cp.resume_from_step,recipe_version:r.recipe_version,adapter_version:r.adapter_version}}}
function runComposite(req){const a4=read(req.a4_path),a5=read(req.a5_path);validate(a4,a5);const decision=makeDecision(a4,a5,req.command_id),recipe=makeRecipe(a4,decision,req.command_id),compiled=compile(recipe),full=execute(recipe),failed=execute(recipe,{failAtStep:'s03'}),resumed=execute(recipe,{checkpoint:JSON.parse(JSON.stringify(failed.checkpoint))});if(failed.receipt.resume_from_step!==2||resumed.receipt.executed_step_count!==2||resumed.checkpoint.status!=='COMPLETED')throw Error('RESUME_VALIDATION_FAILED');const bundle={schema_version:'ADAPTER_EXECUTION_BUNDLE_V1',consumer:'B-1',command_id:req.command_id,decision,recipe,compiled_adapter:{runtime:['Playwright','Crawlee'],sha256:compiled.sha256},lineage:{command_id:req.command_id,action_ids:recipe.steps.map(s=>s.action_id),page_id:recipe.page_id},resume:{checkpoint_id:resumed.checkpoint.checkpoint_id,last_completed_step:resumed.checkpoint.last_completed_step,resume_from_step:resumed.checkpoint.resume_from_step},browser_worker_completion_event:{usage:'EXECUTION_LIFECYCLE_ONLY',adapter_technical_pass_source:false,mixed_with_adapter_pass:false},reanalyze_required:false};return{decision,recipe,compiled,full,failed,resumed,bundle}}
if(require.main===module){try{const req=read(process.argv[2]);const r=runComposite(req);write(req.out_bundle,r.bundle);write(req.out_recipe,r.recipe);fs.mkdirSync(path.dirname(req.out_adapter),{recursive:true});fs.writeFileSync(req.out_adapter,r.compiled.source);write(req.out_full_receipt,r.full.receipt);write(req.out_failure_receipt,r.failed.receipt);write(req.out_checkpoint,r.failed.checkpoint);write(req.out_resume_receipt,r.resumed.receipt);console.log(JSON.stringify({status:'PASS',bundle_sha256:sha(r.bundle),compiled_adapter_sha256:r.compiled.sha256}))}catch(e){console.error(e.stack);process.exit(1)}}
module.exports={validate,makeDecision,makeRecipe,compile,execute,runComposite,sha};
