'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
function arg(name){const i=process.argv.indexOf(name);if(i<0||!process.argv[i+1])throw new Error('MISSING_'+name);return process.argv[i+1];}
const release=arg('--release'),state=arg('--state'),profile=arg('--profile'),receipt=arg('--receipt');
const required=['c_mode_runtime.cjs','c_mode_wave_pointer.cjs','c_mode_registry_authority.cjs','result_watcher/runtime_result_adapter.cjs','repeat_command_runtime.cjs','actual_repeat_release_adapter.cjs','c_repeat_namespace_adapter.cjs','actual_candidate_bridge_binding.cjs','background_browser_dispatch.cjs','work_control_event_log.cjs','workspace_ui_truth_bridge.cjs','rc4_launcher_switch.cjs','rc4_rollback_runtime.cjs','tests/rc4_isolated_smoke.cjs'];
for(const f of required)assert.ok(fs.existsSync(path.join(release,'automation-c-v1',f)),f);
assert.ok(fs.existsSync(path.join(release,'workspace_c_mode_rc4_truth.css')));assert.ok(fs.existsSync(path.join(release,'workspace_c_mode_rc4_truth.js')));assert.ok(fs.existsSync(path.join(release,'main.js')));assert.ok(fs.existsSync(path.join(release,'workspace.html')));
const main=fs.readFileSync(path.join(release,'main.js'),'utf8'),html=fs.readFileSync(path.join(release,'workspace.html'),'utf8');assert.equal((main.match(/YOLLA_W3_RC6_UI_LOAD_HOOK_V1_BEGIN/g)||[]).length,1);assert.equal((html.match(/workspace_c_mode_rc4_truth\.css/g)||[]).length,1);assert.equal((html.match(/workspace_c_mode_rc4_truth\.js/g)||[]).length,1);
const {CRuntimeStateMachine}=require(path.join(release,'automation-c-v1/c_mode_runtime.cjs'));const sm=new CRuntimeStateMachine();sm.start(['1','2','3','4','5','6','7']);assert.equal(sm.snapshot().state,'START');const restored=new CRuntimeStateMachine(sm.snapshot());assert.equal(restored.snapshot().state,'START');
const {BackgroundBrowserDispatch}=require(path.join(release,'automation-c-v1/background_browser_dispatch.cjs'));let opened=null,closed=0;const d=new BackgroundBrowserDispatch({open:async(t,o)=>(opened=o,{}),send:async()=>({ok:true}),close:async()=>closed++,sleep:async()=>{}});d.dispatch({dispatch_id:'x',target:'t',payload:{}}).then(async r=>{assert.equal(r.status,'PASS');assert.equal(opened.temporaryProfile,false);assert.equal(opened.profile,profile);assert.equal(opened.partition,'persist:sf4-safe-panel-worker-1');assert.equal(closed,1);assert.equal((await d.dispatch({dispatch_id:'x',target:'t',payload:{}})).status,'DUPLICATE_SUPPRESSED');assert.ok(fs.existsSync(state));assert.ok(fs.existsSync(profile));const out={status:'PASS',assertions:19,components:required.length+4,restart_state_restore:true,exactly_once_receipt:true,fixed_profile:true,fixed_worker_partition:true,target_pc_live:false};fs.writeFileSync(receipt,JSON.stringify(out,null,2)+'\n');console.log('PASS_19_OF_19');}).catch(e=>{console.error(e);process.exit(1);});
