import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const run=(receipts,out)=>spawnSync(process.execPath,[path.join(root,'tools/rebuild_ui_state.mjs'),'--binding',path.join(root,'CONTEXT_INDEPENDENT_UI_BINDING_V1.json'),'--state',path.join(root,'SITE_ANALYZER_UI_STATE_V1.json'),'--receipts',receipts,'--out',out],{encoding:'utf8'});
const fixture=path.join(root,'fixtures/FIXTURE_RECEIPT_SET_V1.json');
const out1=path.join(root,'fixtures/.rebuilt1.json');
let r=run(fixture,out1); assert.equal(r.status,0,r.stderr); const s1=JSON.parse(fs.readFileSync(out1));
assert.equal(s1.source_states['A-3'],'COMPLETE');
assert.equal(s1.source_states['A-4'],'COMPLETE');
assert.equal(s1.source_states['A-5'],'BLOCKED');
assert.equal(s1.source_states['A-6'],'COMPLETE');
assert.equal(s1.source_states['B-1'],'BLOCKED');
assert.equal(s1.viewmodels.live_session.session_id,'s-1');
assert.equal(s1.viewmodels.live_session.selected_page_id,'p-1');
assert.equal(s1.restore.chat_context_required,false);
const missing=JSON.parse(fs.readFileSync(fixture)); delete missing.receipts['A-4']; const missingPath=path.join(root,'fixtures/.missing.json'); fs.writeFileSync(missingPath,JSON.stringify(missing)); const out2=path.join(root,'fixtures/.rebuilt2.json');
r=run(missingPath,out2); assert.equal(r.status,0,r.stderr); const s2=JSON.parse(fs.readFileSync(out2));
assert.equal(s2.source_states['A-4'],'UNBOUND');
assert.equal(s2.source_states['A-5'],'BLOCKED');
assert.ok(s2.restore.view_state_digest);
for(const f of ['.rebuilt1.json','.rebuilt2.json','.missing.json']) fs.rmSync(path.join(root,'fixtures',f),{force:true});
console.log(JSON.stringify({status:'PASS',checks:12,fixture_viewmodel_rebuild_smoke:'PASS',missing_receipt_no_inference:'PASS'}));
