#!/usr/bin/env node
'use strict';
const fs=require('node:fs');const path=require('node:path');const crypto=require('node:crypto');
const MODES=['DATA','PRODUCT','WRITE','MY_LISTING','EDIT'];
const STAGES={DATA:['SOURCE_DISCOVERY','LIVE_OBSERVATION','STRUCTURE_INFERENCE'],PRODUCT:['PRODUCT_DISCOVERY','BLUEPRINT','PREVIEW'],WRITE:['ADAPTER_DRAFT','VALIDATE','COMMIT'],MY_LISTING:['READ','MAP','VERIFY'],EDIT:['LOAD','PATCH','VALIDATE']};
function readJson(f){return JSON.parse(fs.readFileSync(f,'utf8'));}
function safe(root,rel){if(path.isAbsolute(rel))throw new Error('ABSOLUTE_PATH_REJECTED');const p=path.resolve(root,rel);if(p!==root&&!p.startsWith(root+path.sep))throw new Error('PATH_TRAVERSAL_REJECTED');return p;}
function digest(v){return crypto.createHash('sha256').update(JSON.stringify(v)).digest('hex');}
function preserveEvidence(map){const out={};for(const [k,v] of Object.entries(map.entries||{})){if(!['OBSERVED','INFERRED','UNKNOWN'].includes(v.state))throw new Error(`INVALID_EVIDENCE_STATE:${k}`);if(typeof v.confidence!=='number'||v.confidence<0||v.confidence>1)throw new Error(`INVALID_CONFIDENCE:${k}`);if((v.state==='OBSERVED'||v.state==='INFERRED')&&!v.evidence_pointer)throw new Error(`EVIDENCE_POINTER_REQUIRED:${k}`);out[k]={state:v.state,confidence:v.confidence,evidence_pointer:v.evidence_pointer??null};}return out;}
function completedSet(state){const s=new Set();for(const mode of MODES){for(const row of state.modes?.[mode]?.stages||[]){if(['COMPLETE','PASS'].includes(row.status))s.add(`${mode}:${row.stage}`);}}return s;}
function nextIncomplete(state,fromMode,fromStage,extraComplete=new Set()){const done=completedSet(state);for(const x of extraComplete)done.add(x);let started=false;for(const mode of MODES){for(const stage of STAGES[mode]){if(!started){if(mode===fromMode&&stage===fromStage)started=true;else continue;}if(!done.has(`${mode}:${stage}`))return{mode,stage};}}return null;}
function buildResumePlan(state,extraComplete=new Set()){const done=completedSet(state);for(const x of extraComplete)done.add(x);const plan=[];for(const mode of MODES)for(const stage of STAGES[mode])if(!done.has(`${mode}:${stage}`))plan.push({mode,stage});return plan;}
function writeDecision(cmd,checkpoint,partial){if(cmd.mode!=='WRITE')return null;if(partial.length)return{decision:'NEEDS_REPAIR'};if(checkpoint?.durable&&checkpoint.command_id===cmd.command_id&&checkpoint.idempotency_key===cmd.idempotency_key)return{decision:'RESUME_FROM_CHECKPOINT',resume_from:checkpoint.checkpoint_id};if(cmd.safe_rerun===true&&cmd.non_idempotent_side_effect_committed!==true)return{decision:'SAFE_RERUN_CURRENT_STAGE'};return{decision:'BLOCKED'};}
function partialBlueprint(blueprint){const fields=blueprint.fields||[];const keep=fields.filter(x=>x.status==='COMPLETE');const missing=fields.filter(x=>x.status!=='COMPLETE');return{status:blueprint.status,completed_field_count:keep.length,pending_field_count:missing.length,completed_fields:keep.map(x=>x.field),pending_fields:missing.map(x=>x.field)};}
function recover(pointerFile){const root=path.dirname(pointerFile);const p=readJson(pointerFile);const mission=readJson(safe(root,p.current_mission));const cmd=readJson(safe(root,p.current_command));const result=readJson(safe(root,p.latest_result));const state=readJson(safe(root,p.recovery_state));const evidence=preserveEvidence(readJson(safe(root,p.evidence_map)));const blueprint=readJson(safe(root,p.partial_product_blueprint));const write=readJson(safe(root,p.write_resume_decision));const checkpoint=readJson(safe(root,p.checkpoint));const done=completedSet(state);const currentKey=`${cmd.mode}:${cmd.stage}`;const resultSame=result.idempotency_key&&result.idempotency_key===cmd.idempotency_key&&result.status==='PASS';const stageAlreadyDone=done.has(currentKey)||resultSame;let decision,nextAction,extra=new Set();if(stageAlreadyDone){extra.add(currentKey);const n=nextIncomplete(state,cmd.mode,cmd.stage,extra);decision='ALREADY_DONE';nextAction=n?{action:'ADVANCE_TO_NEXT_INCOMPLETE_STAGE',...n}:{action:'MISSION_COMPLETE'};}else if(cmd.mode==='PRODUCT'&&cmd.stage==='BLUEPRINT'&&['PARTIAL','RUNNING','INTERRUPTED'].includes(cmd.status)){const bp=partialBlueprint(blueprint);decision=bp.pending_field_count?'RESUME_PARTIAL_PRODUCT_BLUEPRINT':'ALREADY_DONE';nextAction=bp.pending_field_count?{action:'RESUME_PRODUCT_BLUEPRINT',mode:'PRODUCT',stage:'BLUEPRINT',preserve_completed_fields:true,pending_fields:bp.pending_fields}:{action:'ADVANCE_TO_NEXT_INCOMPLETE_STAGE',...nextIncomplete(state,'PRODUCT','BLUEPRINT',new Set(['PRODUCT:BLUEPRINT']))};}else if(cmd.mode==='WRITE'){const wd=writeDecision(cmd,checkpoint,[]);decision=wd.decision;nextAction=wd.decision==='RESUME_FROM_CHECKPOINT'?{action:'RESUME_WRITE_ADAPTER',resume_from:wd.resume_from}:{action:wd.decision};}else{decision='SAFE_TO_RESUME';nextAction={action:'RESUME_CURRENT_STAGE',mode:cmd.mode,stage:cmd.stage};}const resumePlan=buildResumePlan(state,extra);if(stageAlreadyDone&&resumePlan.some(x=>x.mode===cmd.mode&&x.stage===cmd.stage))throw new Error('COMPLETED_STAGE_PRESENT_IN_RESUME_PLAN');const out={schema_version:'MULTIMODE_CONTEXT_RECOVERY_READBACK_V1',recovery_order:['Latest Pointer','Current Mission','Current Command','Latest Result','Next Action'],mission:{mission_id:mission.mission_id,phase:mission.phase},current_command:cmd,latest_result:result,recovery_decision:decision,next_action:nextAction,completed_stage_count:done.size,completed_stage_reexecution_count:0,duplicate_execution_suppressed:stageAlreadyDone,evidence,recovered_evidence_digest:digest(evidence),partial_product_blueprint:partialBlueprint(blueprint),write_adapter_resume_contract:write,resume_plan:resumePlan,boundaries:{target_pc_execution:false,live_site_call:false,tunnel_change:false,production:false,ready:false,merge:false}};out.recovery_digest=digest({mission:out.mission,cmd:{id:cmd.command_id,key:cmd.idempotency_key},decision,nextAction,evidence,resumePlan});return out;}
if(require.main===module){const i=process.argv.indexOf('--pointer');const f=path.resolve(i>=0?process.argv[i+1]:'LATEST_AI001_MISSION_POINTER_V1.json');try{console.log(JSON.stringify(recover(f),null,2));}catch(e){console.error(e.stack||e.message);process.exitCode=2;}}
module.exports={recover,preserveEvidence,completedSet,nextIncomplete,partialBlueprint};
