'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { loadPointer, reconstruct, decide } = require('../recover-work.cjs');
function copyTree(src) { const dst = fs.mkdtempSync(path.join(os.tmpdir(), 'a7-recovery-')); fs.cpSync(src, dst, { recursive: true }); return dst; }
test('FIXTURE_INTERRUPTION_RECOVERY_SMOKE_1 chooses repair then resume and quarantines partials', () => { const root = copyTree(path.join(__dirname, '..', 'fixtures', 'interrupted')); const loaded = loadPointer(path.join(root, 'LATEST_MISSION_POINTER.json')); const state = reconstruct(loaded, { repair: true, now: Date.parse('2026-08-07T12:00:00Z') }); assert.equal(state.NEXT_ACTION.decision, 'REPAIR_THEN_RESUME'); assert.equal(state.NEXT_ACTION.resume_from, 'CP-002'); assert.ok(state.REPAIR.repairable_count >= 3); assert.equal(state.REPAIR.nonrepairable_count, 0); assert.ok(state.REPAIR.actions.some(x => x.action === 'quarantine_corrupt_partial')); assert.ok(state.LAST_PASS_COMMAND.command_id === 'CMD-001'); });
test('PASS receipt with same idempotency key suppresses duplicate execution', () => { const d = decide({ current:{command_id:'c',idempotency_key:'k',status:'INTERRUPTED'}, latest:{idempotency_key:'k',status:'PASS'}, checkpoint:{durable:true,checkpoint_id:'cp'}, blocker:null, repair:{repairable_count:0,nonrepairable_count:0}, now:0, staleAfterSec:60 }); assert.equal(d.decision, 'SKIP_DUPLICATE'); });
test('fresh running command is not stolen', () => { const now = Date.parse('2026-08-07T12:00:00Z'); const d = decide({ current:{command_id:'c',idempotency_key:'k',status:'RUNNING',heartbeat_at:'2026-08-07T11:59:30Z'}, latest:{idempotency_key:'old',status:'PASS'}, checkpoint:{durable:true,checkpoint_id:'cp'}, blocker:null, repair:{repairable_count:0,nonrepairable_count:0}, now, staleAfterSec:60 }); assert.equal(d.decision, 'BLOCKED'); assert.equal(d.reason, 'ACTIVE_EXECUTION_HEARTBEAT_FRESH'); });
test('stale command without durable checkpoint can safe rerun only when side effects are safe', () => { const now = Date.parse('2026-08-07T12:00:00Z'); const d = decide({ current:{command_id:'c',idempotency_key:'k',status:'INTERRUPTED',heartbeat_at:'2026-08-07T00:00:00Z',safe_rerun:true,non_idempotent_side_effect_committed:false}, latest:{idempotency_key:'old',status:'PASS'}, checkpoint:{durable:false}, blocker:null, repair:{repairable_count:0,nonrepairable_count:0}, now, staleAfterSec:60 }); assert.equal(d.decision, 'SAFE_RERUN'); });
