'use strict';
const assert = require('node:assert/strict');
const { bindCycle3, REQUIRED_PANEL_FIELDS } = require('./d6_cycle3_rebind_adapter.cjs');
const d2Cycle2={outcome:'PASS',terminal:'ACTIVE_CONTEXT_IDENTIFICATION_LIVE_PASS',retry_count:2,runtime_fields:{CONTEXT_ID:'6a72e288-7f24-83ee-b357-3e327cf6d877',CONTEXT_NAME:'자동화 C 모드',PAGE_ID:'UIA-TAB-42.198100.4.0.0.5287',STARTED_AT:'2026-08-07T16:39:00.000Z'}};
const d2Cycle3Guard={terminal:'LIVE_CONTEXT_HANDOFF_AND_FRESHNESS_GUARD_PASS'};
const d5Cycle2={terminal:'CYCLE2_REAL_RECEIPT_INGESTION_AND_BLOCKER_METRICS_PASS'};
const d5Cycle3={terminal:'D2_LIVE_RECOVERY_INGESTION_AND_METRIC_CLOSURE_PASS'};
const r=bindCycle3({d2Cycle2,d2Cycle3Guard,d5Cycle2,d5Cycle3,d4TerminalPresent:false,nowIso:'2026-08-07T18:32:00.000Z'});
assert.equal(r.ok,true);
assert.equal(r.resolved_blocker_count,2);
assert.equal(r.remaining_gap,'D4_OBSERVER_RECEIPT_MISSING');
assert.equal(r.remaining_gap_count,1);
assert.equal(r.d4_state_inferred,false);
assert.equal(r.synthetic_working_completed_count,0);
assert.equal(r.new_panel_count,0);
assert.equal(r.new_executor_count,0);
assert.equal(r.new_tunnel_count,0);
assert.equal(r.new_transport_count,0);
assert.equal(r.d3_wait_count,0);
assert.equal(Object.keys(r.panel).length,REQUIRED_PANEL_FIELDS.length);
for (const f of REQUIRED_PANEL_FIELDS) assert.ok(Object.prototype.hasOwnProperty.call(r.panel,f));
assert.equal(r.panel.context_id,d2Cycle2.runtime_fields.CONTEXT_ID);
assert.equal(r.panel.status,'PARTIAL_LIVE_D4_GAP');
assert.equal(r.panel.error,'D4_OBSERVER_RECEIPT_MISSING');
assert.equal(r.panel.recent_event,d5Cycle3.terminal);
assert.equal(r.d2_context_authority,'CYCLE2_IMMUTABLE_TARGET_PC_RECEIPT');
assert.equal(r.d2_cycle3_guard_used_as,'FRESHNESS_GUARD_EVIDENCE_ONLY_NOT_CURRENT_BINDING_AUTHORITY');
console.log('PASS_20_ASSERTIONS');
