'use strict';
const fs=require('node:fs');const crypto=require('node:crypto');const {infer}=require('./A4_COMPONENT_NAVIGATION_INFERENCE_V1.cjs');
function fakePtr(kind,id){const inline_payload={kind,id,fixture:true};const sha256=crypto.createHash('sha256').update(JSON.stringify(Object.fromEntries(Object.keys(inline_payload).sort().map(k=>[k,inline_payload[k]])))).digest('hex');return{kind,sha256,inline_payload};}
const f=JSON.parse(fs.readFileSync(process.argv[2]||'fixture_10_site_profiles_v1.json','utf8'));
function run(){return f.profiles.map(p=>infer({...p,evidence:{screenshot:fakePtr('SCREENSHOT',p.site_profile_id),dom:fakePtr('DOM',p.site_profile_id),computed_style:fakePtr('COMPUTED_STYLE',p.site_profile_id),component_tree:fakePtr('COMPONENT_TREE',p.site_profile_id)},locator_candidates:f.shared_locator_candidates,components:[{role:'RESULT_REGION',observed:true,locator_candidates:f.shared_locator_candidates,evidence_pointer:`fixture:${p.site_profile_id}:component`}],forms:p.signals.includes('write_form')?[{role:p.signals.includes('create_action')?'CREATE':'EDIT',observed:true,dynamic:!!p.runtime.dynamic_form,fields:[{role:'title',input_type:'text',observed:true,locator_candidates:[f.shared_locator_candidates[0]]}]}]:[] }));}
const a=run(),b=run(),A=JSON.stringify(a),B=JSON.stringify(b);if(A!==B)throw new Error('NON_DETERMINISTIC_REPLAY');
const modes=new Set();for(const x of a)for(const [k,v] of Object.entries(x.interaction_modes))if(v.value!==false&&v.value!=='UNKNOWN')modes.add(k+':'+v.value);
const out={status:'PASS',profile_count:a.length,archetypes:[...new Set(a.map(x=>x.page_identity.archetype))].sort(),interaction_modes:[...modes].sort(),all_evidence_exact_pointer_pass:a.every(x=>x.evidence_validation.pass),all_structure_digest_present:a.every(x=>/^[0-9a-f]{64}$/.test(x.structure_digest)),deterministic:true,replay_sha256:crypto.createHash('sha256').update(A).digest('hex'),locator_drift_signature_count:new Set(a.flatMap(x=>x.locator_candidates.map(l=>l.drift_signature))).size,target_values_guessed:false};
process.stdout.write(JSON.stringify(out,null,2)+'\n');
