'use strict';
const crypto=require('node:crypto');
const stable=v=>Array.isArray(v)?v.map(stable):v&&typeof v==='object'?Object.keys(v).sort().reduce((a,k)=>(a[k]=stable(v[k]),a),{}):v;
const sha=v=>crypto.createHash('sha256').update(JSON.stringify(stable(v))).digest('hex');
const FINAL_ACTIONS=new Set(['submitCreate','submitUpdate','delete','expire']);
function assertEvidence(mapping){for(const [k,v] of Object.entries(mapping.site_form_mapping||{})){if(!v.form_field||!v.evidence)throw new Error(`FAIL_CLOSED_EVIDENCE:${k}`)}}
function toForm(canonical,mapping){assertEvidence(mapping);const out={};for(const [field,rule] of Object.entries(mapping.site_form_mapping)){if(!(field in canonical))continue;let value=canonical[field];if(rule.transform==='KRW_TEXT_TO_NUMBER')value=Number(String(value).replace(/[^0-9]/g,''));if(rule.transform==='TRIM')value=String(value).trim();out[rule.form_field]=value;}return out}
function fromForm(site,mapping){const out={};for(const [siteField,canonical] of Object.entries(mapping.reverse_mapping||{})){if(siteField in site)out[canonical]=site[siteField]}return out}
function compileRecipe({mode,command_id,canonical,mapping}){if(!['READ','WRITE','MY_LISTING','EDIT'].includes(mode))throw new Error('BAD_MODE');const page_id=`fixture-${mode.toLowerCase()}`;const base={schema_version:'EXTRACTION_RECIPE_V1',recipe_version:'1.0.0-cycle4',adapter_version:'1.0.0-cycle4',mode,command_id,page_id,steps:[]};if(mode==='READ'||mode==='MY_LISTING'){base.steps=[{step_id:'s01',action_id:`${command_id}:a01`,type:'Navigate',page_id},{step_id:'s02',action_id:`${command_id}:a02`,type:'Extract',page_id}];}else{const form=toForm(canonical,mapping);base.form_preview=form;base.steps=[{step_id:'s01',action_id:`${command_id}:a01`,type:'Navigate',page_id},{step_id:'s02',action_id:`${command_id}:a02`,type:'Wait',page_id},{step_id:'s03',action_id:`${command_id}:a03`,type:'AutofillPreview',page_id,payload:form},{step_id:'s04',action_id:`${command_id}:a04`,type:'UserConfirmGate',page_id,status:'USER_CONFIRM_REQUIRED'}];}return base}
function execute(recipe,{checkpoint=null,failAtStep=null}={}){let cp=checkpoint||{schema_version:'ADAPTER_CHECKPOINT_RESUME_V1',checkpoint_id:`cp-${recipe.command_id}`,command_id:recipe.command_id,recipe_version:recipe.recipe_version,adapter_version:recipe.adapter_version,last_completed_step:null,resume_from_step:0,completed_idempotency_keys:[],status:'RUNNING'};let executed=0,skipped=0;for(let i=cp.resume_from_step;i<recipe.steps.length;i++){const s=recipe.steps[i],key=sha({command_id:recipe.command_id,action_id:s.action_id,page_id:s.page_id,step_id:s.step_id,recipe_version:recipe.recipe_version,adapter_version:recipe.adapter_version});if(cp.completed_idempotency_keys.includes(key)){skipped++;continue;}if(failAtStep===s.step_id){cp.status='FAILED';cp.failed_step=s.step_id;cp.resume_from_step=i;cp.checkpoint_sha256=sha({...cp,checkpoint_sha256:undefined});return{checkpoint:cp,receipt:{status:'FAILED',failed_step:s.step_id,executed_step_count:executed,resume_from_step:i,last_completed_step:cp.last_completed_step}}}if(FINAL_ACTIONS.has(s.type))throw new Error('FINAL_ACTION_AUTOEXEC_FORBIDDEN');cp.completed_idempotency_keys.push(key);cp.last_completed_step=s.step_id;cp.resume_from_step=i+1;executed++;}cp.status='COMPLETED';cp.checkpoint_sha256=sha({...cp,checkpoint_sha256:undefined});return{checkpoint:cp,receipt:{status:'PASS',executed_step_count:executed,skipped_completed_step_count:skipped,resume_from_step:cp.resume_from_step,last_completed_step:cp.last_completed_step}}}
function prepare({mode,command_id,canonical,site_listing,mapping}){const recipe=compileRecipe({mode,command_id,canonical,mapping});const result={recipe};if(mode==='MY_LISTING')result.canonical_candidate=fromForm(site_listing,mapping);if(mode==='READ')result.canonical_candidate=canonical;return result}
module.exports={toForm,fromForm,compileRecipe,execute,prepare,sha};
