'use strict';
const net=require('node:net');const fs=require('node:fs');const path=require('node:path');
const {BrowserCdpConnection,CdpObserverModuleV1,selectPageTarget}=require('../ai001-prebuild/CDP_OBSERVER_MODULE_V1.cjs');
const {STATE,WorkerCompletionObserverV2,makeCdpRuntimeAdapter}=require('./WORKER_COMPLETION_OBSERVER_V2.cjs');
const BROWSER_AGENT=Object.freeze({host:'127.0.0.1',port:32100});const CDP_URL='http://127.0.0.1:9222';
function parse(argv){const o={timeoutMs:180000,pollMs:500,urlContains:'chatgpt.com',workerId:'D-4',receipt:null};for(let i=2;i<argv.length;i++){const a=argv[i];if(a==='--timeout-ms')o.timeoutMs=Number(argv[++i]);else if(a==='--poll-ms')o.pollMs=Number(argv[++i]);else if(a==='--url-contains')o.urlContains=String(argv[++i]);else if(a==='--worker-id')o.workerId=String(argv[++i]);else if(a==='--receipt')o.receipt=String(argv[++i]);else throw new Error(`UNKNOWN_ARG:${a}`);}if(!o.receipt)throw new Error('RECEIPT_REQUIRED');if(!Number.isFinite(o.timeoutMs)||o.timeoutMs<5000)throw new Error('INVALID_TIMEOUT');if(!Number.isFinite(o.pollMs)||o.pollMs<100)throw new Error('INVALID_POLL');return o;}
const delay=ms=>new Promise(r=>setTimeout(r,ms));
function tcpProbe(host,port,timeoutMs=1500){return new Promise((resolve,reject)=>{const s=net.createConnection({host,port});const timer=setTimeout(()=>{s.destroy();reject(new Error('BROWSER_AGENT_TCP_TIMEOUT'));},timeoutMs);s.once('connect',()=>{clearTimeout(timer);s.destroy();resolve(true);});s.once('error',e=>{clearTimeout(timer);reject(new Error(`BROWSER_AGENT_UNREACHABLE:${e.code||e.message}`));});});}
function writeReceipt(file,data){fs.mkdirSync(path.dirname(path.resolve(file)),{recursive:true});fs.writeFileSync(file,JSON.stringify(data,null,2)+'\n');}
function baseReceipt(){return{schema_version:'D4_CHROME_REPLY_COMPLETION_LIVE_RECEIPT_V1',cycle_id:'D1-CONTEXT-AWARE-MESSAGE-LOOP-CYCLE1-20260807-001',role:'D-4_CHROME_WORKER_STATE_OBSERVER_OWNER',browser_agent_endpoint:'127.0.0.1:32100',cdp_endpoint:'127.0.0.1:9222',cdp_localhost_only:true,target_origin_required:'chatgpt.com',started_at:new Date().toISOString(),events:[],live_pass_claimed:false};}
async function run(opts=parse(process.argv)){const receipt=baseReceipt();let connection=null;try{if(BROWSER_AGENT.host!=='127.0.0.1'||CDP_URL!=='http://127.0.0.1:9222')throw new Error('LOCALHOST_AUTHORITY_VIOLATION');await tcpProbe(BROWSER_AGENT.host,BROWSER_AGENT.port);receipt.browser_agent_reachable=true;connection=new BrowserCdpConnection({browserUrl:CDP_URL});await connection.connect();receipt.cdp_connected=true;const targets=await CdpObserverModuleV1.discoverPageTargets(connection);const target=selectPageTarget(targets,{url_contains:opts.urlContains});if(!String(target.url||'').includes(opts.urlContains))throw new Error('CHATGPT_PAGE_TARGET_NOT_FOUND');receipt.page={target_id:target.targetId,title:String(target.title||'').slice(0,160),origin_match:true};const attached=await connection.send('Target.attachToTarget',{targetId:target.targetId,flatten:true});await connection.send('Runtime.enable',{},attached.sessionId);const adapter=makeCdpRuntimeAdapter(connection,attached.sessionId);const registry={schema_version:'WORKER_PAGE_REGISTRY_V1',entries:[{worker_id:opts.workerId,page_id:target.targetId}]};const observer=new WorkerCompletionObserverV2({registry,stableMs:1800,minStableObservations:2});observer.on('state',event=>receipt.events.push(event));await observer.install(adapter);const baseline=await observer.readSnapshot(adapter);observer.captureBaseline(opts.workerId,baseline);observer.noteDispatch(opts.workerId,'D4-LIVE-OBSERVE');receipt.baseline={assistant_message_count:Number(baseline?.assistant_message_count||0),captured:true};const deadline=Date.now()+opts.timeoutMs;let streamingObserved=false,terminal=null;while(Date.now()<deadline){const event=await observer.readAndObserve(opts.workerId,adapter);if(event.reason_codes.includes('ASSISTANT_REPLY_STREAMING')||event.reason_codes.includes('NEW_ASSISTANT_REPLY_MUTATED'))streamingObserved=true;if(event.state===STATE.ERROR||event.state===STATE.COMPLETED){terminal=event;break;}await delay(opts.pollMs);}receipt.streaming_intermediate_observed=streamingObserved;receipt.terminal_state=terminal?.state||null;if(!terminal)throw new Error('LIVE_REPLY_COMPLETION_TIMEOUT');if(terminal.state===STATE.ERROR)throw new Error('EXPLICIT_ERROR_VISIBLE');if(!streamingObserved)throw new Error('STREAMING_INTERMEDIATE_NOT_OBSERVED_LIVE');receipt.status='PASS';receipt.completed_at=new Date().toISOString();receipt.live_pass_claimed=true;receipt.terminal='CHROME_REPLY_COMPLETION_LIVE_PASS';writeReceipt(opts.receipt,receipt);process.stdout.write('CHROME_REPLY_COMPLETION_LIVE_PASS\n');return receipt;}catch(error){receipt.status='BLOCKED';receipt.blocker=error.message;receipt.completed_at=new Date().toISOString();receipt.terminal='CHROME_REPLY_COMPLETION_LIVE_BLOCKED';writeReceipt(opts.receipt,receipt);process.stderr.write(`${receipt.terminal}:${receipt.blocker}\n`);process.exitCode=2;return receipt;}finally{try{await connection?.close();}catch{}}}
if(require.main===module)run();module.exports={run,tcpProbe,BROWSER_AGENT,CDP_URL};
