'use strict';
const assert=require('node:assert/strict');
const {STATE,WorkerCompletionObserverV2,buildInjectedObserverScript}=require('./WORKER_COMPLETION_OBSERVER_V2.cjs');
let tick=1000;const clock=()=>tick;
const registry={schema_version:'WORKER_PAGE_REGISTRY_V1',entries:[{worker_id:'D-4',page_id:'chatgpt-page-d4'}]};
const baseline={selector_found:true,assistant_items:[{key:'turn-old',text:'이전 답장'}],assistant_message_count:1,generating_ui_active:false,explicit_error_visible:false,dom_stable_ms:5000,now_ms:1000};
function snap({items=[{key:'turn-old',text:'이전 답장'}],generating=false,error=false,errorText='',stable=0,now=tick}={}){return{selector_found:true,assistant_items:items,assistant_message_count:items.length,generating_ui_active:generating,explicit_error_visible:error,explicit_error_text:errorText,dom_stable_ms:stable,now_ms:now};}
function run(){let assertions=0;const eq=(a,b,m)=>{assertions++;assert.equal(a,b,m);},ok=(v,m)=>{assertions++;assert.ok(v,m);};const observer=new WorkerCompletionObserverV2({registry,stableMs:1500,minStableObservations:2,clock});const states=[];observer.on('state',e=>states.push(e.state));observer.captureBaseline('D-4',baseline);eq(observer.noteDispatch('D-4','CMD-D4-001').state,STATE.WORKING,'MESSAGE_VISIBLE -> WORKING');tick=1200;eq(observer.observeSnapshot('D-4',snap({stable:2000,now:tick})).state,STATE.WORKING,'old reply cannot complete');tick=2000;eq(observer.observeSnapshot('D-4',snap({items:[{key:'turn-old',text:'이전 답장'},{key:'turn-new',text:'답장 생성'}],generating:true,stable:100,now:tick})).state,STATE.WORKING,'streaming -> WORKING');tick=2500;eq(observer.observeSnapshot('D-4',snap({items:[{key:'turn-old',text:'이전 답장'},{key:'turn-new',text:'답장 생성 중 더 길어짐'}],stable:200,now:tick})).state,STATE.WORKING,'mutating reply not complete');tick=4200;eq(observer.observeSnapshot('D-4',snap({items:[{key:'turn-old',text:'이전 답장'},{key:'turn-new',text:'최종 답장'}],stable:1700,now:tick})).state,STATE.WORKING,'first stable observation pending');tick=5900;const complete=observer.observeSnapshot('D-4',snap({items:[{key:'turn-old',text:'이전 답장'},{key:'turn-new',text:'최종 답장'}],stable:3400,now:tick}));eq(complete.state,STATE.COMPLETED,'NEW_ASSISTANT_REPLY_FINISHED -> COMPLETED');ok(complete.reason_codes.includes('NEW_ASSISTANT_REPLY_FINISHED'),'completion reason');const errObserver=new WorkerCompletionObserverV2({registry,stableMs:1500,clock});errObserver.captureBaseline('D-4',baseline);errObserver.noteDispatch('D-4','CMD-D4-ERR');tick=7000;const error=errObserver.observeSnapshot('D-4',snap({error:true,errorText:'Something went wrong',stable:1000,now:tick}));eq(error.state,STATE.ERROR,'EXPLICIT_ERROR_VISIBLE -> ERROR');ok(error.error_digest_sha256?.length===64,'error raw text not persisted');const noBaseline=new WorkerCompletionObserverV2({registry,clock});noBaseline.noteDispatch('D-4','CMD-NOBASE');tick=8000;eq(noBaseline.observeSnapshot('D-4',snap({items:[{key:'new',text:'완료처럼 보이는 답장'}],stable:9000,now:tick})).state,STATE.WORKING,'baseline missing fails safe');const script=buildInjectedObserverScript(undefined,1500);ok(script.includes('__YOLLA_WORKER_COMPLETION_OBSERVER_V2__'),'V2 injection');ok(script.includes('data-message-streaming'),'streaming signal');ok(!script.includes('LIKELY_COMPLETE'),'LIKELY_COMPLETE removed');for(const s of states)ok(['WORKING','COMPLETED','ERROR'].includes(s),`allowed state ${s}`);ok(!JSON.stringify(states).match(/LIKELY_COMPLETE|UNKNOWN|A_MODE|E_MODE/),'legacy states absent');const result={status:'PASS',assertion_count:assertions,streaming_intermediate_not_completed:true,new_reply_stability_gate:true,explicit_error_gate:true,baseline_required:true,terminal:'D4_CHROME_REPLY_COMPLETION_OBSERVER_V2_OFFLINE_READY'};process.stdout.write(JSON.stringify(result,null,2)+'\n');return result;}
if(require.main===module)run();module.exports={run};
