'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { RepeatCommandRuntime } = require('../repeat_command_runtime.cjs');

let now = 1_000_000;
const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'repeat-runtime-'));
const statePath = path.join(dir, 'state.json');
const sent = [];
const runtime = new RepeatCommandRuntime({ statePath, now: () => now, emit: (r) => sent.push(r) });
const prompt = '한글 Byte 보존\nCOMMAND_ID=C-W4-001';
const created = runtime.create({ command_id: 'C-W4-001', role: 'AUTOMATION-C-W4', prompt, targets: [{group_id:'C',slot_id:'4'}], trigger_mode:'EVERY_X_MINUTES', interval_minutes: 1 });
assert.equal(created.prompt, prompt);
assert.equal(created.prompt_byte_length, Buffer.byteLength(prompt, 'utf8'));
assert.throws(() => runtime.create({ command_id:'C-W4-001', role:'X', prompt:'x', targets:[{group_id:'C',slot_id:'4'}], trigger_mode:'AFTER_COMPLETION' }), /ACTIVE_COMMAND_DUPLICATE/);
const first = runtime.tick();
assert.equal(first.length, 1);
assert.equal(runtime.tick().length, 0, 'active dispatch must not duplicate while awaiting completion');
assert.deepEqual(runtime.complete({ role:'AUTOMATION-C-W5', command_id:'C-W4-001', dispatch_id:first[0].dispatch_id }), {accepted:false,reason:'ROLE_MISMATCH'});
assert.deepEqual(runtime.complete({ role:'AUTOMATION-C-W4', command_id:'C-W4-001', dispatch_id:'wrong' }), {accepted:false,reason:'DISPATCH_MISMATCH'});
assert.equal(runtime.complete({ role:'AUTOMATION-C-W4', command_id:'C-W4-001', dispatch_id:first[0].dispatch_id }).accepted, true);
now += 60_000;
assert.equal(runtime.tick().length, 1);
runtime.pause('C-W4-001');
now += 60_000;
assert.equal(runtime.tick().length, 0);
runtime.resume('C-W4-001');
const restored = new RepeatCommandRuntime({ statePath, now: () => now, emit: (r) => sent.push(r) });
assert.equal(restored.get('C-W4-001').dispatch_count, 2);
assert.equal(restored.get('C-W4-001').prompt, prompt);
const active = restored.get('C-W4-001');
assert.equal(restored.complete({ role:active.role, command_id:active.command_id, dispatch_id:active.last_dispatch_id, status:'END' }).accepted, true);
now += 60_000;
assert.equal(restored.tick().length, 0);

const after = restored.create({ command_id:'C-W4-002', role:'AUTOMATION-C-W4', prompt:'repeat after completion', targets:[{group_id:'C',slot_id:'4'},{group_id:'C',slot_id:'5'}], trigger_mode:'AFTER_COMPLETION' });
const a1 = restored.tick()[0];
assert.equal(restored.triggerAfterCompletion(after.command_id), null);
assert.equal(restored.complete({role:after.role,command_id:after.command_id,dispatch_id:a1.dispatch_id}).accepted,true);
const a2 = restored.triggerAfterCompletion(after.command_id);
assert.equal(a2.dispatch_id, 'C-W4-002:2');
assert.equal(restored.delete('C-W4-002'), true);
assert.equal(restored.get('C-W4-002'), null);
const snap = restored.snapshot();
assert.ok(snap.work_control_log.some((e) => e.event === 'AUTO_STOP_END'));
assert.ok(snap.receipts.every((r) => r.prompt_sha256 && r.prompt_byte_length > 0));
assert.equal(sent.length, 4);
console.log(JSON.stringify({status:'PASS',tests:18,dispatch_receipts:sent.length,work_control_log_entries:snap.work_control_log.length}));
