'use strict';
const assert=require('node:assert/strict'); const fs=require('node:fs'); const os=require('node:os'); const path=require('node:path'); const {RepeatCommandRuntime,RepeatCommandBridgeAdapter}=require('../repeat_command_runtime.cjs');
let now=1000000; const dir=fs.mkdtempSync(path.join(os.tmpdir(),'w4-wave3-')); const statePath=path.join(dir,'state.json'); const popup=[]; const rt=new RepeatCommandRuntime({statePath,now:()=>now});
const c=rt.create({command_id:'C6W-W3-W4-REPEAT-BRIDGE-ARBITRATION',role:'AUTOMATION-C-W4',prompt:'repeat bridge',targets:[{group_id:'C',slot_id:'4'},{group_id:'C',slot_id:'5'},{group_id:'C',slot_id:'6'}],trigger_mode:'AFTER_COMPLETION'});
const bridge=new RepeatCommandBridgeAdapter({runtime:rt,dispatchToPopup:r=>popup.push(r)});
let records=bridge.flushRuntime(); assert.equal(records.length,3); assert.equal(new Set(records.map(x=>x.dispatch_id)).size,3); assert.equal(popup.length,3); assert.ok(popup.every(x=>x.mode==='REPEAT_COMMAND'));
const first=rt.get(c.command_id); const d4=first.targets.find(x=>x.slot_id==='4').last_dispatch_id,d5=first.targets.find(x=>x.slot_id==='5').last_dispatch_id,d6=first.targets.find(x=>x.slot_id==='6').last_dispatch_id;
assert.deepEqual(bridge.acceptRepeatResult({schema_version:'W2_REPEAT_RESULT_V1',role:c.role,command_id:c.command_id,dispatch_id:'bad',status:'REPORTED'}),{accepted:false,reason:'UNKNOWN_DISPATCH'});
assert.deepEqual(bridge.acceptRepeatResult({schema_version:'W2_REPEAT_RESULT_V1',role:'AUTOMATION-C-W5',command_id:c.command_id,dispatch_id:d4,status:'REPORTED'}),{accepted:false,reason:'CORRELATION_MISMATCH'});
assert.equal(bridge.acceptRepeatResult({schema_version:'W2_REPEAT_RESULT_V1',role:c.role,command_id:c.command_id,dispatch_id:d4,status:'REPORTED'}).accepted,true);
assert.equal(bridge.acceptRepeatResult({schema_version:'W2_REPEAT_RESULT_V1',role:c.role,command_id:c.command_id,dispatch_id:d5,status:'END'}).target_status,'END');
assert.equal(bridge.snapshot().repeat_queue.find(x=>x.dispatch_id===d6).state,'ACTIVE');
assert.equal(bridge.enqueueCMode({dispatch_id:'C-MODE-1',role:c.role,slot_id:'4'}).accepted,true); assert.deepEqual(bridge.enqueueCMode({dispatch_id:'C-MODE-1'}),{accepted:false,reason:'C_MODE_DUPLICATE'});
assert.equal(bridge.snapshot().c_mode_queue.length,1); assert.equal(bridge.snapshot().repeat_queue.length,3);
now+=5000; const resend=rt.triggerAfterCompletion(c.command_id); assert.equal(resend.length,1); assert.equal(resend[0].slot_id,'4'); bridge.dispatch(resend[0]);
rt.pause(c.command_id); assert.equal(bridge.flushRuntime().length,0); assert.equal(bridge.snapshot().c_mode_queue.length,1); rt.resume(c.command_id);
const restored=new RepeatCommandRuntime({statePath,now:()=>now}); const restoredBridge=new RepeatCommandBridgeAdapter({runtime:restored,cModeQueue:bridge.snapshot().c_mode_queue});
const rs=restored.get(c.command_id); assert.equal(rs.targets.find(x=>x.slot_id==='5').status,'END'); assert.equal(rs.targets.find(x=>x.slot_id==='6').awaiting_completion,true); assert.equal(restoredBridge.snapshot().c_mode_queue.length,1);
const r4=rs.targets.find(x=>x.slot_id==='4').last_dispatch_id,r6=rs.targets.find(x=>x.slot_id==='6').last_dispatch_id; restoredBridge.dispatch({dispatch_id:r4,command_id:c.command_id,role:c.role,group_id:'C',slot_id:'4'}); restoredBridge.dispatch({dispatch_id:r6,command_id:c.command_id,role:c.role,group_id:'C',slot_id:'6'});
assert.equal(restoredBridge.acceptRepeatResult({schema_version:'W2_REPEAT_RESULT_V1',role:c.role,command_id:c.command_id,dispatch_id:r6,status:'REPORTED'}).accepted,true);
assert.equal(restoredBridge.acceptRepeatResult({schema_version:'W2_REPEAT_RESULT_V1',role:c.role,command_id:c.command_id,dispatch_id:r4,status:'END'}).accepted,true);
const next6=restored.triggerAfterCompletion(c.command_id); assert.equal(next6.length,1); assert.equal(next6[0].slot_id,'6'); restoredBridge.dispatch(next6[0]);
assert.equal(restoredBridge.snapshot().repeat_queue.filter(x=>x.state==='ACTIVE').length,1); assert.equal(restoredBridge.snapshot().c_mode_queue.length,1);
assert.throws(()=>restoredBridge.parseRepeatResult({schema_version:'BAD'}),/INVALID_REPEAT_RESULT_SCHEMA/);
console.log(JSON.stringify({status:'PASS',assertions:31,popup_dispatches:popup.length,repeat_queue:restoredBridge.snapshot().repeat_queue.length,c_mode_queue:restoredBridge.snapshot().c_mode_queue.length}));
