'use strict';
const assert=require('node:assert/strict');
const {ActualRepeatReleaseAdapter}=require('../actual_repeat_release_adapter.cjs');
const {CRepeatNamespaceAdapter}=require('../c_repeat_namespace_adapter.cjs');
const {ActualCandidateBridgeBinding}=require('../actual_candidate_bridge_binding.cjs');
let now=0,counter=0;const targets=Array.from({length:6},(_,i)=>({group_id:'C',slot_id:String(i+1),status:'ACTIVE',awaiting_completion:false,last_dispatch_id:null}));
class Runtime{tick(){const out=[];for(const t of targets){if(t.status==='ACTIVE'&&!t.awaiting_completion){counter++;t.awaiting_completion=true;t.last_dispatch_id=`R:C:${t.slot_id}:${counter}`;out.push({dispatch_id:t.last_dispatch_id,command_id:'REPEAT',role:'AUTOMATION-C-W4',group_id:'C',slot_id:t.slot_id});}}return out;}complete(p){const t=targets.find(x=>x.last_dispatch_id===p.dispatch_id&&x.awaiting_completion);if(!t)return{accepted:false};t.awaiting_completion=false;if(p.status==='END')t.status='END';return{accepted:true};}list(){return[{command_id:'REPEAT',role:'AUTOMATION-C-W4',targets}];}}
const runtime=new Runtime(),popup=[];let release=new ActualRepeatReleaseAdapter({runtime,popupBridge:{send:x=>popup.push(x)},now:()=>now});let ns=new CRepeatNamespaceAdapter({repeatRuntime:runtime,now:()=>now});let bridge=new ActualCandidateBridgeBinding({releaseAdapter:release,namespaceAdapter:ns});
bridge.registerRegistry({registry_id:'old',result_key:'old'});bridge.registerRegistry({registry_id:'current',result_key:'519386645000'});assert.equal(bridge.acceptCResult({registry_id:'old',result_key:'old'}).accepted,false);
const counters={duplicate:0,cross_cancel:0,end_redispatch:0,receipt_loss:0,queue_growth:0};
for(let cycle=1;cycle<=1200;cycle++){now++;const receipts=bridge.dispatchDue(now);if(cycle===600){const s=bridge.snapshot();release=new ActualRepeatReleaseAdapter({runtime,popupBridge:{send:x=>popup.push(x)},now:()=>now});release.state=s.release;ns=new CRepeatNamespaceAdapter({repeatRuntime:runtime,now:()=>now});ns.state=s.namespace;bridge=new ActualCandidateBridgeBinding({releaseAdapter:release,namespaceAdapter:ns});}for(const r of [...receipts].reverse()){const status=cycle===1000&&r.slot_id==='6'?'END':'REPORTED';assert.equal(bridge.acceptRepeatResult({schema_version:'W2_REPEAT_RESULT_V1',role:r.role,command_id:r.command_id,dispatch_id:r.dispatch_id,status}).accepted,true);}if(cycle%100===0)bridge.enqueueC({dispatch_id:`C-${cycle}`,registry_id:'current',result_key:'519386645000'});const s=bridge.snapshot();if(new Set(s.release.receipts.map(x=>x.dispatch_id)).size!==s.release.receipts.length)counters.duplicate++;if(s.release.c_mode_queue.length!==s.namespace.c_queue.length)counters.cross_cancel++;if(cycle>1000&&receipts.some(x=>x.slot_id==='6'))counters.end_redispatch++;if(s.release.receipts.length!==s.namespace.repeat_receipts.length)counters.receipt_loss++;if(Object.keys(s.release.active).length!==Object.keys(s.namespace.repeat_active).length)counters.queue_growth++;}
assert.deepEqual(counters,{duplicate:0,cross_cancel:0,end_redispatch:0,receipt_loss:0,queue_growth:0});console.log(JSON.stringify({status:'PASS',cycles:1200,slots:6,repeat_receipts:bridge.snapshot().release.receipts.length,c_items:bridge.snapshot().namespace.c_queue.length,restart_cycle:600,counters}));
