'use strict';
const assert = require('assert');
const { parsePanelReports, detectSchema, validateReport, correlateReports } = require('../report_parser/index.cjs');
const W='V1-C-MODE-6W-WAVE-002', C='C6W-W2-W2-DUAL-REPORT-SCHEMA';
let n=0; const t=(name,fn)=>{fn();n++;};
t('post id',()=>assert.equal(parsePanelReports(`PANEL | ROLE=R | WAVE=${W} | COMMAND_ID=${C} | STATUS=END`,{id:7})[0].post_id,7));
t('c schema',()=>assert.equal(detectSchema({WAVE:W}),'C_RESULT'));
t('repeat schema',()=>assert.equal(detectSchema({DISPATCH_ID:'D'}),'REPEAT_RESULT'));
t('mixed',()=>assert(validateReport({fields:{ROLE:'R',WAVE:W,DISPATCH_ID:'D',COMMAND_ID:C,STATUS:'END'}},{},{schema:'C_RESULT'}).reasons.includes('MIXED_SCHEMA')));
t('missing wave',()=>assert(validateReport({fields:{ROLE:'R',COMMAND_ID:C,STATUS:'END'}},{},{schema:'C_RESULT'}).reasons.includes('MISSING_WAVE')));
t('missing dispatch',()=>assert(validateReport({fields:{ROLE:'R',COMMAND_ID:C,STATUS:'END'}},{},{schema:'REPEAT_RESULT'}).reasons.includes('MISSING_DISPATCH_ID')));
t('wrong schema',()=>assert(validateReport({fields:{ROLE:'R',DISPATCH_ID:'D',COMMAND_ID:C,STATUS:'END'}},{},{schema:'C_RESULT'}).reasons.includes('SCHEMA_MISMATCH')));
t('role mismatch',()=>assert(validateReport({fields:{ROLE:'X',WAVE:W,COMMAND_ID:C,STATUS:'END'}},{role:'R',wave:W,command_id:C},{schema:'C_RESULT'}).reasons.includes('ROLE_MISMATCH')));
t('wave mismatch',()=>assert(validateReport({fields:{ROLE:'R',WAVE:'OLD',COMMAND_ID:C,STATUS:'END'}},{role:'R',wave:W,command_id:C},{schema:'C_RESULT'}).reasons.includes('WAVE_MISMATCH')));
t('command mismatch',()=>assert(validateReport({fields:{ROLE:'R',WAVE:W,COMMAND_ID:'OLD',STATUS:'END'}},{role:'R',wave:W,command_id:C},{schema:'C_RESULT'}).reasons.includes('COMMAND_ID_MISMATCH')));
t('stale',()=>assert.equal(correlateReports([{id:1,created_at:'2026-08-05T08:00:00Z',body:`PANEL | ROLE=R | WAVE=${W} | COMMAND_ID=${C} | STATUS=END`}],{role:'R',wave:W,command_id:C},{schema:'C_RESULT',not_before:'2026-08-05T09:00:00Z'}).accepted.length,0));
t('duplicate latest',()=>{const r=correlateReports([{id:1,created_at:'2026-08-05T09:00:00Z',body:`PANEL | ROLE=R | WAVE=${W} | COMMAND_ID=${C} | STATUS=REPORTED`},{id:2,created_at:'2026-08-05T09:01:00Z',body:`PANEL | ROLE=R | WAVE=${W} | COMMAND_ID=${C} | STATUS=END`}],{role:'R',wave:W,command_id:C},{schema:'C_RESULT'}); assert.equal(r.accepted[0].post_id,2)});
t('order reversal',()=>{const r=correlateReports([{id:2,created_at:'2026-08-05T09:01:00Z',body:`PANEL | ROLE=R | WAVE=${W} | COMMAND_ID=${C} | STATUS=END`},{id:1,created_at:'2026-08-05T09:00:00Z',body:`PANEL | ROLE=R | WAVE=${W} | COMMAND_ID=${C} | STATUS=REPORTED`}],{role:'R',wave:W,command_id:C},{schema:'C_RESULT'}); assert.equal(r.accepted[0].post_id,2)});
t('missing roles',()=>assert.deepEqual(correlateReports([],{wave:W,command_id:C},{schema:'C_RESULT',expected_roles:['R1','R2']}).missing_roles,['R1','R2']));
t('repeat accepted',()=>assert.equal(correlateReports([{id:9,created_at:'2026-08-05T09:00:00Z',body:`PANEL | ROLE=R | COMMAND_ID=${C} | DISPATCH_ID=D1 | STATUS=END`}],{role:'R',command_id:C,dispatch_id:'D1'},{schema:'REPEAT_RESULT'}).accepted.length,1));
t('legacy read-only rejected for wave2',()=>assert.equal(correlateReports([{id:3,created_at:'2026-08-05T09:00:00Z',body:'PANEL | ROLE=AUTOMATION-C-W3 | STATUS=END'}],{role:'AUTOMATION-C-W3',wave:W,command_id:C},{schema:'C_RESULT'}).accepted.length,0));
console.log(`PASS_${n}_OF_${n}`);
