'use strict';
const assert=require('node:assert/strict'); const fs=require('node:fs'); const os=require('node:os'); const path=require('node:path'); const {RepeatCommandRuntime}=require('../repeat_command_runtime.cjs');
let now=1000000; const dir=fs.mkdtempSync(path.join(os.tmpdir(),'w4-wave2-')); const statePath=path.join(dir,'state.json'); const sent=[]; const rt=new RepeatCommandRuntime({statePath,now:()=>now,emit:r=>sent.push(r)});
const prompt='한글 Byte 보존\nCOMMAND_ID=C6W-W2-W4-PER-TARGET-REPEAT';
const c=rt.create({command_id:'C6W-W2-W4-PER-TARGET-REPEAT',role:'AUTOMATION-C-W4',prompt,targets:[{group_id:'C',slot_id:'4'},{group_id:'C',slot_id:'5'},{group_id:'C',slot_id:'6'}],trigger_mode:'AFTER_COMPLETION'});
assert.equal(c.targets.length,3); assert.equal(c.prompt_byte_length,Buffer.byteLength(prompt));
const first=rt.tick(); assert.equal(first.length,3); assert.equal(new Set(first.map(x=>x.dispatch_id)).size,3); assert.equal(rt.tick().length,0);
const s4=first.find(x=>x.slot_id==='4'),s5=first.find(x=>x.slot_id==='5'),s6=first.find(x=>x.slot_id==='6');
assert.deepEqual(rt.complete({role:'AUTOMATION-C-W5',command_id:c.command_id,dispatch_id:s4.dispatch_id}),{accepted:false,reason:'ROLE_MISMATCH'});
assert.equal(rt.complete({role:c.role,command_id:c.command_id,dispatch_id:s4.dispatch_id,status:'REPORTED'}).accepted,true);
now+=5000; let next=rt.triggerAfterCompletion(c.command_id); assert.equal(next.length,1); assert.equal(next[0].slot_id,'4');
assert.equal(rt.complete({role:c.role,command_id:c.command_id,dispatch_id:s5.dispatch_id,status:'END'}).target_status,'END');
now+=7000; assert.equal(rt.complete({role:c.role,command_id:c.command_id,dispatch_id:s6.dispatch_id,status:'REPORTED'}).accepted,true);
next=rt.triggerAfterCompletion(c.command_id); assert.deepEqual(next.map(x=>x.slot_id).sort(),['6']);
const restored=new RepeatCommandRuntime({statePath,now:()=>now,emit:r=>sent.push(r)}); const rs=restored.get(c.command_id);
assert.equal(rs.targets.find(x=>x.slot_id==='4').dispatch_count,2); assert.equal(rs.targets.find(x=>x.slot_id==='5').status,'END'); assert.equal(rs.targets.find(x=>x.slot_id==='6').dispatch_count,2);
assert.equal(restored.triggerAfterCompletion(c.command_id).length,0);
const r4=rs.targets.find(x=>x.slot_id==='4').last_dispatch_id; const r6=rs.targets.find(x=>x.slot_id==='6').last_dispatch_id;
assert.equal(restored.complete({role:c.role,command_id:c.command_id,dispatch_id:r4,status:'END'}).accepted,true);
assert.equal(restored.complete({role:c.role,command_id:c.command_id,dispatch_id:r6,status:'END'}).command_status,'END');
assert.equal(restored.triggerAfterCompletion(c.command_id).length,0);
restored.create({command_id:'EVERY',role:c.role,prompt:'x',targets:[{group_id:'C',slot_id:'1'},{group_id:'C',slot_id:'2'}],trigger_mode:'EVERY_X_MINUTES',interval_minutes:1});
assert.equal(restored.tick().length,2); now+=120000; assert.equal(restored.tick().length,0); const ev=restored.get('EVERY');
assert.equal(restored.complete({role:c.role,command_id:'EVERY',dispatch_id:ev.targets[0].last_dispatch_id}).accepted,true); assert.equal(restored.tick().length,1); assert.equal(restored.tick().length,0);
const snap=restored.snapshot(); assert.ok(snap.work_control_log.some(x=>x.event==='TARGET_END')); assert.ok(snap.receipts.every(x=>x.group_id&&x.slot_id&&x.prompt_sha256));
console.log(JSON.stringify({status:'PASS',assertions:25,receipts:snap.receipts.length,targets_persisted:rs.targets.length}));
