'use strict';
const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const { RegistryAuthorityState } = require('../c_mode_registry_authority.cjs');
let n=0; const t=(name,fn)=>{fn();n++;};
const pointer=(comment='5193625388')=>`C_MODE_WAVE_V2|WAVE_ID=V1-C-MODE-6W-WAVE-007|READY=true|WORKER_COUNT=1|END_WAVE=W7\nW7|ROLE=AUTOMATION-C-W1|PR=59|COMMENT=${comment}|RESULT_KEY=${comment}00`;
const s=new RegistryAuthorityState();
let r1;
t('register sequence 1',()=>{r1=s.register(pointer(),{registry_sequence:1,registry_id:'REG-1'});assert.equal(r1.registry_sequence,1)});
t('duplicate wave sequence fails',()=>assert.throws(()=>s.register(pointer(),{registry_sequence:1,registry_id:'REG-X'}),/DUPLICATE_WAVE_SEQUENCE_READY/));
t('non monotonic fails',()=>assert.throws(()=>s.register(pointer('5193625389'),{registry_sequence:0,registry_id:'REG-0'}),/INVALID_REGISTRY_SEQUENCE/));
t('missing supersedes fails',()=>assert.throws(()=>s.register(pointer('5193625390'),{registry_sequence:2,registry_id:'REG-2'}),/SUPERSEDES_CHAIN_MISMATCH/));
t('wrong supersedes fails',()=>assert.throws(()=>s.register(pointer('5193625391'),{registry_sequence:2,registry_id:'REG-2',supersedes:'BAD'}),/SUPERSEDES_CHAIN_MISMATCH/));
let r2;
t('valid supersedes',()=>{r2=s.register(pointer('5193625392'),{registry_sequence:2,registry_id:'REG-2',supersedes:'REG-1'});assert.equal(r2.supersedes,'REG-1')});
t('latest snapshot',()=>assert.equal(s.latestSnapshot('V1-C-MODE-6W-WAVE-007').registry_id,'REG-2'));
const snap=s.snapshot(); const restored=new RegistryAuthorityState(snap);
t('restart latest restore',()=>assert.equal(restored.latestSnapshot('V1-C-MODE-6W-WAVE-007').registry_sequence,2));
t('restart duplicate prevention',()=>assert.throws(()=>restored.register(pointer('5193625393'),{registry_sequence:2,registry_id:'REG-X',supersedes:'REG-2'}),/DUPLICATE_WAVE_SEQUENCE_READY/));
const bytes=Buffer.from('source-export-fixture'); const sha=crypto.createHash('sha256').update(bytes).digest('hex');
let manifest;
t('source export manifest',()=>{manifest=restored.exportSourceManifest('V1-C-MODE-6W-WAVE-007',[{path:'automation-c-v1/c_mode_wave_pointer.cjs',commit:'31528c31ea3f4a10d2a7034491c2dacb75829e00',blob_sha:'4e651f02a3e0992e2f8379d89e6a15cbaa546956',sha256:sha}]);assert.equal(manifest.files.length,1)});
t('manifest sha256',()=>assert.match(manifest.manifest_sha256,/^[0-9a-f]{64}$/));
t('missing source sha fails',()=>assert.throws(()=>restored.exportSourceManifest('V1-C-MODE-6W-WAVE-007',[{path:'x',commit:'31528c31ea3f4a10d2a7034491c2dacb75829e00',blob_sha:'4e651f02a3e0992e2f8379d89e6a15cbaa546956'}]),/SOURCE_SHA256_MISSING/));
t('legacy relay retained',()=>{const p=r2.pointer; restored.prefetch(p,()=> 'directive'); assert.equal(restored.dispatchAll(p,()=>{}).length,1)});
t('exactly once retained',()=>assert.equal(restored.dispatchAll(r2.pointer,()=>{}).length,0));
t('snapshot relay retained',()=>{const x=new RegistryAuthorityState(restored.snapshot());assert.equal(x.dispatchAll(r2.pointer,()=>{}).length,0)});
console.log(`PASS_${n}_OF_${n}`);
