'use strict';
const assert=require('node:assert/strict');
const {buildSemanticBinding}=require('./api_ui_state_entity_semantic_binding.cjs');
let n=0;const eq=(a,b)=>{assert.deepEqual(a,b);n++};const ok=x=>{assert.ok(x);n++};
const c4={schema_version:'A5_ACTION_STATE_API_ENTITY_BINDING_RESULT_V1',decision_digest:'c4digest',provenance:{command_id:'CMD-1',page_id:'page-1',action_ids:['ACT-1'],evidence_pointer:{a3:'github://a3',a4:'github://a4'}},action_network_binding:{bindings:[{action_id:'ACT-1',command_id:'CMD-1',page_id:'page-1',action_kind:'submit',evidence_pointer:'github://a3/action/1',network_requests:[{endpoint_id:'EP-1',request_id:'REQ-1',method:'POST',url_template:'https://fixture.local/api/items',evidence_pointer:'github://a3/request/1'}]}]},api_ui_binding_graph:{nodes:[{node_id:'item-list',node_type:'UI_COMPONENT',kind:'LIST',evidence_pointer:'github://a4/component/1'},{node_id:'ENT-1',node_type:'DATA_ENTITY',record_path:'$.record',request_id:'REQ-1',evidence_pointer:'github://a3/body/1'}],edges:[{from:'ENT-1',to:'item-list',relation:'ENTITY_FIELD_TO_COMPONENT_CANDIDATE',authority:'CANDIDATE',confidence:.78,evidence_pointer:['github://a3/body/1','github://a4/component/1']}]},ui_state_transition_graph:{transitions:[{action_id:'ACT-1',component_id:'item-list',state_before:'COUNT_1',state_after:'COUNT_2',authority:'OBSERVED',evidence_pointer:'github://a3/state/1'}]},data_entity_relationship_graph:{nodes:[{entity_id:'ENT-1',record_path:'$.record',request_id:'REQ-1',identifier_paths:['$.record.record_id'],authority:'OBSERVED_REDACTED_BODY',evidence_pointer:'github://a3/body/1'}],edges:[],business_rules:{status:'UNKNOWN',reason:'BUSINESS_RULES_NOT_OBSERVED'}},form_field_canonical_candidate:{candidates:[{form_id:'item-form',field_name:'price',canonical_candidate:{json_path:'$.record.price',authority:'CANDIDATE',confidence:.95,evidence_pointer:['github://a4/form/price','github://a3/body/1']},read_transform:{from:'$.record.price',to:'price',transform:'IDENTITY_CANDIDATE',authority:'CANDIDATE',confidence:.9,evidence_pointer:'github://a3/body/1'},write_transform:{from:'price',to:'price',location:'body',transform:'IDENTITY_CANDIDATE',authority:'CANDIDATE',confidence:.82,evidence_pointer:'github://a3/request/1'}}]},raw_secret_value_count:0};
const a=buildSemanticBinding(c4),b=buildSemanticBinding(c4);
eq(a.api_ui_state_binding_graph.schema_version,'API_UI_STATE_BINDING_GRAPH_V1');
eq(a.data_entity_graph.schema_version,'DATA_ENTITY_GRAPH_V1');
eq(a.form_field_semantic_candidate.schema_version,'FORM_FIELD_SEMANTIC_CANDIDATE_V1');
ok(a.api_ui_state_binding_graph.edges.some(e=>e.relation==='ACTION_TRIGGERS_ENDPOINT'&&e.authority==='OBSERVED'));
ok(a.api_ui_state_binding_graph.edges.some(e=>e.relation==='ACTION_TRANSITIONS_UI_STATE'&&e.authority==='OBSERVED'));
ok(a.api_ui_state_binding_graph.edges.some(e=>e.relation==='ENDPOINT_RETURNS_ENTITY'&&e.authority==='OBSERVED'));
ok(a.api_ui_state_binding_graph.edges.some(e=>e.relation==='ENTITY_PRESENTED_BY_COMPONENT'&&e.authority==='CANDIDATE'));
eq(a.data_entity_graph.nodes[0].application_fields[0].application_canonical_candidate,'price');
eq(a.data_entity_graph.nodes[0].application_fields[0].d_canonical_authority,false);
eq(a.form_field_semantic_candidate.candidates[0].application_canonical_candidate.name,'price');
eq(a.form_field_semantic_candidate.candidates[0].application_canonical_candidate.d_canonical_authority,false);
eq(a.form_field_semantic_candidate.candidates[0].business_rule.status,'UNKNOWN');
eq(a.raw_secret_value_count,0);
eq(a.semantic_digest,b.semantic_digest);
ok(/^[a-f0-9]{64}$/.test(a.semantic_digest));
ok(a.evidence_pointer.includes('github://a3/request/1'));
const missing=JSON.parse(JSON.stringify(c4));delete missing.data_entity_relationship_graph.nodes[0].request_id;missing.api_ui_binding_graph.nodes.find(x=>x.node_type==='DATA_ENTITY').request_id='UNKNOWN';const m=buildSemanticBinding(missing);ok(m.api_ui_state_binding_graph.unresolved_bindings.some(x=>x.relation==='ENDPOINT_RETURNS_ENTITY'&&x.status==='INSUFFICIENT_EVIDENCE'));
eq(m.decision_status,'READY_WITH_INSUFFICIENT_EVIDENCE');
const noState=JSON.parse(JSON.stringify(c4));noState.ui_state_transition_graph.transitions=[{status:'UNKNOWN',reason:'NO_EXPLICIT_UI_STATE_TRANSITION_OBSERVED',evidence_pointer:'github://a4'}];const s=buildSemanticBinding(noState);ok(s.api_ui_state_binding_graph.unresolved_bindings.some(x=>x.relation==='ACTION_TO_UI_STATE'));
const secret=JSON.parse(JSON.stringify(c4));secret.action_network_binding.bindings[0].network_requests[0].authorization='Bearer SECRETSECRET';assert.throws(()=>buildSemanticBinding(secret),/RAW_SECRET_VALUE_REJECTED/);n++;
console.log(JSON.stringify({status:'PASS',fixture_replay_count:2,assertions:n,semantic_digest_run1:a.semantic_digest,semantic_digest_run2:b.semantic_digest,unresolved_missing_entity_request:m.api_ui_state_binding_graph.unresolved_bindings.length}));
