#!/usr/bin/env node
'use strict';
const fs=require('node:fs');const path=require('node:path');
const {CSS_HOOK,JS_HOOK,MAIN_BEGIN,MAIN_END,MEMBERS,hash}=require('./apply_w3_rc6_ui_overlay.cjs');
function read(f){return fs.readFileSync(f,'utf8').replace(/^\uFEFF/,'');}function write(f,t){fs.writeFileSync(f,t,'utf8');}
function removeHookLine(text,hook){const lines=text.split(/(?<=\n)/);const filtered=lines.filter(line=>!line.includes(hook));return filtered.join('');}
function removeMainBlock(text){const s=text.indexOf(MAIN_BEGIN);const e=text.indexOf(MAIN_END);if(s<0&&e<0)return text;if(s<0||e<s)throw new Error('PARTIAL_MAIN_HOOK');let end=e+MAIN_END.length;if(text.slice(end,end+2)==='\r\n')end+=2;else if(text[end]==='\n')end+=1;return text.slice(0,s)+text.slice(end);}
function parse(argv){const o={};for(let i=2;i<argv.length;i+=2){if(!argv[i]?.startsWith('--')||argv[i+1]==null)throw new Error('BAD_ARG');o[argv[i].slice(2)]=argv[i+1];}for(const k of ['release','receipt'])if(!o[k])throw new Error(`MISSING_ARG:${k}`);return o;}
function rollback(root){const main=path.join(root,'main.js'),html=path.join(root,'workspace.html');for(const f of [main,html])if(!fs.existsSync(f))throw new Error(`BASELINE_RENDERER_FILE_MISSING:${path.basename(f)}`);const before={main_sha256:hash(fs.readFileSync(main)),workspace_html_sha256:hash(fs.readFileSync(html)),base_js_sha256:hash(fs.readFileSync(path.join(root,'workspace_c_mode.js'))),base_css_sha256:hash(fs.readFileSync(path.join(root,'workspace_c_mode.css')))};
 let h=read(html);h=removeHookLine(h,CSS_HOOK);h=removeHookLine(h,JS_HOOK);write(html,h);write(main,removeMainBlock(read(main)));
 const removed=[];for(const m of MEMBERS){const f=path.join(root,m.dest);if(!fs.existsSync(f))continue;const actual=hash(fs.readFileSync(f));if(actual!==m.sha256)throw new Error(`OVERLAY_FILE_HASH_MISMATCH:${m.dest}`);fs.rmSync(f,{force:true});removed.push(m.dest);}
 const after={main_sha256:hash(fs.readFileSync(main)),workspace_html_sha256:hash(fs.readFileSync(html)),base_js_sha256:hash(fs.readFileSync(path.join(root,'workspace_c_mode.js'))),base_css_sha256:hash(fs.readFileSync(path.join(root,'workspace_c_mode.css')))};if(before.base_js_sha256!==after.base_js_sha256||before.base_css_sha256!==after.base_css_sha256)throw new Error('BASE_UI_BYTES_CHANGED_DURING_ROLLBACK');return {schema_version:'W3_RC6_UI_ROLLBACK_RECEIPT_V1',status:'PASS',mode:'REMOVAL_ONLY',removed,base_ui_preserved:true,profile_or_state_modified:false,before,after,live_pass_claimed:false};}
if(require.main===module){const a=parse(process.argv);const r=rollback(path.resolve(a.release));fs.mkdirSync(path.dirname(path.resolve(a.receipt)),{recursive:true});fs.writeFileSync(a.receipt,JSON.stringify(r,null,2)+'\n');console.log(`W3_RC6_UI_ROLLBACK_PASS removed=${r.removed.length}`);}module.exports={rollback};
