#!/usr/bin/env node
'use strict';
const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const os=require('node:os');const crypto=require('node:crypto');const cp=require('node:child_process');const vm=require('node:vm');
function parse(argv){const o={};for(let i=2;i<argv.length;i+=2){if(!argv[i]?.startsWith('--')||argv[i+1]==null)throw new Error('BAD_ARG');o[argv[i].slice(2)]=argv[i+1];}for(const k of ['root','manifest','receipt'])if(!o[k])throw new Error(`MISSING_ARG:${k}`);return o;}
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');const fileHash=f=>hash(fs.readFileSync(f));
function run(root,manifestPath){let n=0;const ok=(v,m)=>{n++;assert.ok(v,m);};const eq=(a,b,m)=>{n++;assert.deepEqual(a,b,m);};const m=JSON.parse(fs.readFileSync(manifestPath,'utf8'));
 const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'w3-rc6-ui-'));const rel=path.join(tmp,'release');const profile=path.join(tmp,'browser-profile');fs.mkdirSync(rel,{recursive:true});fs.mkdirSync(profile,{recursive:true});
 fs.writeFileSync(path.join(rel,'main.js'),'"use strict";\nconst APP_VERSION = "5.10.2.4.1";\nfunction createWorkspaceWindow(){return true;}\n');
 fs.writeFileSync(path.join(rel,'workspace.html'),'<!doctype html>\n<html><head>\n  <link rel="stylesheet" href="./workspace.css">\n  <link rel="stylesheet" href="./workspace_c_mode.css">\n</head><body>\n  <script src="./workspace.js"></script>\n  <script src="./workspace_c_mode.js"></script>\n</body></html>\n');
 fs.writeFileSync(path.join(rel,'workspace_c_mode.js'),'window.baseWorkspaceCMode=true;\n');fs.writeFileSync(path.join(rel,'workspace_c_mode.css'),'.base-c-mode{display:block}\n');fs.writeFileSync(path.join(profile,'Preferences'),'fixed-login-profile-byte-fixture\n');
 const pre={main:fileHash(path.join(rel,'main.js')),html:fileHash(path.join(rel,'workspace.html')),baseJs:fileHash(path.join(rel,'workspace_c_mode.js')),baseCss:fileHash(path.join(rel,'workspace_c_mode.css')),profile:fileHash(path.join(profile,'Preferences'))};
 const pkg=path.join(root,'rc6-package');const patch=path.join(pkg,'tools/apply_w3_rc6_ui_overlay.cjs');const rollback=path.join(pkg,'tools/rollback_w3_rc6_ui_overlay.cjs');const validator=path.join(pkg,'tools/validate_w3_rc6_ui_package.cjs');
 cp.execFileSync(process.execPath,[validator,'--root',root,'--manifest',manifestPath,'--receipt',path.join(tmp,'membership.json')],{stdio:'pipe'});ok(JSON.parse(fs.readFileSync(path.join(tmp,'membership.json'),'utf8')).status==='PASS','membership');
 cp.execFileSync(process.execPath,[patch,'--release',rel,'--package',pkg,'--receipt',path.join(tmp,'patch1.json')],{stdio:'pipe'});cp.execFileSync(process.execPath,[patch,'--release',rel,'--package',pkg,'--receipt',path.join(tmp,'patch2.json')],{stdio:'pipe'});
 const p1=JSON.parse(fs.readFileSync(path.join(tmp,'patch1.json'),'utf8')),p2=JSON.parse(fs.readFileSync(path.join(tmp,'patch2.json'),'utf8'));eq(p1.changed,true,'first patch changed');eq(p2.changed,false,'second patch idempotent');
 const html=fs.readFileSync(path.join(rel,'workspace.html'),'utf8'),main=fs.readFileSync(path.join(rel,'main.js'),'utf8');eq((html.match(/data-yolla-overlay="w3-rc6"/g)||[]).length,2,'two renderer hooks');eq((main.match(/YOLLA_W3_RC6_UI_LOAD_HOOK_V1_BEGIN/g)||[]).length,1,'one bridge hook');ok(html.indexOf('workspace_c_mode_rc4_truth.css')>html.indexOf('workspace_c_mode.css'),'css order');ok(html.indexOf('workspace_c_mode_rc4_truth.js')>html.indexOf('workspace_c_mode.js'),'js order');ok(main.indexOf('workspace_ui_truth_bridge.cjs')<main.indexOf('createWorkspaceWindow'),'bridge before renderer creation');
 eq(fileHash(path.join(rel,'workspace_c_mode.js')),pre.baseJs,'base js preserved');eq(fileHash(path.join(rel,'workspace_c_mode.css')),pre.baseCss,'base css preserved');eq(fileHash(path.join(profile,'Preferences')),pre.profile,'profile preserved');
 const bridge=require(path.join(rel,'automation-c-v1/workspace_ui_truth_bridge.cjs'));const context={console,setInterval:()=>0,clearInterval:()=>{},requestAnimationFrame:f=>f(),window:{yollaWorkspaceV5:{},addEventListener:()=>{}},document:{getElementById:()=>null,querySelectorAll:()=>[],createElement:()=>({})}};vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(rel,'workspace_c_mode_rc4_truth.js'),'utf8'),context);const ui=context.window.yollaUiTruthV12;ok(ui,'ui export');
 const watcher={c_enabled:true,command_enabled:true,c_active_roles:['W1'],reports_by_role:{W3:{registry_relation:'CURRENT',result_comment_id:5195394714,result_key:'519517264100'},W4:{registry_relation:'HISTORICAL',result_comment_id:5194991632,result_key:'519440526200'},W6:{result_commit:'a'.repeat(40),result_key:'missing'},W7:{duplicate_report:true,result_comment_id:7,result_key:'dup'},W8:{error:true},W9:{status:'END'}},repeat_by_role:{W2:{state:'RUNNING'},W5:{state:'AWAITING'}}};const activity=bridge.normalizeUiTruth(watcher);const roles=['W1','W2','W3','W4','W5','W6','W7','W8','W9','W10'];const counts=ui.truthCountsFromActivity(roles,activity);eq({...counts},{working:4,c:1,command:1,current:1,historical:1,awaiting:1,missing:1,duplicate:1,error:1,end:1,idle:1},'mixed counts');eq(ui.projectRoleFromActivity(activity,'W3').reference,'RESULT_COMMENT #5195394714','comment priority');eq(ui.truthCountsFromActivity(roles,{...activity,c_enabled:false,command_enabled:false}).working,0,'disabled zero');ok(!fs.readFileSync(path.join(rel,'workspace_c_mode_rc4_truth.js'),'utf8').includes('profile.status'),'legacy excluded');
 cp.execFileSync(process.execPath,[rollback,'--release',rel,'--receipt',path.join(tmp,'rollback1.json')],{stdio:'pipe'});cp.execFileSync(process.execPath,[rollback,'--release',rel,'--receipt',path.join(tmp,'rollback2.json')],{stdio:'pipe'});const post={main:fileHash(path.join(rel,'main.js')),html:fileHash(path.join(rel,'workspace.html')),baseJs:fileHash(path.join(rel,'workspace_c_mode.js')),baseCss:fileHash(path.join(rel,'workspace_c_mode.css')),profile:fileHash(path.join(profile,'Preferences'))};eq(post,pre,'rollback exact preimage');for(const f of ['workspace_c_mode_rc4_truth.js','workspace_c_mode_rc4_truth.css','automation-c-v1/workspace_ui_truth_bridge.cjs'])ok(!fs.existsSync(path.join(rel,f)),`removed ${f}`);
 return {schema_version:'W3_RC6_UI_SMOKE_RECEIPT_V1',status:'PASS',assertion_count:n,target_version:'5.10.2.4.2-rc6',exact_ui_source_bytes:true,base_ui_preserved:true,css_load_after_base_css:true,js_load_after_base_js:true,bridge_load_before_ui_overlay:true,fixed_browser_profile_unchanged:true,c_and_repeat_disabled_working_count:0,legacy_a_e_current_count:0,idempotent_patch:true,idempotent_rollback:true,live_pass_claimed:false};}
if(require.main===module){const a=parse(process.argv);const r=run(path.resolve(a.root),path.resolve(a.manifest));fs.mkdirSync(path.dirname(path.resolve(a.receipt)),{recursive:true});fs.writeFileSync(a.receipt,JSON.stringify(r,null,2)+'\n');console.log(`W3_RC6_UI_SMOKE_PASS assertions=${r.assertion_count}`);}module.exports={run};
