#!/usr/bin/env node
'use strict';
const fs=require('node:fs');const path=require('node:path');const crypto=require('node:crypto');
function parse(argv){const o={};for(let i=2;i<argv.length;i+=2){if(!argv[i]?.startsWith('--')||argv[i+1]==null)throw new Error('BAD_ARG');o[argv[i].slice(2)]=argv[i+1];}for(const k of ['root','manifest','receipt'])if(!o[k])throw new Error(`MISSING_ARG:${k}`);return o;}
function hash(b){return crypto.createHash('sha256').update(b).digest('hex');}
function assert(c,m){if(!c)throw new Error(m);}
function validate(root,m){
 assert(m.schema_version==='W3_RC6_AUTHORITY_UI_EXPORT_V1','SCHEMA_MISMATCH');assert(m.target_version==='5.10.2.4.2-rc6','VERSION_MISMATCH');
 const a=m.authority;assert(a.state_root==='E:\\SOURCE FACTORY\\.yolla\\yolla-workspace-v5-2','STATE_ROOT_MISMATCH');assert(a.release_root==='E:\\SOURCE FACTORY\\.yolla\\yolla-panel\\releases','RELEASE_ROOT_MISMATCH');assert(a.browser_profile==='E:\\SOURCE FACTORY\\.yolla\\yolla-workspace-browser-profile','PROFILE_MISMATCH');assert(a.worker_partition==='persist:sf4-safe-panel-worker-1','WORKER_PARTITION_MISMATCH');assert(a.analysis_partition==='persist:yolla-analysis-browser-v1','ANALYSIS_PARTITION_MISMATCH');
 assert(m.candidate_release_root===a.release_root+'\\5.10.2.4.2-rc6','CANDIDATE_ROOT_MISMATCH');assert(m.base_release_resolution.mode==='EXISTING_LAUNCHER_OR_VALIDATED_PARAMETER','BASE_RESOLUTION_MODE');
 const members=m.members||[];assert(members.length===7,'MEMBER_COUNT');assert(new Set(members.map(x=>x.package_path)).size===members.length,'DUPLICATE_PACKAGE_PATH');
 const destinations=members.filter(x=>x.install_destination).map(x=>x.install_destination);assert(new Set(destinations).size===destinations.length,'DUPLICATE_INSTALL_DESTINATION');
 const results=[];for(const x of members){assert(/^[0-9a-f]{40}$/.test(x.source_commit),'BAD_COMMIT');assert(/^[0-9a-f]{40}$/.test(x.source_blob),'BAD_BLOB');assert(/^[0-9a-f]{64}$/.test(x.sha256),'BAD_SHA256');const f=path.resolve(root,x.package_path);const rootPrefix=path.resolve(root)+path.sep;assert(f.startsWith(rootPrefix),'PACKAGE_PATH_ESCAPE');assert(fs.existsSync(f)&&fs.statSync(f).isFile(),`MEMBER_MISSING:${x.package_path}`);const body=fs.readFileSync(f);assert(body.length===x.size_bytes,`SIZE_MISMATCH:${x.package_path}`);assert(hash(body)===x.sha256,`HASH_MISMATCH:${x.package_path}`);if(x.install_destination)assert(x.install_destination.startsWith(m.candidate_release_root+'\\'),'DESTINATION_OUTSIDE_CANDIDATE');results.push({logical_role:x.logical_role,package_path:x.package_path,status:'PASS'});}
 const runtime=members.filter(x=>x.classification==='EXECUTABLE_RUNTIME').sort((x,y)=>x.load_order-y.load_order);assert(runtime.map(x=>x.logical_role).join(',')==='TRUTH_BRIDGE,CSS_OVERLAY,JS_OVERLAY','RUNTIME_ORDER');assert(runtime.map(x=>x.load_order).join(',')==='11,12,13','LOAD_ORDER');
 assert(runtime[0].sha256==='8086f56f1f0b5731cb9ad4be5339fc211d1468f4195fcf249b7a300cc3b830e8','BRIDGE_NOT_EXACT_WAVE12');assert(runtime[1].sha256==='43b6a3721c250e76b2562c45d931fd17d87ae219fec70aa3ef3206af9cd8b0fe','CSS_NOT_EXACT_WAVE12');assert(runtime[2].sha256==='5fdd1719e110ce80ad4b3efb911fd20a86ccbfeb27182645e8d2170287114b54','JS_NOT_EXACT_WAVE12');
 const h=m.load_hook_contract;assert(h.css.anchor==='<link rel="stylesheet" href="./workspace_c_mode.css">','CSS_ANCHOR');assert(h.css.overlay.includes('data-yolla-overlay="w3-rc6"'),'CSS_OVERLAY_MARKER');assert(h.js.anchor==='<script src="./workspace_c_mode.js"></script>','JS_ANCHOR');assert(h.js.overlay.includes('data-yolla-overlay="w3-rc6"'),'JS_OVERLAY_MARKER');assert(h.bridge.main_marker==='YOLLA_W3_RC6_UI_LOAD_HOOK_V1','BRIDGE_MARKER');assert(h.bridge.load_before_ui_overlay===true,'BRIDGE_ORDER');
 assert(m.rollback.mode==='REMOVAL_ONLY'&&m.rollback.base_ui_preserved===true,'ROLLBACK_CONTRACT');assert(m.fixed_browser_profile_contract.unchanged===true&&m.fixed_browser_profile_contract.write_scope==='NONE','PROFILE_CONTRACT');
 for(const [k,v] of Object.entries({EXACT_UI_SOURCE_BYTES:true,CSS_LOAD_AFTER_BASE_CSS:true,JS_LOAD_AFTER_BASE_JS:true,BRIDGE_LOAD_BEFORE_UI_OVERLAY:true,FIXED_BROWSER_PROFILE_UNCHANGED:true,C_AND_REPEAT_DISABLED_WORKING_COUNT:0,LEGACY_A_E_CURRENT_COUNT:0}))assert(m.required_gates[k]===v,`GATE_${k}`);
 return {schema_version:'W3_RC6_UI_MEMBERSHIP_RECEIPT_V1',status:'PASS',target_version:m.target_version,member_count:members.length,runtime_member_count:runtime.length,authority_correct:true,exact_ui_source_bytes:true,results,live_pass_claimed:false};
}
if(require.main===module){const a=parse(process.argv);const m=JSON.parse(fs.readFileSync(a.manifest,'utf8'));const r=validate(path.resolve(a.root),m);fs.mkdirSync(path.dirname(path.resolve(a.receipt)),{recursive:true});fs.writeFileSync(a.receipt,JSON.stringify(r,null,2)+'\n');console.log(`W3_RC6_UI_MEMBERSHIP_PASS members=${r.member_count}`);}module.exports={validate,hash};
