'use strict';
const crypto = require('crypto');
function object(value){return value!==null&&typeof value==='object'&&!Array.isArray(value)?value:{}}
function text(value){return typeof value==='string'&&value.trim()?value.trim():''}
function canonical(value){if(Array.isArray(value))return value.map(canonical);if(value===null||typeof value!=='object')return value;const output={};Object.keys(value).sort().forEach((key)=>{output[key]=canonical(value[key])});return output}
function sha256(value){const input=typeof value==='string'?value:JSON.stringify(canonical(value));return crypto.createHash('sha256').update(Buffer.from(input,'utf8')).digest('hex')}
function parseWaveNumber(waveId){const match=text(waveId).toUpperCase().match(/(?:WAVE[_-]?)?(\d+)$/);return match?Number(match[1]):null}
function normalizeKstMinute(value){const match=text(value).match(/^(\d{4})-(\d{2})-(\d{2})[ T](\d{2}):(\d{2}) KST$/);if(!match)return null;const[,year,month,day,hour,minute]=match;const canonicalValue=`${year}-${month}-${day} ${hour}:${minute} KST`;const epoch=Date.parse(`${year}-${month}-${day}T${hour}:${minute}:00+09:00`);return Number.isFinite(epoch)?{canonical:canonicalValue,epoch}:null}
function normalizePrompt(input){const source=object(input);return{role_id:text(source.role_id),directive_id:text(source.directive_id),wave_id:text(source.wave_id),directive_registered_at_kst:text(source.directive_registered_at_kst),platform_id:text(source.platform_id),service_id:text(source.service_id),domain_pack_id:text(source.domain_pack_id),supersession_pointer:text(source.supersession_pointer),rework_authority:text(source.rework_authority),result_comment:Number.isInteger(Number(source.result_comment))?Number(source.result_comment):null,result_accepted:source.result_accepted===true,metadata:object(source.metadata)}}
function duplicateKey(promptInput){const prompt=normalizePrompt(promptInput);return sha256([prompt.role_id,prompt.directive_id,prompt.wave_id,prompt.directive_registered_at_kst].join('|'))}
function identityKey(prompt){return`${prompt.role_id}|${prompt.directive_id}`}
function normalizeLedger(input){return(Array.isArray(input)?input:[]).map((entry)=>{const prompt=normalizePrompt(entry);return{...prompt,duplicate_key:text(entry&&entry.duplicate_key)||duplicateKey(prompt),decision:text(entry&&entry.decision),terminal:text(entry&&entry.terminal)}})}
function preserveSpecialistPayloads(payloadsInput){return(Array.isArray(payloadsInput)?payloadsInput:[]).map((payloadInput)=>{const payload=object(payloadInput);return{...payload,platform_id:text(payload.platform_id),service_id:text(payload.service_id),domain_pack_id:text(payload.domain_pack_id)}})}
module.exports={object,text,sha256,parseWaveNumber,normalizeKstMinute,normalizePrompt,duplicateKey,identityKey,normalizeLedger,preserveSpecialistPayloads};
