'use strict';
const core=require('./core');
const DECISIONS=Object.freeze({ACCEPT:'ACCEPT',REJECT_DUPLICATE:'REJECT_DUPLICATE',REJECT_ALREADY_ACCEPTED:'REJECT_ALREADY_ACCEPTED',REJECT_STALE_WAVE:'REJECT_STALE_WAVE',REQUIRE_SUPERSESSION_POINTER:'REQUIRE_SUPERSESSION_POINTER',REJECT_PREVIOUS_WAVE_RESULT_REQUIRED:'REJECT_PREVIOUS_WAVE_RESULT_REQUIRED',FAIL_CLOSED:'FAIL_CLOSED'});
function reject(decision,findings,prompt,key){return{admitted:false,decision,findings,duplicate_key:key||null,prompt_identity:{role_id:prompt.role_id,directive_id:prompt.directive_id,wave_id:prompt.wave_id,directive_registered_at_kst:prompt.directive_registered_at_kst},payload_identity:{platform_id:prompt.platform_id,service_id:prompt.service_id,domain_pack_id:prompt.domain_pack_id},auto_next_wave_created:false,manual_prompt_composition_count:0}}
function evaluatePrompt(promptInput,contextInput){
 const prompt=core.normalizePrompt(promptInput),context=core.object(contextInput),ledger=core.normalizeLedger(context.ledger),findings=[];
 const waveNumber=core.parseWaveNumber(prompt.wave_id),registeredAt=core.normalizeKstMinute(prompt.directive_registered_at_kst);
 if(!prompt.role_id)findings.push('ROLE_ID_MISSING');if(!prompt.directive_id)findings.push('DIRECTIVE_ID_MISSING');if(!prompt.wave_id)findings.push('WAVE_ID_MISSING');if(!prompt.directive_registered_at_kst)findings.push('DIRECTIVE_REGISTERED_AT_KST_MISSING');if(prompt.wave_id&&waveNumber===null)findings.push('WAVE_ID_INVALID');if(prompt.directive_registered_at_kst&&!registeredAt)findings.push('DIRECTIVE_REGISTERED_AT_KST_INVALID');if(!prompt.platform_id)findings.push('PLATFORM_ID_MISSING');if(!prompt.service_id)findings.push('SERVICE_ID_MISSING');if(!prompt.domain_pack_id)findings.push('DOMAIN_PACK_ID_MISSING');if(findings.length)return reject(DECISIONS.FAIL_CLOSED,findings,prompt,null);
 const key=core.duplicateKey(prompt),exactDuplicate=ledger.find((entry)=>entry.duplicate_key===key);if(exactDuplicate)return reject(DECISIONS.REJECT_DUPLICATE,['DUPLICATE_PROMPT_KEY_ALREADY_OBSERVED'],prompt,key);
 const accepted=ledger.find((entry)=>core.identityKey(entry)===core.identityKey(prompt)&&entry.result_accepted&&!prompt.rework_authority);if(accepted)return reject(DECISIONS.REJECT_ALREADY_ACCEPTED,['DIRECTIVE_RESULT_ALREADY_ACCEPTED'],prompt,key);
 const roleEntries=ledger.filter((entry)=>entry.role_id===prompt.role_id),numericEntries=roleEntries.map((entry)=>({entry,wave:core.parseWaveNumber(entry.wave_id)})).filter((item)=>item.wave!==null),latestWave=numericEntries.length?Math.max(...numericEntries.map((item)=>item.wave)):null;
 if(latestWave!==null&&waveNumber<latestWave)return reject(DECISIONS.REJECT_STALE_WAVE,['OLDER_WAVE_THAN_LATEST_OBSERVED'],prompt,key);
 const sameWave=roleEntries.find((entry)=>entry.directive_id===prompt.directive_id&&core.parseWaveNumber(entry.wave_id)===waveNumber&&entry.directive_registered_at_kst!==prompt.directive_registered_at_kst);
 if(sameWave&&!prompt.supersession_pointer)return reject(DECISIONS.REQUIRE_SUPERSESSION_POINTER,['SAME_WAVE_DIFFERENT_REGISTERED_TIME'],prompt,key);
 if(sameWave&&prompt.supersession_pointer!==sameWave.duplicate_key)return reject(DECISIONS.REQUIRE_SUPERSESSION_POINTER,['SUPERSESSION_POINTER_DOES_NOT_MATCH_PRIOR_DUPLICATE_KEY'],prompt,key);
 if(latestWave!==null&&waveNumber===latestWave+1&&!prompt.rework_authority){const prior=numericEntries.find((item)=>item.wave===latestWave&&Number.isInteger(item.entry.result_comment)&&item.entry.result_comment>0);if(!prior)return reject(DECISIONS.REJECT_PREVIOUS_WAVE_RESULT_REQUIRED,['PREVIOUS_WAVE_RESULT_COMMENT_OR_REWORK_AUTHORITY_REQUIRED'],prompt,key)}
 return{admitted:true,decision:DECISIONS.ACCEPT,findings:[],duplicate_key:key,prompt_identity:{role_id:prompt.role_id,directive_id:prompt.directive_id,wave_id:prompt.wave_id,directive_registered_at_kst:registeredAt.canonical},payload_identity:{platform_id:prompt.platform_id,service_id:prompt.service_id,domain_pack_id:prompt.domain_pack_id},supersession_pointer:prompt.supersession_pointer||null,rework_authority:prompt.rework_authority||null,dispatch_plan_only:true,actual_dispatch_performed:false,auto_next_wave_created:false,manual_prompt_composition_count:0};
}
module.exports={DECISIONS,evaluatePrompt};
