'use strict';
const {ACTIONS,ACTION_CAPABILITY}=require('./constants');
const {obj,text,admitDirective,directiveKey,idempotencyKey,duplicateFinding}=require('./directiveAdmission');
function bindingFor(action,c){const cap=ACTION_CAPABILITY[action],b=obj(c.apiBindings)&&obj(c.apiBindings[cap])?c.apiBindings[cap]:null,f=[];if(!b)return{cap,b:null,f:['API_BINDING_MISSING_'+cap]};if(!text(b.authority))f.push('API_BINDING_AUTHORITY_MISSING');if(!text(b.method))f.push('API_BINDING_METHOD_MISSING');if(b.mode!=='EXISTING_CONTRACT_ONLY')f.push('API_BINDING_MODE_INVALID');return{cap,b:{...b},f}}
function retryFinding(d,c){const rows=(Array.isArray(c.executionLedger)?c.executionLedger:[]).filter(e=>obj(e)&&e.directiveKey===directiveKey(d));if(!rows.length)return'RETRY_PREDECESSOR_MISSING';return['BLOCKED','FAILED'].includes(text(rows[rows.length-1].status).toUpperCase())?null:'RETRY_PREDECESSOR_NOT_BLOCKED_OR_FAILED'}
function steps(action,d,b){const i={repository:d.repository,pr:d.pr,commentId:d.commentId,directiveId:d.directiveId,roleId:d.roleId,cycleId:d.cycleId};const call={step:'CALL_EXISTING_API_CONTRACT',capability:ACTION_CAPABILITY[action],authority:b.authority,method:b.method,identity:i,directivePackage:{...d.directivePackage},promptBodyGeneratedByController:false};const first={READ_AND_EXECUTE:{step:'READ_EXACT_DIRECTIVE',identity:i},RUN_SELECTED_ROLE:{step:'VERIFY_ROLE_SELECTED',roleId:d.roleId},REQUEST_STOP:{step:'REQUEST_COOPERATIVE_STOP',identity:i},RETRY:{step:'VERIFY_RETRY_PREDECESSOR',allowedStatuses:['BLOCKED','FAILED']},OPEN_RESULT:{step:'OPEN_EXACT_RESULT_REFERENCE',resultRef:d.resultRef},POST_PC_STATUS:{step:'POST_CURRENT_PC_STATUS',identity:i},BACKUP_NOW:{step:'REQUEST_CURRENT_BACKUP',identity:i}}[action];return first?[first,call]:[call]}
function buildActionPlan(action,input,contextInput){const c=obj(contextInput)?contextInput:{};if(!Object.values(ACTIONS).includes(action)||action===ACTIONS.RUN_GROUP)return{ok:false,findings:['ACTION_INVALID_OR_GROUP_ONLY'],plan:null};const a=admitDirective(input,c),b=bindingFor(action,c),f=a.findings.concat(b.f),attempt=Number.isInteger(c.attempt)&&c.attempt>0?c.attempt:1;if(action===ACTIONS.RETRY){const x=retryFinding(a.directive,c);if(x)f.push(x)}if(action===ACTIONS.OPEN_RESULT&&!obj(a.directive.resultRef))f.push('RESULT_REFERENCE_MISSING');const key=idempotencyKey(action,a.directive,attempt),dup=duplicateFinding(key,c.executionLedger);if(dup)f.push(dup);if(f.length)return{ok:false,findings:f,displayedIdentity:a.displayedIdentity,plan:null};return{ok:true,findings:[],displayedIdentity:a.displayedIdentity,plan:{schemaVersion:'C5_COMMAND_FLOW_CONTROLLER_V1',action,capability:b.cap,apiBinding:b.b,directiveKey:directiveKey(a.directive),idempotencyKey:key,attempt,planOnly:true,dryRun:true,actualDispatchPerformed:false,newTransportCreated:false,promptBodyGeneratedByController:false,manualPromptCompositionCount:0,steps:steps(action,a.directive,b.b)}}}
function buildGroupExecutionPlan(inputs,contextInput){const c=obj(contextInput)?contextInput:{},b=bindingFor(ACTIONS.RUN_GROUP,c),admitted=[],rejected=[];(Array.isArray(inputs)?inputs:[]).forEach(input=>{const a=admitDirective(input,c);if(!a.admitted)return rejected.push({identity:a.displayedIdentity,findings:a.findings});const key=idempotencyKey(ACTIONS.RUN_GROUP,a.directive,1),dup=duplicateFinding(key,c.executionLedger);if(dup)return rejected.push({identity:a.displayedIdentity,findings:[dup]});admitted.push({identity:a.displayedIdentity,directiveKey:directiveKey(a.directive),directivePackage:{...a.directive.directivePackage},idempotencyKey:key})});const f=b.f.slice();if(!admitted.length)f.push('NO_ADMITTED_DIRECTIVE_PACKAGES');if(f.length)return{ok:false,findings:f,plan:null,admitted,rejected};const m=Number.isInteger(c.maxParallel)&&c.maxParallel>0?c.maxParallel:admitted.length;return{ok:true,findings:[],admitted,rejected,plan:{schemaVersion:'C5_COMMAND_FLOW_CONTROLLER_V1',action:ACTIONS.RUN_GROUP,capability:b.cap,apiBinding:b.b,planOnly:true,dryRun:true,actualDispatchPerformed:false,newTransportCreated:false,promptBodyGeneratedByController:false,manualPromptCompositionCount:0,parallel:true,maxParallel:Math.min(m,admitted.length),dispatches:admitted}}}
module.exports={buildActionPlan,buildGroupExecutionPlan,bindingFor};
