'use strict';
const ACTIONS=Object.freeze({READ_AND_EXECUTE:'READ_AND_EXECUTE',RUN_SELECTED_ROLE:'RUN_SELECTED_ROLE',RUN_GROUP:'RUN_GROUP',REQUEST_STOP:'REQUEST_STOP',RETRY:'RETRY',OPEN_RESULT:'OPEN_RESULT',POST_PC_STATUS:'POST_PC_STATUS',BACKUP_NOW:'BACKUP_NOW'});
const STATES=Object.freeze({IDLE:'IDLE',DIRECTIVE_READY:'DIRECTIVE_READY',DISPATCHING:'DISPATCHING',RUNNING:'RUNNING',RESULT_WAITING:'RESULT_WAITING',COMPLETED:'COMPLETED',BLOCKED:'BLOCKED',FAILED:'FAILED'});
const EVENTS=Object.freeze({DIRECTIVE_ADMITTED:'DIRECTIVE_ADMITTED',DISPATCH_PLANNED:'DISPATCH_PLANNED',DISPATCH_ACCEPTED:'DISPATCH_ACCEPTED',RESULT_PENDING:'RESULT_PENDING',RESULT_PASS:'RESULT_PASS',RESULT_BLOCKED:'RESULT_BLOCKED',RESULT_FAILED:'RESULT_FAILED',STOP_ACKNOWLEDGED:'STOP_ACKNOWLEDGED',RETRY_ADMITTED:'RETRY_ADMITTED'});
const CAPABILITIES=Object.freeze({PROMPT_DISPATCH:'PROMPT_DISPATCH',JOB_CONTROL:'JOB_CONTROL',RESULT_OPEN:'RESULT_OPEN',PC_STATUS_POST:'PC_STATUS_POST',BACKUP_CREATE:'BACKUP_CREATE'});
const ACTION_CAPABILITY=Object.freeze({READ_AND_EXECUTE:CAPABILITIES.PROMPT_DISPATCH,RUN_SELECTED_ROLE:CAPABILITIES.PROMPT_DISPATCH,RUN_GROUP:CAPABILITIES.PROMPT_DISPATCH,REQUEST_STOP:CAPABILITIES.JOB_CONTROL,RETRY:CAPABILITIES.JOB_CONTROL,OPEN_RESULT:CAPABILITIES.RESULT_OPEN,POST_PC_STATUS:CAPABILITIES.PC_STATUS_POST,BACKUP_NOW:CAPABILITIES.BACKUP_CREATE});
const TRANSITIONS=Object.freeze({
 IDLE:{DIRECTIVE_ADMITTED:STATES.DIRECTIVE_READY},DIRECTIVE_READY:{DISPATCH_PLANNED:STATES.DISPATCHING},
 DISPATCHING:{DISPATCH_ACCEPTED:STATES.RUNNING,RESULT_BLOCKED:STATES.BLOCKED,RESULT_FAILED:STATES.FAILED,STOP_ACKNOWLEDGED:STATES.BLOCKED},
 RUNNING:{RESULT_PENDING:STATES.RESULT_WAITING,RESULT_PASS:STATES.COMPLETED,RESULT_BLOCKED:STATES.BLOCKED,RESULT_FAILED:STATES.FAILED,STOP_ACKNOWLEDGED:STATES.BLOCKED},
 RESULT_WAITING:{RESULT_PASS:STATES.COMPLETED,RESULT_BLOCKED:STATES.BLOCKED,RESULT_FAILED:STATES.FAILED,STOP_ACKNOWLEDGED:STATES.BLOCKED},
 BLOCKED:{RETRY_ADMITTED:STATES.DIRECTIVE_READY},FAILED:{RETRY_ADMITTED:STATES.DIRECTIVE_READY},COMPLETED:{}
});
module.exports={ACTIONS,STATES,EVENTS,CAPABILITIES,ACTION_CAPABILITY,TRANSITIONS};
