import fs from 'node:fs';
import assert from 'node:assert/strict';
const read=n=>JSON.parse(fs.readFileSync(new URL(`../${n}`,import.meta.url),'utf8'));
const m=read('AI_BUILD_DECISION_VIEWMODEL_V1.json');
const p=read('IMPLEMENTATION_PRIORITY_VIEW_V1.json');
const c=read('REUSABLE_NEW_BUILD_CANDIDATE_VIEW_V1.json');
const u=read('UNKNOWN_IMPLEMENTATION_GAPS_V1.json');
const f=read('fixtures/AI_BUILD_DECISION_FIXTURE_V1.json');
assert.equal(m.schema_version,'AI_BUILD_DECISION_VIEWMODEL_V1');
assert.deepEqual(Object.keys(m.graphs).sort(),['API','COMPONENT','DEPENDENCY','ENTITY','FEATURE','PAGE','STATE']);
assert.equal(m.critical_product_structure_coverage.coverage_percent,98.65);
assert.equal(m.critical_product_structure_coverage.unknown_count,1);
assert.equal(m.unknowns.length,1);
assert.equal(m.unknowns[0].candidate_mode,'DEFER_UNTIL_EVIDENCE');
assert.equal(m.decision_contract.no_evidence_no_feature_generation,true);
assert.equal(m.decision_contract.unknown_never_promoted_to_build_ready,true);
assert.equal(m.candidate_summary.reusable_existing_count,9);
assert.equal(m.candidate_summary.reuse_first_conditional_new_build_count,1);
assert.equal(m.candidate_summary.new_build_candidate_count,0);
assert.equal(m.candidate_summary.deferred_unknown_count,1);
assert.equal(p.counts.P0,8);
assert.equal(p.counts.P1,3);
assert.equal(c.direct_new_build_candidates.length,0);
assert.equal(c.conditional_new_build_candidates.length,1);
assert.equal(c.deferred_candidates.length,1);
assert.equal(u.unknown_count,1);
assert.equal(f.expected.graph_domain_count,7);
assert.equal(f.expected.critical_coverage_percent,98.65);
for (const x of m.implementation_units){ assert.ok(x.evidence_pointer); assert.ok(['OBSERVED','INFERRED','UNKNOWN'].includes(x.evidence_state)); assert.ok(['P0','P1','P2','P3'].includes(x.implementation_priority)); }
assert.equal(m.machine_readable_done_when.natural_language_interpretation_required,false);
console.log(JSON.stringify({status:'PASS',assertions:22,graph_domains:Object.keys(m.graphs).length,coverage:m.critical_product_structure_coverage.coverage_percent,unknowns:m.unknowns.length,reuse:m.candidate_summary.reusable_existing_count,conditional_new_build:m.candidate_summary.reuse_first_conditional_new_build_count,direct_new_build:m.candidate_summary.new_build_candidate_count,deferred:m.candidate_summary.deferred_unknown_count}));
