'use strict';
const crypto=require('node:crypto');
const REJECTION_REASONS=Object.freeze(['UNMAPPED_FIELD','PROVENANCE_REF_MISSING','EVIDENCE_REF_MISSING','SOURCE_VALUE_MISSING','TRANSFORMATION_ERROR','DUPLICATE_SOURCE_FIELD','RULE_VERSION_MISMATCH','SENSITIVE_VALUE_REJECTED']);
const SENSITIVE=/(password|secret|token|authorization|cookie|credential|private[_-]?key)/i;
class DAlignedAssemblerError extends Error{constructor(code,details={}){super(code);this.name='DAlignedAssemblerError';this.code=code;this.details=details;}}
const req=(ok,code,details={})=>{if(!ok)throw new DAlignedAssemblerError(code,details);};
const clone=v=>v===undefined?undefined:JSON.parse(JSON.stringify(v));
const text=v=>typeof v==='string'&&v.trim().length>0;
function stable(v){if(Array.isArray(v))return v.map(stable);if(v&&typeof v==='object')return Object.keys(v).sort().reduce((o,k)=>(o[k]=stable(v[k]),o),{});return v;}
const sha256=v=>crypto.createHash('sha256').update(JSON.stringify(stable(v))).digest('hex');
function scan(v,p='$'){if(Array.isArray(v))return v.forEach((x,i)=>scan(x,`${p}[${i}]`));if(!v||typeof v!=='object')return;for(const[k,x]of Object.entries(v)){req(!SENSITIVE.test(k),'SENSITIVE_VALUE_REJECTED',{path:`${p}.${k}`});scan(x,`${p}.${k}`);}}
function binding(b,n){req(b&&typeof b==='object','AUTHORITY_BINDING_REQUIRED',{n});req(typeof b.available==='boolean','AUTHORITY_AVAILABLE_REQUIRED',{n});req(['FIXTURE','EXACT_REMOTE_AUTHORITY','NOT_PUBLISHED'].includes(b.mode),'AUTHORITY_MODE_INVALID',{n});if(b.available){req(b.mode==='EXACT_REMOTE_AUTHORITY','AVAILABLE_AUTHORITY_MUST_BE_EXACT',{n});req(b.pointer&&typeof b.pointer==='object','AVAILABLE_AUTHORITY_POINTER_REQUIRED',{n});}}
function validateFixture(i){req(i&&typeof i==='object','INPUT_REQUIRED');scan(i);req(i.schema_version==='C4_D_ALIGNED_PACKAGE_FIXTURE_V1','SCHEMA_VERSION_INVALID');req(i.fixture===true,'FIXTURE_FLAG_REQUIRED');req(text(i.domain_scope),'DOMAIN_SCOPE_REQUIRED');req(text(i.classification_version),'CLASSIFICATION_VERSION_REQUIRED');req(text(i.mapping_version),'MAPPING_VERSION_REQUIRED');for(const n of ['c2_source_lineage','c3_mapping_rules','b1_source_package','d1_contract_set'])binding(i.authority_bindings?.[n],n);req(Array.isArray(i.source_lineage)&&i.source_lineage.length,'SOURCE_LINEAGE_REQUIRED');req(Array.isArray(i.mapping_rules),'MAPPING_RULES_REQUIRED');req(Array.isArray(i.relationship_templates),'RELATIONSHIP_TEMPLATES_REQUIRED');return clone(i);}
function upstreamRejectionReason(e){if(e.validation_status!=='REJECTED')return null;return({UNMAPPED_FIELD:'UNMAPPED_FIELD',FORMAT_ERROR:'TRANSFORMATION_ERROR',MISSING_REQUIRED_VALUE:'SOURCE_VALUE_MISSING',SOURCE_VALUE_MISSING:'SOURCE_VALUE_MISSING',TRANSFORMATION_ERROR:'TRANSFORMATION_ERROR',PROVENANCE_REF_MISSING:'PROVENANCE_REF_MISSING',EVIDENCE_REF_MISSING:'EVIDENCE_REF_MISSING',SENSITIVE_VALUE_REJECTED:'SENSITIVE_VALUE_REJECTED'})[e.rejection_reason]||'TRANSFORMATION_ERROR';}
function transformValue(v,r){if(r.operation==='IDENTITY')return clone(v);if(r.operation==='STRING_TRIM'){req(typeof v==='string','TRANSFORMATION_ERROR');return v.trim();}if(r.operation==='INTEGER'){const n=Number.parseInt(String(v),10);req(Number.isInteger(n)&&String(n)===String(v).trim(),'TRANSFORMATION_ERROR');return n;}if(r.operation==='NUMBER'){const n=Number(v);req(Number.isFinite(n),'TRANSFORMATION_ERROR');return n;}if(r.operation==='CODE_MAP'){req(r.code_map&&Object.prototype.hasOwnProperty.call(r.code_map,String(v)),'TRANSFORMATION_ERROR');return r.code_map[String(v)];}throw new DAlignedAssemblerError('RULE_OPERATION_INVALID');}
function reject(e,m,reason,r=null){req(REJECTION_REASONS.includes(reason),'REJECTION_REASON_INVALID',{reason});return{source_record_id:e.source_record_id,source_field:e.source_field,source_value:clone(e.source_value),transformation_rule_id:r?.transformation_rule_id??null,target_entity:r?.target_entity??null,target_field:r?.target_field??null,target_type:r?.target_type??null,transformed_value:null,provenance_ref:text(e.provenance_ref)?e.provenance_ref:'MISSING_PROVENANCE_REF',evidence_ref:text(e.evidence_ref)?e.evidence_ref:'MISSING_EVIDENCE_REF',validation_status:'REJECTED',rejection_reason:reason,mapping_version:m};}
const exact=i=>['c2_source_lineage','c3_mapping_rules','b1_source_package','d1_contract_set'].every(n=>i.authority_bindings[n].available);
function unresolved(i){const a=[];if(!i.authority_bindings.c2_source_lineage.available)a.push('C2_D_ALIGNED_SOURCE_LINEAGE_TERMINAL_NOT_PUBLISHED');if(!i.authority_bindings.c3_mapping_rules.available)a.push('C3_D_ALIGNED_FIELD_MAPPING_TERMINAL_NOT_PUBLISHED');if(!i.authority_bindings.b1_source_package.available)a.push('B1_NORMALIZED_DATASET_OR_RAW_ARTIFACT_MANIFEST_NOT_PUBLISHED');if(!i.authority_bindings.d1_contract_set.available)a.push('D1_REQUIRED_SCHEMA_MAPPING_VALIDATION_CONTRACT_SET_NOT_PUBLISHED');return a;}
function assemble(input){const i=validateFixture(input),rules=new Map(),transformed=[],rejected=[],seen=new Set(),actual=exact(i);for(const r of i.mapping_rules){req(r&&text(r.transformation_rule_id)&&text(r.source_field)&&text(r.target_entity)&&text(r.target_field)&&text(r.target_type)&&text(r.operation)&&text(r.mapping_version)&&text(r.target_authority),'RULE_FIELD_REQUIRED');req(r.mapping_version===i.mapping_version,'RULE_VERSION_MISMATCH');req(!rules.has(r.source_field),'DUPLICATE_MAPPING_RULE',{source_field:r.source_field});rules.set(r.source_field,r);}for(const e of i.source_lineage){req(e&&text(e.source_record_id)&&text(e.source_field)&&['VALID','REJECTED','PENDING_AUTHORITY'].includes(e.validation_status),'LINEAGE_INVALID');const k=`${e.source_record_id}::${e.source_field}`,r=rules.get(e.source_field)||null;if(seen.has(k)){rejected.push(reject(e,i.mapping_version,'DUPLICATE_SOURCE_FIELD',r));continue;}seen.add(k);if(SENSITIVE.test(e.source_field)){rejected.push(reject(e,i.mapping_version,'SENSITIVE_VALUE_REJECTED',r));continue;}if(!text(e.provenance_ref)){rejected.push(reject(e,i.mapping_version,'PROVENANCE_REF_MISSING',r));continue;}if(!text(e.evidence_ref)){rejected.push(reject(e,i.mapping_version,'EVIDENCE_REF_MISSING',r));continue;}const up=upstreamRejectionReason(e);if(up){rejected.push(reject(e,i.mapping_version,up,r));continue;}if(e.source_value===null||e.source_value===undefined||e.source_value===''){rejected.push(reject(e,i.mapping_version,'SOURCE_VALUE_MISSING',r));continue;}if(!r){rejected.push(reject(e,i.mapping_version,'UNMAPPED_FIELD'));continue;}try{transformed.push({source_record_id:e.source_record_id,source_field:e.source_field,source_value:clone(e.source_value),transformation_rule_id:r.transformation_rule_id,target_entity:r.target_entity,target_field:r.target_field,target_type:r.target_type,transformed_value:transformValue(e.source_value,r),provenance_ref:e.provenance_ref,evidence_ref:e.evidence_ref,validation_status:actual?'VALID':'PENDING_AUTHORITY',rejection_reason:null,mapping_version:i.mapping_version,target_authority:actual?'D1_EXACT_AUTHORITY':'FIXTURE_PLACEHOLDER_NOT_D_AUTHORITY'});}catch(_){rejected.push(reject(e,i.mapping_version,'TRANSFORMATION_ERROR',r));}}
transformed.sort((a,b)=>`${a.source_record_id}:${a.source_field}`.localeCompare(`${b.source_record_id}:${b.source_field}`));rejected.sort((a,b)=>`${a.source_record_id}:${a.source_field}`.localeCompare(`${b.source_record_id}:${b.source_field}`));const count=i.source_lineage.length;req(count===transformed.length+rejected.length,'SILENT_DROP_DETECTED');const packageId=`DTP-${sha256({domain:i.domain_scope,mapping:i.mapping_version,source:i.source_lineage}).slice(0,24)}`;const pkg={schema_version:'D_ALIGNED_TRANSFORMATION_PACKAGE_V1',package_id:packageId,domain_scope:i.domain_scope,package_mode:actual?'AUTHORITY_BOUND_CANDIDATE':'FIXTURE_ONLY',mapping_version:i.mapping_version,source_authority:clone(i.authority_bindings.b1_source_package),d_authority:clone(i.authority_bindings.d1_contract_set),transformed_fields:transformed,rejected_fields:rejected,accounting:{source_field_count:count,transformed_field_count:transformed.length,rejected_field_count:rejected.length,silent_drop_count:0,complete:true},d_acceptance_claim:false,d_canonical_db_write:false,source_digest:sha256({source_lineage:i.source_lineage,mapping_rules:i.mapping_rules})};
const entries=[...transformed.map(f=>({source_record_id:f.source_record_id,source_field:f.source_field,transformation_rule_id:f.transformation_rule_id,target_entity:f.target_entity,target_field:f.target_field,status:actual?'MAPPED':'PENDING_AUTHORITY',reason:actual?null:'FIXTURE_TARGET_NOT_D_AUTHORITY',provenance_ref:f.provenance_ref,evidence_ref:f.evidence_ref})),...rejected.map(f=>({source_record_id:f.source_record_id,source_field:f.source_field,transformation_rule_id:f.transformation_rule_id,target_entity:f.target_entity,target_field:f.target_field,status:'REJECTED',reason:f.rejection_reason,provenance_ref:f.provenance_ref,evidence_ref:f.evidence_ref}))].sort((a,b)=>`${a.source_record_id}:${a.source_field}`.localeCompare(`${b.source_record_id}:${b.source_field}`));const report={schema_version:'FIELD_MAPPING_REPORT_V1',report_id:`FMR-${sha256({packageId,entries}).slice(0,24)}`,mapping_version:i.mapping_version,package_id:packageId,entries,summary:{source_fields:count,mapped:actual?transformed.length:0,rejected:rejected.length,pending_authority:actual?0:transformed.length},unresolved_authority_inputs:unresolved(i),silent_drop_count:0,source_digest:sha256(entries)};
const groups=new Map();for(const f of transformed){const k=`${f.source_record_id}::${f.target_entity}`;if(!groups.has(k))groups.set(k,[]);groups.get(k).push(f);}const objects=[...groups.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([k,fs])=>{const [source_record_id,target_entity]=k.split('::'),candidate_fields={};for(const f of fs.sort((a,b)=>a.target_field.localeCompare(b.target_field)))candidate_fields[f.target_field]=clone(f.transformed_value);return{knowledge_object_id:`KCO-${sha256({source_record_id,target_entity,mapping:i.mapping_version}).slice(0,20)}`,candidate_status:actual?'PENDING_D1_REVIEW':'FIXTURE_CANDIDATE_ONLY',source_record_id,target_entity,candidate_fields,provenance_refs:[...new Set(fs.map(f=>f.provenance_ref))].sort(),evidence_refs:[...new Set(fs.map(f=>f.evidence_ref))].sort(),mapping_version:i.mapping_version};});const evidence_refs=[...new Set([...transformed,...rejected].map(f=>f.evidence_ref))].sort();const bundle={schema_version:'KNOWLEDGE_CANDIDATE_BUNDLE_V1',candidate_bundle_id:`KCB-${sha256({packageId,objects}).slice(0,24)}`,domain_scope:i.domain_scope,knowledge_objects:objects,evidence_refs,relationship_edges:[],classification_version:i.classification_version,validation_summary:{source_field_count:count,candidate_object_count:objects.length,rejected_field_count:rejected.length,silent_drop_count:0,provenance_ref_omission_count:0,evidence_ref_omission_count:0,authority_binding_complete:actual},candidate_only:true,d_acceptance_claim:false,source_digest:sha256({pkg,report})};return{transformation_package:pkg,field_mapping_report:report,knowledge_candidate_bundle:bundle,unresolved_authority_inputs:report.unresolved_authority_inputs,final_binding_ready:actual,fixture_contract_ready:true,silent_drop_count:0,d_acceptance_claim:false,d_canonical_db_write:false};}
module.exports={REJECTION_REASONS,DAlignedAssemblerError,validateFixture,transformValue,upstreamRejectionReason,assemble,sha256};
