import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {loadContracts,buildInitialViewState} from '../src/panel_prebuild.mjs';
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const contracts=loadContracts(ROOT);
const vm=contracts.SITE_ANALYZER_PANEL_VIEWMODEL_V1;
const si=contracts.SMART_INSPECTOR_CONTRACT_V1;
const tr=contracts.TRACE_DRAWER_CONTRACT_V1;
const bp=contracts.SUCCESSOR_UI_BOOTSTRAP_PLAN_V1;
assert.equal(vm.workflow.nodes.key,'node_id');
assert.equal(vm.live_session.selected_page_binding.primary_key,'selected_page_id');
assert.equal(vm.data_preview.selection_binding.inspector_bidirectional,true);
assert.deepEqual(si.correlation.required_bidirectional_links,['DOM_TO_FIELD','FIELD_TO_DOM','DOM_TO_NETWORK','NETWORK_TO_DOM']);
for(const c of ['ACTION','NETWORK','RESPONSE','CONSOLE','ERROR','RECIPE','ADAPTER']) assert.ok(tr.categories[c]);
assert.equal(bp.context_free_restore.chat_context_required,false);
assert.equal(bp.package_plan.runtime_transport,'consume Server/Analyzer result APIs or existing Runtime Bridge only');
const state=buildInitialViewState(contracts);
assert.equal(state.schema_version,'SITE_ANALYZER_PANEL_VIEW_STATE_V1');
assert.equal(state.active_inspector_tab,'DOM');
assert.ok(state.expanded_panels.includes('data_preview'));
console.log(JSON.stringify({status:'PASS',checks:12,schemas:Object.keys(contracts),view_state_schema:state.schema_version}));
