'use strict';

const MODEL_VERSION = 'stage4.instructionFileSeparator.v1';
const REFERENCE_TYPE = Object.freeze({ SOURCE_REFERENCE:'source_reference', DOWNLOAD_REFERENCE:'download_reference', LOCAL_FILE_REFERENCE:'local_file_reference', FILE_BATCH:'file_batch', UNKNOWN:'unknown' });
const REFERENCE_STATUS = Object.freeze({ GREEN:'GREEN', YELLOW:'YELLOW' });
const SEPARATION_STATUS = Object.freeze({ SEPARATED:'SEPARATED', COMMANDER_REVIEW_REQUIRED:'COMMANDER_REVIEW_REQUIRED' });
const URL_PATTERN = /\bhttps?:\/\/[^\s<>"'`]+/gi;
const SOURCE_FILE_BLOCK_PATTERN = /===\s*SOURCE_FILE_START\s*===[\s\S]*?===\s*SOURCE_FILE_END\s*===/gi;
const SOURCE_UNIT_BLOCK_PATTERN = /===\s*SOURCE_UNIT_START\s*===[\s\S]*?===\s*SOURCE_UNIT_END\s*===/gi;
const WINDOWS_ABSOLUTE_PATH_PATTERN = /\b[A-Za-z]:[\\/][^\s<>"'`|]+/g;
const PROJECT_RELATIVE_PATH_PATTERN = /(?:^|[\s("'`])((?:src|docs|tools|run|tests|fixtures|prompts|reports|generated|assembled|stage\d+_patch_requests|_CONSTITUTION_V2)\/[A-Za-z0-9._~@+\-()가-힣\[\]]+(?:\/[A-Za-z0-9._~@+\-()가-힣\[\]]+)*(?:\.[A-Za-z0-9]+)?)/g;
const SOURCE_PATH_LINE_PATTERN = /^\s*path:\s*(.+?)\s*$/im;

function normalizeText(value) { return typeof value === 'string' ? value.trim() : value === undefined || value === null ? '' : String(value).trim(); }
function posInt(value, fallback) { const n = Number(value); return Number.isInteger(n) && n > 0 ? n : fallback; }
function nonNegInt(value, fallback) { const n = Number(value); return Number.isInteger(n) && n >= 0 ? n : fallback; }
function normalizeIsoDate(value) { if (value instanceof Date && Number.isFinite(value.getTime())) return value.toISOString(); if (typeof value !== 'string' || !value.trim()) return ''; const parsed = new Date(value); return Number.isFinite(parsed.getTime()) ? parsed.toISOString() : ''; }
function hashString(value) { const text = normalizeText(value); let hash = 0; for (let i = 0; i < text.length; i += 1) hash = (hash * 31 + text.charCodeAt(i)) >>> 0; return hash.toString(36).padStart(7, '0'); }
function safeId(value) { return normalizeText(value).replace(/[^A-Za-z0-9_-]/g, '_').replace(/_+/g, '_').replace(/^_+|_+$/g, '') || 'id'; }
function toPlainSerializable(value, seen) { const s = seen || new WeakSet(); if (value === null || value === undefined) return value === undefined ? null : value; if (['string','number','boolean'].includes(typeof value)) return value; if (value instanceof Date) return Number.isFinite(value.getTime()) ? value.toISOString() : null; if (['function','symbol','bigint'].includes(typeof value)) return String(value); if (Array.isArray(value)) { if (s.has(value)) return '[Circular]'; s.add(value); return value.map((v) => toPlainSerializable(v, s)); } if (typeof value === 'object') { if (s.has(value)) return '[Circular]'; s.add(value); return Object.keys(value).reduce((r, k) => { r[k] = toPlainSerializable(value[k], s); return r; }, {}); } return String(value); }
function stableStringify(value) { if (value === null || typeof value !== 'object') return JSON.stringify(value); if (Array.isArray(value)) return `[${value.map((v) => stableStringify(v)).join(',')}]`; return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${stableStringify(value[key])}`).join(',')}}`; }
function uniquePlainObjects(list) { const seen = new Set(); const out = []; (Array.isArray(list) ? list : []).forEach((item) => { const plain = toPlainSerializable(item); const key = stableStringify(plain); if (!seen.has(key)) { seen.add(key); out.push(plain); } }); return out; }
function freezePlainRecord(record) { return Object.freeze(toPlainSerializable(record)); }
function isPlainObject(value) { return Object.prototype.toString.call(value) === '[object Object]'; }

function separateInstructionAndReferences(parseResult) {
  const input = normalizeParseResult(parseResult);
  const extracted = extractReferencesFromText(input.raw_text);
  const sourceRefs = uniqueReferences(normalizeInputs(input.source_references).map(createSourceReference).concat(extracted.source_references));
  const downloadRefs = uniqueReferences(normalizeInputs(input.download_references).map(createDownloadReference).concat(extracted.download_references));
  const fileRefs = uniqueReferences(normalizeInputs(input.local_file_references).map(createFileReference).concat(extracted.local_file_references));
  const batches = createFileBatchCandidates(fileRefs, downloadRefs);
  const warnings = buildWarnings(input.raw_text, sourceRefs.concat(downloadRefs, fileRefs), batches);
  const body = normalizeText(input.instruction_body) || removeReferenceRanges(input.raw_text, extracted.ranges);
  const yellow = warnings.length > 0;
  const result = { model_version:MODEL_VERSION, status: yellow ? SEPARATION_STATUS.COMMANDER_REVIEW_REQUIRED : SEPARATION_STATUS.SEPARATED, gate_status: yellow ? REFERENCE_STATUS.YELLOW : REFERENCE_STATUS.GREEN, needs_commander_review: yellow, review_reason: yellow ? warnings[0].code : '', instruction_body: body, original_text: input.raw_text, references:{ source_references:sourceRefs, download_references:downloadRefs, local_file_references:fileRefs, file_batch_candidates:batches }, counts:{ source_reference_count:sourceRefs.length, download_reference_count:downloadRefs.length, local_file_reference_count:fileRefs.length, file_batch_candidate_count:batches.length, total_reference_count: sourceRefs.length + downloadRefs.length + fileRefs.length }, warnings, metadata:toPlainSerializable(input.metadata || {}) };
  result.summary = summarizeInstructionReferences(result).message;
  return freezePlainRecord(result);
}
function createSourceReference(input) { const source = normalizeReferenceInput(input); const rawText = source.raw_text || source.value || source.text || source.block || ''; const targetPath = normalizeText(source.target_path || source.targetPath || source.path || extractPathFromSourceBlock(rawText)); const warnings = []; if (!rawText && !targetPath) warnings.push(refWarning('source_reference_empty','source reference has no text or target path.')); if (targetPath && isUnclearPath(targetPath)) warnings.push(refWarning('source_target_path_unclear','source reference target path is unclear.')); return freezePlainRecord({ reference_id: normalizeText(source.reference_id || source.referenceId || source.id) || createReferenceId('source', rawText || targetPath), reference_type:REFERENCE_TYPE.SOURCE_REFERENCE, source_kind: normalizeText(source.source_kind || source.sourceKind || inferSourceKind(rawText)) || 'TEXT_SOURCE', label: normalizeText(source.label || source.title || source.name), target_path:targetPath, normalized_target_path: normalizePath(targetPath), raw_text:rawText, status:warnings.length ? REFERENCE_STATUS.YELLOW : REFERENCE_STATUS.GREEN, warnings, metadata:toPlainSerializable(source.metadata || {}) }); }
function createFileReference(input) { const source = normalizeReferenceInput(input); const rawPath = normalizeText(source.path || source.file_path || source.filePath || source.local_path || source.localPath || source.value || source.text || source.raw_text); const warnings = []; if (!rawPath) warnings.push(refWarning('local_file_path_empty','local file reference path is empty.')); if (rawPath && isUnclearPath(rawPath)) warnings.push(refWarning('local_file_path_unclear','local file reference path is unclear.')); if (rawPath && hasBrokenPathSyntax(rawPath)) warnings.push(refWarning('local_file_path_syntax_yellow','local file reference path has syntax-risk characters or broken path shape.')); return freezePlainRecord({ reference_id: normalizeText(source.reference_id || source.referenceId || source.id) || createReferenceId('file', rawPath), reference_type:REFERENCE_TYPE.LOCAL_FILE_REFERENCE, file_kind: normalizeText(source.file_kind || source.fileKind || inferFileKind(rawPath)) || 'unknown_file', label: normalizeText(source.label || source.title || source.name), original_path:rawPath, normalized_path: normalizePath(rawPath), path_style: inferPathStyle(rawPath), target_path: normalizeText(source.target_path || source.targetPath), status:warnings.length ? REFERENCE_STATUS.YELLOW : REFERENCE_STATUS.GREEN, warnings, metadata:toPlainSerializable(source.metadata || {}) }); }
function createDownloadReference(input) { const source = normalizeReferenceInput(input); const url = normalizeText(source.url || source.href || source.link || source.download_url || source.downloadUrl || source.value || source.text || source.raw_text); const warnings = []; if (!url) warnings.push(refWarning('download_url_empty','download reference URL is empty.')); else if (!/^https?:\/\//i.test(url)) warnings.push(refWarning('download_url_not_http','download reference is not an http or https URL.')); return freezePlainRecord({ reference_id: normalizeText(source.reference_id || source.referenceId || source.id) || createReferenceId('download', url), reference_type:REFERENCE_TYPE.DOWNLOAD_REFERENCE, resource_kind: normalizeText(source.resource_kind || source.resourceKind || inferResourceKind(url)) || 'download_resource', label: normalizeText(source.label || source.title || source.name), url, suggested_filename: normalizeText(source.suggested_filename || source.suggestedFilename || inferFilenameFromUrl(url)), status:warnings.length ? REFERENCE_STATUS.YELLOW : REFERENCE_STATUS.GREEN, warnings, metadata:toPlainSerializable(source.metadata || {}) }); }
function summarizeInstructionReferences(result) { const refs = isPlainObject(result.references) ? result.references : {}; const source = Array.isArray(refs.source_references) ? refs.source_references : []; const download = Array.isArray(refs.download_references) ? refs.download_references : []; const local = Array.isArray(refs.local_file_references) ? refs.local_file_references : []; const batches = Array.isArray(refs.file_batch_candidates) ? refs.file_batch_candidates : []; const all = source.concat(download, local); const gate = all.some((ref) => ref.status === REFERENCE_STATUS.YELLOW) ? REFERENCE_STATUS.YELLOW : REFERENCE_STATUS.GREEN; return freezePlainRecord({ gate_status:gate, needs_commander_review: gate === REFERENCE_STATUS.YELLOW || Boolean(result.needs_commander_review), source_reference_count:source.length, download_reference_count:download.length, local_file_reference_count:local.length, file_batch_candidate_count:batches.length, total_reference_count:all.length, warning_count:Array.isArray(result.warnings) ? result.warnings.length : 0, message: all.length ? `Separated ${all.length} reference(s): ${source.length} source, ${download.length} download, ${local.length} local file. Gate=${gate}.` : 'No source, download, or local file references were separated.' }); }
function normalizeParseResult(parseResult) { if (typeof parseResult === 'string') return { raw_text:parseResult, instruction_body:'', source_references:[], download_references:[], local_file_references:[], metadata:{} }; const source = isPlainObject(parseResult) ? parseResult : {}; const body = isPlainObject(source.parse_result) ? source.parse_result : {}; return { raw_text: normalizeText(source.raw_text || source.rawText || source.text || source.instruction_text || source.instructionText || body.raw_text || body.rawText || body.text), instruction_body: normalizeText(source.instruction_body || source.instructionBody || body.instruction_body || body.instructionBody), source_references: collectFields(source, body, ['source_reference','sourceReference','source_references','sourceReferences','source_refs','sourceRefs','source_units','sourceUnits','lao_records','laoRecords']), download_references: collectFields(source, body, ['download_reference','downloadReference','download_references','downloadReferences','download_refs','downloadRefs','download_links','downloadLinks','urls','resources','taera_resources','taeraResources']), local_file_references: collectFields(source, body, ['local_file_reference','localFileReference','local_file_references','localFileReferences','file_reference','fileReference','file_references','fileReferences','file_refs','fileRefs','files','attachments']), metadata: source.metadata || body.metadata || {} }; }
function extractReferencesFromText(text) { const raw = normalizeText(text); const source_references = []; const download_references = []; const local_file_references = []; const ranges = []; collectMatches(raw, SOURCE_FILE_BLOCK_PATTERN).concat(collectMatches(raw, SOURCE_UNIT_BLOCK_PATTERN)).forEach((m) => { source_references.push(createSourceReference({ raw_text:m.value, path:extractPathFromSourceBlock(m.value), metadata:{ extracted_from_text:true } })); ranges.push(m.range); }); collectMatches(raw, URL_PATTERN).forEach((m) => { download_references.push(createDownloadReference({ url:stripTrailing(m.value), metadata:{ extracted_from_text:true } })); ranges.push(m.range); }); collectMatches(raw, WINDOWS_ABSOLUTE_PATH_PATTERN).forEach((m) => { local_file_references.push(createFileReference({ path:stripTrailing(m.value), metadata:{ extracted_from_text:true } })); ranges.push(m.range); }); collectProjectPaths(raw).forEach((m) => { local_file_references.push(createFileReference({ path:stripTrailing(m.value), metadata:{ extracted_from_text:true } })); ranges.push(m.range); }); return { source_references:uniqueReferences(source_references), download_references:uniqueReferences(download_references), local_file_references:uniqueReferences(local_file_references), ranges:mergeRanges(ranges) }; }
function createFileBatchCandidates(localRefs, downloadRefs) { const refs = uniqueReferences([].concat(localRefs || [], downloadRefs || [])); if (refs.length < 2) return []; const yellow = refs.some((ref) => ref.status === REFERENCE_STATUS.YELLOW); return [freezePlainRecord({ reference_id:createReferenceId('file_batch', refs.map((ref) => ref.reference_id).join('|')), reference_type:REFERENCE_TYPE.FILE_BATCH, file_batch_id:createReferenceId('batch', refs.map((ref) => ref.reference_id).join('|')), status: yellow ? 'REVIEW_REQUIRED' : 'READY', gate_status: yellow ? REFERENCE_STATUS.YELLOW : REFERENCE_STATUS.GREEN, reference_count:refs.length, references:refs.map((ref) => ({ reference_id:ref.reference_id, reference_type:ref.reference_type, status:ref.status })), warnings: yellow ? [refWarning('file_batch_contains_yellow_reference','FILE_BATCH candidate contains at least one YELLOW reference.')] : [] })]; }
function buildWarnings(rawText, refs, batches) { const warnings = []; if (!rawText && refs.length === 0) warnings.push(refWarning('instruction_and_references_empty','No instruction body or references were provided.')); refs.forEach((ref) => { if (ref.status === REFERENCE_STATUS.YELLOW) warnings.push(refWarning('reference_needs_review', `${ref.reference_type} needs review: ${ref.reference_id}`)); }); batches.forEach((batch) => { if (batch.gate_status === REFERENCE_STATUS.YELLOW) warnings.push(refWarning('file_batch_needs_review', `${batch.file_batch_id} contains YELLOW references.`)); }); return uniquePlainObjects(warnings); }
function collectFields(a,b,fields) { const out = []; [a,b].forEach((record) => fields.forEach((field) => { const v = record[field]; if (Array.isArray(v)) v.forEach((item) => out.push(item)); else if (v !== undefined && v !== null && v !== '') out.push(v); })); return out; }
function normalizeInputs(value) { return value === undefined || value === null || value === '' ? [] : Array.isArray(value) ? value : [value]; }
function normalizeReferenceInput(value) { return typeof value === 'string' || typeof value === 'number' ? { value:String(value), raw_text:String(value) } : isPlainObject(value) ? value : { value:String(value) }; }
function inferSourceKind(text) { const t = normalizeText(text).toUpperCase(); if (t.includes('SOURCE_FILE_START')) return 'SOURCE_FILE_BLOCK'; if (t.includes('SOURCE_UNIT_START')) return 'SOURCE_UNIT_BLOCK'; if (t.includes('LAO_RECORD')) return 'LAO_RECORD'; return 'TEXT_SOURCE'; }
function inferPathStyle(pathValue) { const text = normalizeText(pathValue); if (!text) return 'unknown'; if (/^[A-Za-z]:[\\/]/.test(text)) return 'windows_absolute'; if (/^\//.test(text)) return 'posix_absolute'; if (/^[A-Za-z0-9._~@+\-()가-힣\[\]]+(?:\/[A-Za-z0-9._~@+\-()가-힣\[\]]+)+/.test(text)) return 'project_relative'; return 'unknown'; }
function inferFileKind(pathValue) { const ext = extension(pathValue); const map = { '.js':'javascript_source', '.json':'json_file', '.md':'markdown_file', '.txt':'text_file', '.py':'python_file', '.bat':'windows_batch_file', '.ps1':'powershell_file', '.zip':'zip_file', '.docx':'word_document', '.pdf':'pdf_document' }; return map[ext] || (ext ? 'local_file' : 'unknown_file'); }
function inferResourceKind(url) { const ext = extension(inferFilenameFromUrl(url)); return { '.zip':'download_zip', '.js':'download_javascript_source', '.json':'download_json', '.md':'download_markdown', '.txt':'download_text', '.docx':'download_word_document', '.pdf':'download_pdf' }[ext] || 'download_resource'; }
function extractPathFromSourceBlock(blockText) { const match = normalizeText(blockText).match(SOURCE_PATH_LINE_PATTERN); return match ? normalizeText(match[1]) : ''; }
function collectMatches(text, regex) { const out = []; const pattern = new RegExp(regex.source, regex.flags.includes('g') ? regex.flags : `${regex.flags}g`); let match = pattern.exec(text); while (match) { out.push({ value:match[0], range:[match.index, match.index + match[0].length] }); match = pattern.exec(text); } return out; }
function collectProjectPaths(text) { const out = []; const pattern = new RegExp(PROJECT_RELATIVE_PATH_PATTERN.source, 'g'); let match = pattern.exec(text); while (match) { const start = match.index + match[0].indexOf(match[1]); out.push({ value:match[1], range:[start, start + match[1].length] }); match = pattern.exec(text); } return out; }
function removeReferenceRanges(text, ranges) { const raw = normalizeText(text); const merged = mergeRanges(ranges); let cursor = 0; const parts = []; merged.forEach((range) => { if (range[0] > cursor) parts.push(raw.slice(cursor, range[0])); cursor = Math.max(cursor, range[1]); }); if (cursor < raw.length) parts.push(raw.slice(cursor)); return parts.join(' ').replace(/[ \t]+/g, ' ').replace(/\n{3,}/g, '\n\n').trim(); }
function mergeRanges(ranges) { const sorted = (Array.isArray(ranges) ? ranges : []).filter((r) => Array.isArray(r) && r.length === 2).map((r) => [Number(r[0]), Number(r[1])]).filter((r) => Number.isFinite(r[0]) && Number.isFinite(r[1]) && r[1] >= r[0]).sort((a,b) => a[0]-b[0]); const out = []; sorted.forEach((r) => { const prev = out[out.length - 1]; if (!prev || r[0] > prev[1]) out.push(r); else prev[1] = Math.max(prev[1], r[1]); }); return out; }
function hasBrokenPathSyntax(value) { const text = normalizeText(value); return !text || /\.{3,}|TODO|TBD|나중|추후|생략/i.test(text) || /[<>|*?]/.test(text) || /^[A-Za-z]:[\\/]?$/.test(text) || /\\{3,}/.test(text); }
function isUnclearPath(value) { const text = normalizeText(value); return !text || /^(file|path|target|unknown|none)$/i.test(text) || /TODO|TBD|미정|불명확|unknown|placeholder/i.test(text); }
function normalizePath(value) { return stripTrailing(value).replace(/\\/g, '/').replace(/\/+/g, '/'); }
function stripTrailing(value) { return normalizeText(value).replace(/[),.;\]}]+$/g, ''); }
function inferFilenameFromUrl(url) { const clean = stripTrailing(url).split('#')[0].split('?')[0]; const parts = clean.split('/').filter(Boolean); return parts[parts.length - 1] || ''; }
function extension(value) { const filename = normalizeText(value).split('?')[0].split('#')[0].split(/[\\/]/).pop() || ''; const index = filename.lastIndexOf('.'); return index > 0 && index < filename.length - 1 ? filename.slice(index).toLowerCase() : ''; }
function refWarning(code, message) { return { code, status:REFERENCE_STATUS.YELLOW, message }; }
function createReferenceId(prefix, seed) { return `${safeId(prefix)}_ref_${hashString(seed || `${Date.now()}_${Math.random()}`)}`; }
function uniqueReferences(list) { const seen = new Set(); const out = []; (Array.isArray(list) ? list : []).forEach((ref) => { const plain = toPlainSerializable(ref); const key = `${plain.reference_type || REFERENCE_TYPE.UNKNOWN}:${plain.reference_id || stableStringify(plain)}`; if (!seen.has(key)) { seen.add(key); out.push(freezePlainRecord(plain)); } }); return out; }
module.exports = { REFERENCE_TYPE, separateInstructionAndReferences, createSourceReference, createFileReference, createDownloadReference, summarizeInstructionReferences };