'use strict';
const assert=require('node:assert/strict');
const fixture=require('./fixture_source_reinforcement_v1.json');
const {build,ENTITY_TYPES,LANES,CAPABILITIES}=require('./source_reinforcement.cjs');
const {receipt}=require('./secret_pii_redaction_validator.cjs');
let n=0; const eq=(a,b)=>{assert.deepEqual(a,b);n++}; const ok=v=>{assert.ok(v);n++};
const a=build(fixture), b=build(fixture);
eq(a.schema_version,'A5_REAL_ESTATE_ENTITY_FORM_ACTION_BINDING_SOURCE_RESULT_V1');
eq(a.decision_status,'PASS');
eq(a.entity_model.entities.length,10);
eq(a.entity_model.entity_types,ENTITY_TYPES);
eq(a.entity_model.entities.find(x=>x.entity_type==='listing').source_identifier.field,'listing_id');
eq(a.entity_model.entities.find(x=>x.entity_type==='contact').source_identifier.state,'WAITING_INPUT');
eq(a.entity_model.relationships.length,4);
eq(a.entity_model.source_ontology_policy.d_canonical_schema_defined,false);
eq(a.entity_model.entities.every(x=>x.lossless_extensions.unknown_source_fields_preserved===true),true);
eq(a.form_action_binding.chain,['form_field','validation_rule','request_field','response_result','ui_state']);
eq(a.form_action_binding.final_write_or_edit_submit,false);
eq(a.form_action_binding.bindings.find(x=>x.binding_id==='FAB-EDIT-STATUS').request_binding.state,'WAITING_INPUT');
eq(a.capability_validation_matrix.lanes,LANES);
eq(a.capability_validation_matrix.capabilities,CAPABILITIES);
eq(a.capability_validation_matrix.sites[0].capabilities.DELETE.support,'UNKNOWN');
eq(a.capability_validation_matrix.sites[1].capabilities.DELETE.support,'OBSERVED_UNSUPPORTED');
eq(a.validation.entity_type_count,10);
eq(a.validation.final_write_or_edit_submit_count,0);
eq(a.validation.d_canonical_definition_count,0);
eq(a.raw_secret_value_count,0);
eq(a.raw_pii_value_count,0);
eq(a.target_value_guessing,false);
eq(a.result_digest,b.result_digest);ok(/^[a-f0-9]{64}$/.test(a.result_digest));
const redaction=receipt({sessions:[{credential_reference:'credential_ref://site-a/account-1',cookie:'<REDACTED>'}],source:a});eq(redaction.status,'PASS');eq(redaction.credential_reference_only,true);eq(redaction.raw_secret_value_count,0);eq(redaction.raw_pii_value_count,0);
let secretCode=null;try{build({...fixture,extra:'Bearer SECRETSECRET'});}catch(e){secretCode=e.code;}eq(secretCode,'RAW_SECRET_VALUE_REJECTED');
let piiCode=null;try{receipt({customer_name:'홍길동'});}catch(e){piiCode=e.code;}eq(piiCode,'RAW_PII_VALUE_REJECTED');
let canonicalCode=null;try{build({...fixture,d_canonical_id:'D-001'});}catch(e){canonicalCode=e.code;}eq(canonicalCode,'D_CANONICAL_AUTHORITY_FORBIDDEN');
console.log(JSON.stringify({status:'PASS',fixture_replay_count:2,assertions:n,digest_run1:a.result_digest,digest_run2:b.result_digest,entity_type_count:a.validation.entity_type_count,form_binding_count:a.validation.form_binding_count,site_count:a.validation.site_count}));
