'use strict';
const assert=require('node:assert/strict');
const {closeWave3,groupTraffic,generalizeUrl}=require('./wave3_live_authority_closure.cjs');
let n=0; const eq=(a,b)=>{assert.deepEqual(a,b);n++}; const ok=(x)=>{assert.ok(x);n++};
const urls=[
'http://127.0.0.1:44475/','http://127.0.0.1:44475/assets/app.css','http://127.0.0.1:44475/assets/app.js','http://127.0.0.1:44475/assets/pixel.png','http://127.0.0.1:44475/frame','http://127.0.0.1:44475/api/items?page=1','http://127.0.0.1:44475/load-more','http://127.0.0.1:44475/infinite','http://127.0.0.1:44475/schema-drift?mode=v2','http://127.0.0.1:44475/detail/1','http://127.0.0.1:44475/detail/2','http://127.0.0.1:44475/popup','http://127.0.0.1:44475/download.csv','http://127.0.0.1:44475/api/items?page=1&run=1','http://127.0.0.1:44475/api/items?page=2&run=2','http://127.0.0.1:44475/load-more?run=3','http://127.0.0.1:44475/infinite?run=4','http://127.0.0.1:44475/schema-drift?mode=v2&run=5','http://127.0.0.1:44475/detail/1?run=6','http://127.0.0.1:44475/detail/2?run=7','http://127.0.0.1:44475/detail/3?run=8','http://127.0.0.1:44475/popup?run=9','http://127.0.0.1:44475/download.csv?run=10','http://127.0.0.1:44475/assets/app.css?run=11','http://127.0.0.1:44475/assets/list.js?run=12','http://127.0.0.1:44475/frame?run=dynamic','http://127.0.0.1:44475/list?page=1','http://127.0.0.1:44475/assets/app.css','http://127.0.0.1:44475/assets/list.js','http://127.0.0.1:44475/frame?from=list','http://127.0.0.1:44475/api/items?page=2'];
const reqs=urls.map((url,i)=>({sequence:i+1,request_id:'r'+i,url,method:'GET',resource_type:url.includes('/assets/')?'Fetch':url.includes('/list?')?'Document':'Fetch'}));
const bodyPathKind={'/':'text/html','/api/items':'application/json','/frame':'text/html','/load-more':'application/json','/infinite':'application/json','/schema-drift':'application/json','/detail/{id_2}':'text/html','/popup':'text/html','/download.csv':'text/csv','/assets/app.css':'text/css','/assets/list.js':'application/javascript','/list':'text/html'};
const bodies=[]; for(const r of reqs){const p=generalizeUrl(r.url).path_pattern;if(bodyPathKind[p]&&!bodies.some(b=>b.request_id===r.request_id)){bodies.push({request_id:r.request_id,url:r.url,mime_type:bodyPathKind[p],size_bytes:100,sha256:String(bodies.length).padStart(64,'a').slice(-64)})}}
const a3={schema_version:'A3_SITE_ANALYZER_WAVE2_LIVE_STREAM_HANDOFF_V1',status:'LIVE_STREAM_READY',actual_browser:'Chromium_144_REAL_CDP',stream_sha256:'s'.repeat(64),event_type_counts:{'network.request':32},network_request_stream:reqs,response_body_stream:bodies};
const a4={schemaVersion:'A4_WAVE2_ACTUAL_LIVE_STRUCTURE_HANDOFF_V2',actualLive:true,inputAuthority:{a3Head:'A3HEAD',a3StreamSha256:'s'.repeat(64)},repeatedRegions:[{itemCount:5}],fieldCandidates:[{name:'record_id',value:'1',strategy:'attribute',css:'article.item'},{name:'name',value:'Fixture Item 01',strategy:'text',css:'h2.name'},{name:'category',value:'odd',strategy:'text',css:'span.category'},{name:'value',value:'100',strategy:'text',css:'span.value'},{name:'detail_url',value:'/detail/1',strategy:'href',css:'a.detail'}],listDetailRelation:{navigationConfirmedByA3LiveStream:['/detail/1']},resultSha256:'r'.repeat(64)};
eq(generalizeUrl('http://x/detail/3?run=8').path_pattern,'/detail/{id_2}');
const groups=groupTraffic(a3); eq(groups.length,14); ok(groups.find(g=>g.path_pattern==='/api/items').request_parameters.find(p=>p.name==='page').required); eq(groups.find(g=>g.path_pattern==='/api/items').request_parameters.find(p=>p.name==='run').required,false);
const out=closeWave3({a3,a4,a3_head:'A3HEAD',a4_head:'A4HEAD'}); eq(out.extraction_mode.mode,'HYBRID'); eq(out.coverage.listed_network_requests,31); eq(out.coverage.advertised_network_requests,32); eq(out.coverage.endpoint_group_count,14); eq(out.coverage.json_endpoint_group_count,4); eq(out.response_schema.dom.fields.length,5); eq(out.identifier_map.primary_key.field,'record_id'); eq(out.a6_generator_input.status,'BLOCKED_EXACT_UPSTREAM_EVIDENCE_GAP'); ok(out.blockers.some(b=>b.code==='A3_NETWORK_REQUEST_STREAM_COUNT_MISMATCH')); ok(out.blockers.some(b=>b.code==='A3_RESPONSE_BODY_BYTES_OR_CONTENT_POINTER_NOT_PUBLISHED')); ok(out.blockers.some(b=>b.code==='A3_LIVE_SCHEMA_DRIFT_BASELINE_MISSING')); eq(out.schema_drift.observed_modes,['v2']); eq(out.raw_secret_value_count,0); ok(/^[0-9a-f]{64}$/.test(out.output_sha256));
const rerun=closeWave3({a3,a4,a3_head:'A3HEAD',a4_head:'A4HEAD'}); eq(JSON.stringify(rerun),JSON.stringify(out));
assert.throws(()=>closeWave3({a3:{...a3,status:'NO'},a4,a3_head:'A3HEAD',a4_head:'A4HEAD'}),/A3_ACTUAL_LIVE_STREAM_REQUIRED/);n++;
assert.throws(()=>closeWave3({a3,a4:{...a4,inputAuthority:{...a4.inputAuthority,a3Head:'OTHER'}},a3_head:'A3HEAD',a4_head:'A4HEAD'}),/A3_A4_AUTHORITY_MISMATCH/);n++;
console.log(JSON.stringify({status:'PASS',assertions:n,endpoint_groups:out.coverage.endpoint_group_count,json_groups:out.coverage.json_endpoint_group_count,mode:out.extraction_mode.mode,blockers:out.blockers.map(b=>b.code)}));
