'use strict';
const fs=require('node:fs'),path=require('node:path');
const EXACT=['C_RUNTIME_STATE_MACHINE','POINTER_RELAY_PARSER','REGISTRY_SEQUENCE_RESTART_EXPORT','RESULT_WATCHER_RUNTIME_ADAPTER','REPEAT_COMMAND_RUNTIME','REPEAT_RELEASE_ADAPTER','C_REPEAT_NAMESPACE_ADAPTER','ACTUAL_CANDIDATE_BRIDGE_BINDING','WORK_CONTROL_EVENT_LOGGING','BACKGROUND_BROWSER_DISPATCH','UI_TRUTH_BRIDGE','UI_TRUTH_CSS','UI_TRUTH_RUNTIME','TARGET_PC_RUNTIME_LOCATOR_RESOLVER','EXACT_UI_LOAD_HOOK','EXACT_UI_ROLLBACK','FULL_OFFLINE_ACCEPTANCE_RUNNER_V2','RESOLVER_INTEGRATION_VERIFIER'];
const OUTPUT=['RC8_INSTALLER','EXPECTED_MANIFEST_BUNDLE_VERIFIER','FULL_COMPONENT_SMOKE','LAUNCHER_AND_INSTALL_ROLLBACK','TARGET_PC_ACCEPTANCE_RUNNER'];
const RUNTIME=new Set(['EXECUTABLE_RUNTIME','RUNTIME_ASSET']),NONRUNTIME=new Set(['EXECUTABLE_TOOL','EVIDENCE_ONLY']),OUTCLS=new Set(['EXECUTABLE_INSTALLER','EXECUTABLE_TOOL','EXECUTABLE_TEST','EXECUTABLE_RUNNER']);
function read(p){return JSON.parse(fs.readFileSync(p,'utf8'))}function hex(v,n){return typeof v==='string'&&new RegExp(`^[0-9a-f]{${n}}$`).test(v)}
function counts(a){const m=new Map;for(const x of a)m.set(x,(m.get(x)||0)+1);return m}function forbidden(p){return /(?:^|\/)(?:reports?|results?|pointers?|receipts?|schemas?|fixtures?)(?:\/|$)/i.test(String(p))}
function rows(m){return m.member_rows.map(r=>Object.fromEntries(m.member_fields.map((f,i)=>[f,r[i]])))}function slots(m){return m.slot_rows.map(r=>Object.fromEntries(m.slot_fields.map((f,i)=>[f,r[i]])))}
function rowcheck(r,c,a){for(const k of ['component_class','owner','source_commit','source_path','blob_sha1','sha256','size_bytes','package_path','install_destination','load_order','classification','runtime_member']){a.n++;if(!(k in r))c.push(`MISSING_ROW_FIELD:${r.component_class||'UNKNOWN'}:${k}`)}
a.n++;if(!hex(r.source_commit,40))c.push(`INVALID_COMMIT:${r.component_class}`);a.n++;if(!hex(r.blob_sha1,40))c.push(`INVALID_BLOB_SHA1:${r.component_class}`);a.n++;if(!hex(r.sha256,64))c.push(`INVALID_SHA256:${r.component_class}`);a.n++;if(!Number.isSafeInteger(r.size_bytes)||r.size_bytes<=0)c.push(`INVALID_SIZE:${r.component_class}`);a.n++;if(!Number.isSafeInteger(r.load_order)||r.load_order<0)c.push(`INVALID_LOAD_ORDER:${r.component_class}`);
a.n++;if(!RUNTIME.has(r.classification)&&!NONRUNTIME.has(r.classification))c.push(`INVALID_CLASSIFICATION:${r.component_class}`);const e=RUNTIME.has(r.classification);a.n++;if(Boolean(r.runtime_member)!==e)c.push(`${r.classification==='EVIDENCE_ONLY'?'EVIDENCE_COUNTED_AS_RUNTIME':'RUNTIME_FLAG_MISMATCH'}:${r.component_class}`);a.n++;if(r.runtime_member&&forbidden(r.package_path))c.push(`REPORT_POINTER_RESULT_COUNTED_AS_RUNTIME:${r.component_class}`)}
function validateManifest(m){const c=[],a={n:0};for(const [id,ok] of [['CONTROL',m.control_id==='V1-C-MODE-6W-VALIDATION-CYCLE-002'],['WAVE',m.wave_id==='V1-C-MODE-6W-WAVE-018'],['SEQ',m.registry_sequence===18],['CMD',m.command_id==='C6W-W18-W1-RC8-EXPECTED-COMPONENT-MANIFEST-AUTHORITY'],['ROLE',m.role==='AUTOMATION-C-W1'],['KEY',m.result_key===`${m.directive_comment}00`],['TARGET',m.target_version==='5.10.2.4.2-rc8'],['BASE',m.baseline_version==='5.10.2.4.0']]){a.n++;if(!ok)c.push(`MANIFEST_${id}_MISMATCH`)}
const rs=rows(m),ss=slots(m);a.n++;if(rs.length!==EXACT.length)c.push(`EXACT_MEMBER_COUNT:${rs.length}`);a.n++;if(ss.length!==OUTPUT.length)c.push(`OUTPUT_SLOT_COUNT:${ss.length}`);for(const r of rs)rowcheck(r,c,a);
const cc=counts(rs.map(x=>x.component_class));for(const x of EXACT){a.n++;const n=cc.get(x)||0;if(!n)c.push(`MISSING_REQUIRED_COMPONENT_CLASS:${x}`);else if(n>1)c.push(`DUPLICATE_COMPONENT_CLASS:${x}`)}
for(const [p,n]of counts(rs.map(x=>x.package_path))){a.n++;if(n>1)c.push(`DUPLICATE_PACKAGE_PATH:${p}`)}for(const [p,n]of counts(rs.filter(x=>x.runtime_meber).map(x=>x.install_destination))){a.n++;if(n>1)c.push(`DUPLICATE_INSTALL_DESTINATION_FOR_RUNTIME:${p}`)}
const sc=counts(ss.map(x=>x.component_class));for(const x of OUTPUT){a.n++;const n=sc.get(x)||0;if(!n)c.push(`MISSING_OUTPUT_SLOT:${x}`);else if(n>1)c.push(`DUPLICATE_OUTPUT_SLOT:${x}`)}
for(const s of ss){for(const k of ['owner','identity_status','required_package_path','install_destination','load_order','classification']){a.n++;if(!(k in s))c.push(`MISSING_SLOT_FIELD:${s.component_class}:${k}`)}a.n++;if(s.owner!=='AUTOMATION-C-W5')c.push(`INVALID_SLOT_OWNER:${s.component_class}`);a.n++;if(s.identity_status!=='PENDING_W5_CARRYOVER')c.push(`INVALID_SLOT_STATUS:${s.component_class}`);a.n++;if(!OUTCLS.has(s.classification))c.push(`INVALID_SLOT_CLASSIFICATION:${s.component_class}`)}
a.n++;if(m.assembly_status.authority_manifest_complete!==true)c.push('AUTHORITY_MANIFEST_NOT_COMPLETE');a.n++;if(m.assembly_status.offline_artifact_ready!==false)c.push('OFFLINE_ARTIFACT_PREMATURE_READY');return{pass:!c.length,codes:[...new Set(c)],assertion_count:a.n,rows:rs,slots:ss}}
function complete(m,f){const base=[...rows(m),...f.positive_output_rows];return base}
function mut(a,m){a=JSON.parse(JSON.stringify(a));if(m.remove_class)return a.filter(x=>x.component_class!==m.remove_class);if(m.duplicate_class){const x=JSON.parse(JSON.stringify(a.find(x=>x.component_class===m.duplicate_class)));x.package_path=m.new_package_path||x.package_path;a.push(x);return a}if(m.set_runtime_member){a.find(x=>x.component_class===m.set_runtime_member.component_class).runtime_member=m.set_runtime_member.value;return a}throw Error('UNKNOWN_MUTATION')}
function validateComplete(a){const c=[],x={n:0},need=[...EXACT,...OUTPUT],cc=counts(a.map(x=>x.component_class));for(const x of need){x.n++;const n=cc.get(x)||0;if(!n)c.push(`MISSING_REQUIRED_COMPONENT_CLASS:${x}`);else if(n>1)c.push(`DUPLICATE_COMPONENT_CLASS:${x}`)}
for(const r of a){if(EXACT.includes(r.component_class))rowcheck(r,c,x);else{for(const k of ['source_commit','source_path','blob_sha1','sha256','size_bytes','package_path','install_destination','load_order','classification','runtime_member']){x.n++;if(!(k in r))c.push(`MISSING_ROW_FIELD:${r.component_class}:${k}`)}x.n++;if(!hex(r.source_commit,40))c.push(`INVALID_COMMIT:${r.component_class}`);x.n++;if(!hex(r.blob_sha1,40))c.push(`INVALID_BLOB_SHA1:${r.component_class}`);x.n++;if(!hex(r.sha256,64))c.push(`INVALID_SHA256:${r.component_class}`);x.n++;if(!Number.isSafeInteger(r.size_bytes)||r.size_bytes<=0)c.push(`INVALID_SIZE:${r.component_class}`);x.n++;if(!OUTCLS.has(r.classification))c.push(`INVALID_CLASSIFICATION:${r.component_class}`);x.n++;if(r.runtime_member!==false)c.push(`OUTPUT_CLASS_COUNTED_AS_RUNTIME:${r.component_class}`)}}
for(const [p,n]of counts(a.map(x=>x.package_path))){x.n++;if(n>1)c.push(`DUPLICATE_PACKAGE_PATH:${p}`)}return{pass:!c.length,codes:[...new Set(c)],assertion_count:x.n}}
function fixtures(m,f){const b=complete(m,f),p=validateComplete(b),neg=f.negative_cases.map(t=>{const r=validateComplete(mut(b,t.mutation)),missing=t.expected_codes.filter(x=>!r.codes.includes(x));return{id:t.id,actual:r.pass?'PASS':'FAIL_CLOSED',codes:r.codes,missing_expected_codes:missing,fixture_pass:!r.pass&&!missing.length,assertion_count:r.assertion_count}});return{positive:{actual:p.pass?'PASS':'FAIL_CLOSED',codes:p.codes,fixture_pass:p.pass,assertion_count:p.assertion_count},negatives:neg,pass:p.pass&&neg.every(x=>x.fixture_pass),assertion_count:p.assertion_count+neg.reduce((s,x)=>s+x.assertion_count+1,0)}}
function args(v){const o={};for(let i=0;i<v.length;i+=2)o[v[i]]=v[i+1];for(const k of ['--manifest','--assembly-map','--fixture','--receipt'])if(!o[k])throw Error('ARGS_REQUIRED');return o}
function main(){const a=args(process.argv.slice(2)),m=read(a['--manifest']),am=read(a['--assembly-map']),f=read(a['--fixture']),mr=validateManifest(m),fr=fixtures(m,f),ac={manifest_path_match:am.manifest_path==='RC8_EXPECTED_COMPONENT_MANIFEST_V2.json',exact_classes_match:JSON.stringify(am.exact_classes)===JSON.stringify(m.required_exact_component_classes),output_slots_match:JSON.stringify(am.output_slots)===JSON.stringify(m.required_output_component_classes),consumers_complete:['AUTOMATION-BÕÕÍIË	ÐUUÓPUSÓ‹PËUÌ‰Ë	ÐUUÓPUSÓ‹PËUÍ	Ë	ÐUUÓPUSÓ‹PËUÍ‰×K™]™\žJO˜[K˜ÛÛœÝ[Y\œËš[˜ÛY\Ê
JKÙ™›[™WØXØÙ\[˜ÙWØÛÜÙY˜[K›Ù™›[™WØ\Y˜XÝØXØÙ\[˜ÙWØ[ÝÙYOOY˜[Ù_K\ÜÏ[\‹œ\ÜÉ‰™œ‹œ\ÜÉ‰“Øš™XÝ˜[Y\ÊXÊK™]™\žJ›ÛÛX[ŠNÂ˜ÛÛœÝ^ÜØÚ[XWÝ™\œÚ[ÛŽ‰ÔÎÑVPÕQÐÓÓTÓ‘S•ÓPS’Q‘TÕÕSQUSÓ—Ô‘PÑRTÕŒIËÝ]\Îœ\ÜÏÉÔTÔ×ÓPS’Q‘TÕÐUUÔ’UWÕÍWÓÕUU×ÔS‘S‘ÉÎ‰ÑRSÓPS’Q‘TÕÐUUÔ’UIËÛÛ›ÛÚY›K˜ÛÛ›ÛÚYØ]™WÚY›KØ]™WÚY™\Ý[ÚÙ^N›Kœ™\Ý[ÚÙ^KX[šY™\ÝÝ˜[Y][ÛŽžÜ\ÜÎ›\‹œ\ÜËÛÙ\Î›\‹˜ÛÙ\Ë\ÜÙ\[Û—ØÛÝ[›\‹˜\ÜÙ\[Û—ØÛÝ[K\ÜÙ[X›WØÚXÚÜÎ˜XËš^\™WØ[™N™œ‹ÛÝ[Î›K˜ÛÝ[Ë™\]Z\™YÝÍWÛÝ]]ÜÛÝ×Ü[™[™Î“ÕUU]]Üš]WÛX[šY™\ÝÜ\ÜÎœ\ÜËÙ™›[™WØ\Y˜XÝÜ™XYN™˜[ÙK˜ÎØØ[™Y]WØXØÙ\Y™˜[ÙK\™Ù]Ü×Ù^XÝ][Û—Ü\™›Ü›YY™˜[ÙK\™Ù]Ü×Ü\Ü×ØÛZ[YY™˜[ÙK\ÜÙ\[Û—ØÛÝ[›\‹˜\ÜÙ\[Û—ØÛÝ[
Ùœ‹˜\ÜÙ\[Û—ØÛÝ[
ÓØš™XÝšÙ^\ÊXÊK›[™Ý˜Z[\™WØÛÝ[œ\ÜÏÌŒK›ÙXÝ[ÛŽ™˜[ÙK™XYN™˜[ÙKY\™ÙN™˜[Ù_NÙœËÜš]Qš[TÞ[˜ÊVÉËK\™XÙZ\	×K”ÓÓ‹œÝš[™ÚYžJ‹[ŠJÉ×‰ÊNØÛÛœÛÛK›ÙÊ”ÓÓ‹œÝš[™ÚYžJ‹[ŠJNÚYŠ\\ÜÊ\›ØÙ\ÜË™^]ÛÙOL_BšYŠ™\]Z\™K›XZ[OO[[Ù[J[XZ[Š
NÛ[Ù[K™^ÜÏ^Ý˜[Y]SX[šY™\Ý˜[Y]PÛÛ\]Kš^\™\ÏNÂ