import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import {spawn} from 'node:child_process';
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';

const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const records=Array.from({length:10},(_,i)=>({id:i+1,name:`Fixture Item ${String(i+1).padStart(2,'0')}`,category:i%2?'even':'odd',value:(i+1)*100}));
const fixtureHtml=`<!doctype html><html><head><meta charset="utf-8"><title>Wave3 Fixture</title><style>body{height:1600px}.item{padding:8px;border:1px solid #ddd;margin:4px}</style></head><body><main id="records">${records.slice(0,5).map(r=>`<article class="item" data-record-id="${r.id}" data-source-request-id="req-items"><h2 class="name">${r.name}</h2><span class="category">${r.category}</span><span class="value">${r.value}</span><a class="detail" href="/detail/${r.id}">Detail</a></article>`).join('')}</main><button id="add-dynamic">Add dynamic</button><a id="open-popup" href="/popup" target="_blank">Popup</a><iframe id="child" src="/frame"></iframe><script>fetch('/api/items?page=1').then(r=>r.json()).then(x=>window.__api=x);document.querySelector('#add-dynamic').onclick=()=>{const a=document.createElement('article');a.className='item';a.dataset.recordId='11';a.dataset.sourceRequestId='req-items';a.innerHTML='<h2 class="name">Dynamic Item</h2><span class="category">odd</span><span class="value">1100</span><a class="detail" href="/detail/11">Detail</a>';document.querySelector('#records').append(a)};</script></body></html>`;
const server=http.createServer((req,res)=>{const u=new URL(req.url,'http://x');if(u.pathname==='/fixture/list'){res.setHeader('content-type','text/html');return res.end(fixtureHtml);}if(u.pathname==='/api/items'){res.setHeader('content-type','application/json');return res.end(JSON.stringify({records,next_page:null}));}if(u.pathname==='/frame'){res.setHeader('content-type','text/html');return res.end('<html><body><button class="frame-button">Frame Button</button></body></html>');}if(u.pathname==='/popup'){res.setHeader('content-type','text/html');return res.end(`<html><body>Popup<script>window.opener?.postMessage({type:'fixture-popup-ready',url:location.href},'*')</script></body></html>`);}if(u.pathname.startsWith('/detail/')){res.setHeader('content-type','text/html');return res.end('<html><body>detail</body></html>');}let p=path.join(ROOT,u.pathname.replace(/^\//,''));if(u.pathname==='/')p=path.join(ROOT,'ui/index.html');if(fs.existsSync(p)&&fs.statSync(p).isFile()){if(p.endsWith('.mjs'))res.setHeader('content-type','text/javascript');if(p.endsWith('.html'))res.setHeader('content-type','text/html');return fs.createReadStream(p).pipe(res);}res.statusCode=404;res.end('not found');});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const {port}=server.address();const origin=`http://127.0.0.1:${port}`;
const debugPort=31000+Math.floor(Math.random()*2000);const userData=fs.mkdtempSync(path.join(os.tmpdir(),'b2-wave3-chrome-'));
const chrome=spawn('/usr/bin/chromium',['--headless=new','--no-sandbox','--disable-gpu',`--remote-debugging-port=${debugPort}`,`--user-data-dir=${userData}`,'about:blank'],{stdio:['ignore','ignore','pipe']});
let stderr='';chrome.stderr.on('data',d=>stderr+=d);
async function json(url,opts){for(let i=0;i<80;i++){try{const r=await fetch(url,opts);if(r.ok)return r.json();}catch{}await sleep(100);}throw new Error(`fetch timeout ${url} ${stderr}`);}
await json(`http://127.0.0.1:${debugPort}/json/version`);
let nextId=1;
class CDP{constructor(ws){this.ws=new WebSocket(ws);this.pending=new Map();this.events=[];this.handlers=[];}async open(){await new Promise((r,j)=>{this.ws.onopen=r;this.ws.onerror=j});this.ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){const p=this.pending.get(m.id);if(p){this.pending.delete(m.id);m.error?p.reject(new Error(m.error.message)):p.resolve(m.result);}}else{this.events.push(m);for(const h of this.handlers)h(m);}};}send(method,params={}){const id=nextId++;this.ws.send(JSON.stringify({id,method,params}));return new Promise((resolve,reject)=>this.pending.set(id,{resolve,reject}));}on(fn){this.handlers.push(fn);}close(){this.ws.close();}}
async function createTarget(mode){const t=await json(`http://127.0.0.1:${debugPort}/json/new?about:blank`,{method:'PUT'});const c=new CDP(t.webSocketDebuggerUrl);await c.open();await c.send('Page.enable');await c.send('Runtime.enable');await c.send('Network.enable');const net=[];const resp=[];c.on(m=>{if(m.method==='Network.requestWillBeSent')net.push(m.params);if(m.method==='Network.responseReceived')resp.push(m.params);});await c.send('Page.navigate',{url:`${origin}/ui/index.html?mode=${mode}`});for(let i=0;i<100;i++){const r=await c.send('Runtime.evaluate',{expression:`document.documentElement.dataset.b2Ready==='true'`,returnByValue:true});if(r.result.value)break;await sleep(50);}await c.send('Runtime.evaluate',{expression:`(()=>{const c=new MessageChannel();window.__b2Host=c.port1;window.__b2Out=[];c.port1.onmessage=e=>window.__b2Out.push(e.data);c.port1.start();window.postMessage({type:'YOLLA_ANALYZER_RUNTIME_PORT'},'*',[c.port2]);return true})()`,returnByValue:true});await sleep(150);
for(let i=0;i<80&&!net.some(x=>x.request.url.includes('/api/items'));i++) await sleep(50);
const apiReq=net.find(x=>x.request.url.includes('/api/items'));
assert.ok(apiReq,'actual CDP API request missing');const apiResp=resp.find(x=>x.requestId===apiReq.requestId);assert.ok(apiResp,'actual CDP API response missing');
const send=async(topic,payload,seq)=>c.send('Runtime.evaluate',{expression:`window.__b2Host.postMessage(${JSON.stringify({topic,payload,sequence:seq,sessionId:'wave3-host',source:'integration-test'})})`});let seq=1;
await send('analyzer:browser-state',{url:`${origin}/fixture/list`,title:'Wave3 Fixture',connected:true},seq++);
await send('analyzer:a3-event',{type:'network.request',request_id:apiReq.requestId,sequence:1,url:apiReq.request.url,method:apiReq.request.method,resource_type:apiReq.type,cdp_actual:true},seq++);
await send('analyzer:a3-event',{type:'network.response',request_id:apiReq.requestId,url:apiReq.request.url,status:apiResp.response.status,mime_type:apiResp.response.mimeType,cdp_actual:true},seq++);
const body=await c.send('Network.getResponseBody',{requestId:apiReq.requestId});await send('analyzer:a3-event',{type:'network.response_body',request_id:apiReq.requestId,url:apiReq.request.url,size_bytes:body.body.length,sha256:'actual-runtime-body'},seq++);
await send('analyzer:a3-event',{type:'dom.snapshot',url:`${origin}/fixture/list`,node_count:46,sha256:'actual-runtime-dom'},seq++);
await send('analyzer:a3-event',{type:'page.frame',child_frame_count:1},seq++);
await send('analyzer:a4-candidates',{repeatedRegions:[{id:'repeat-items',semanticLocator:'article.item',itemCount:5,confidence:.99}],fieldCandidates:[{id:'f-name',name:'name',css:'h2.name',networkRequestId:apiReq.requestId},{id:'f-category',name:'category',css:'span.category',networkRequestId:apiReq.requestId},{id:'f-value',name:'value',css:'span.value',networkRequestId:apiReq.requestId},{id:'f-detail',name:'detail_url',css:'a.detail',networkRequestId:apiReq.requestId},{id:'f-id',name:'record_id',css:'article.item',networkRequestId:apiReq.requestId}],locatorCandidates:[{id:'l-name',fieldId:'f-name',locator:'h2.name'},{id:'l-value',fieldId:'f-value',locator:'span.value'},{id:'l-detail',fieldId:'f-detail',locator:'a.detail'},{id:'l-category',fieldId:'f-category',locator:'span.category'},{id:'l-id',fieldId:'f-id',locator:'article.item'}],pagination:{detected:true,type:'NEXT',locator:'#next-page'},highlightPayload:{highlights:[{kind:'repeated-region',locator:'article.item'},{kind:'field',locator:'h2.name'}]}},seq++);
await send('analyzer:a5-inference',{status:'CONSUMER_CONTRACT_BOUND',mode_decision:'HYBRID',endpoint_groups:[{id:'items',url_pattern:'/api/items',method:'GET'}],response_schemas:[{id:'items-schema',fields:['id','name','category','value']}],identifier_relations:[{field:'name',request_id:apiReq.requestId},{field:'value',request_id:apiReq.requestId}],authority:{pointer_blob:'5cd7ab3b08d65f52895beeb62904277a5075aa53'}},seq++);
await send('analyzer:b3-workflow',{authority:{head:'31162d67eb474e7958e9a5591d87dc26bf3c307a',pointer_blob:'6f28e3c20b8a3b901ecac7933a215dd0c75f0e2f',action_log_blob:'f5715fee2d537535220af97c3723af1c3e148702'},steps:[{id:'wave3-action-0001',label:'input apartment',type:'input'},{id:'wave3-action-0002',label:'select seoul',type:'select'},{id:'wave3-action-0003',label:'click search',type:'click'},{id:'wave3-action-0004',label:'scroll 700',type:'scroll'},{id:'wave3-action-0005',label:'click route',type:'click'},{id:'wave3-action-0006',label:'navigate detail',type:'navigation'},{id:'wave3-action-0007',label:'click details',type:'click'},{id:'wave3-action-0008',label:'popup',type:'popup'},{id:'wave3-action-0009',label:'iframe details-frame',type:'iframe'},{id:'wave3-action-0010',label:'click frame-load',type:'click'}]},seq++);
await send('analyzer:b5-preview',{authority:{head:'589a8074f3844bb2d8192e4b1e876484030023d1',pointer_blob:'41597993e2dbb97a9d4d9b310b9e15769843db64',evidence_blob:'cd0fbb144e47ed955ff1a60eb0600844bd667af5'},columns:[{name:'id'},{name:'item_name'},{name:'edited_value'}],records:records.map((r,i)=>({data:{id:r.id,item_name:r.name,edited_value:i===4?5550:r.value},source:{rowPointer:{provider:'B-5',runId:'b5-wave2-live10-20260807-001',jsonPointer:`/records/${i}`,rowIndex:i},elementPointers:{id:{pointer:`/records/${i}/id`},name:{pointer:`/records/${i}/name`},value:{pointer:`/records/${i}/value`}}}}))},seq++);await sleep(150);
await c.send('Runtime.evaluate',{expression:`document.querySelector('#picker').click(); const w=document.querySelector('#browser').contentWindow; const el=w.document.querySelector('h2.name'); el.dispatchEvent(new w.MouseEvent('click',{bubbles:true,cancelable:true}));`,awaitPromise:true});await sleep(100);
const domToNet=(await c.send('Runtime.evaluate',{expression:`({selection:window.b2Wave3.state().selection,networkText:document.querySelector('#network').innerText})`,returnByValue:true})).result.value;
assert.equal(domToNet.selection.networkIds[0],apiReq.requestId);assert.equal(domToNet.selection.sourcePointer.jsonPointer,'/records/0');assert.match(domToNet.networkText,/200/);assert.match(domToNet.networkText,/application\/json/);assert.match(domToNet.networkText,/body/);
await c.send('Runtime.evaluate',{expression:`document.querySelector('#network .row').click()`});await sleep(50);const reverse=(await c.send('Runtime.evaluate',{expression:`window.b2Wave3.state().selection`,returnByValue:true})).result.value;assert.equal(reverse.selector,'h2.name');assert.deepEqual(reverse.fieldIds,['f-name']);
await c.send('Runtime.evaluate',{expression:`(()=>{const w=document.querySelector('#browser').contentWindow;w.document.querySelector('#add-dynamic').click();return true})()`});await c.send('Runtime.evaluate',{expression:`(()=>{const w=document.querySelector('#browser').contentWindow;w.document.querySelector('#open-popup').scrollIntoView({block:'center'});return w.scrollY})()`,returnByValue:true});await sleep(80);const popupPoint=(await c.send('Runtime.evaluate',{expression:`(()=>{const f=document.querySelector('#browser').getBoundingClientRect();const a=document.querySelector('#browser').contentWindow.document.querySelector('#open-popup').getBoundingClientRect();return {x:f.left+a.left+a.width/2,y:f.top+a.top+a.height/2}})()`,returnByValue:true})).result.value;await c.send('Input.dispatchMouseEvent',{type:'mousePressed',x:popupPoint.x,y:popupPoint.y,button:'left',clickCount:1});await c.send('Input.dispatchMouseEvent',{type:'mouseReleased',x:popupPoint.x,y:popupPoint.y,button:'left',clickCount:1});
let popupTarget=null;for(let i=0;i<60&&!popupTarget;i++){const targets=await json(`http://127.0.0.1:${debugPort}/json/list`);popupTarget=targets.find(t=>t.type==='page'&&t.url===`${origin}/popup`);if(!popupTarget)await sleep(50);}assert.ok(popupTarget,'actual Chromium popup target missing');await c.send('Runtime.evaluate',{expression:`document.querySelector('#browser').contentWindow.scrollTo(0,700)`});await send('analyzer:a3-event',{type:'page.popup',url:popupTarget.url,target_id:popupTarget.id,cdp_actual:true},seq++);await sleep(250);
const state=(await c.send('Runtime.evaluate',{expression:`window.b2Wave3.state()`,returnByValue:true})).result.value;
assert.equal(state.pass.DOM_NETWORK_SYNC,true);assert.equal(state.pass.ELEMENT_TO_FIELD_POINTER,true);assert.equal(state.pass.LIVE_PREVIEW,true);assert.equal(state.pass.DYNAMIC_DOM,true);assert.equal(state.pass.POPUP_IFRAME,true);assert.equal(state.preview.rows.length,10);assert.equal(state.preview.rows[4].data.edited_value,5550);assert.equal(state.selection.networkIds[0],apiReq.requestId);assert.equal(state.selection.sourcePointer.jsonPointer,'/records/0');assert.ok(state.browser.scrollY>0);assert.ok(state.browser.dynamicMutationCount>=1);assert.ok(state.browser.iframeCount>=1);assert.ok(state.browser.popupCount>=1);return {c,state,netCount:net.length,actualApiRequestId:apiReq.requestId,popupTargetId:popupTarget.id};}
let embedded,standalone;try{embedded=await createTarget('embedded');standalone=await createTarget('standalone');const k1=(await embedded.c.send('Runtime.evaluate',{expression:'window.b2Wave3.model.parityKey()',returnByValue:true})).result.value;const k2=(await standalone.c.send('Runtime.evaluate',{expression:'window.b2Wave3.model.parityKey()',returnByValue:true})).result.value;assert.equal(k1,k2);const receipt={status:'PASS',actualChromium:true,embeddedStandaloneParity:true,embeddedNetworkEvents:embedded.netCount,standaloneNetworkEvents:standalone.netCount,previewRows:embedded.state.preview.rows.length,dynamicMutationCount:embedded.state.browser.dynamicMutationCount,popupCount:embedded.state.browser.popupCount,iframeCount:embedded.state.browser.iframeCount,workflowStepCount:embedded.state.workflow.length,selection:embedded.state.selection,pass:{...embedded.state.pass,EMBEDDED_STANDALONE_PARITY:true}};console.log(JSON.stringify(receipt));}finally{embedded?.c.close();standalone?.c.close();chrome.kill('SIGTERM');server.close();try{fs.rmSync(userData,{recursive:true,force:true})}catch{}}
