'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const read=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const stable=v=>Array.isArray(v)?v.map(stable):v&&typeof v==='object'?Object.keys(v).sort().reduce((a,k)=>(a[k]=stable(v[k]),a),{}):v;
const sha=v=>crypto.createHash('sha256').update(JSON.stringify(stable(v))).digest('hex');
const unknown=(reason,evidence_pointer=null)=>({status:'UNKNOWN',reason,evidence_pointer});
function bestLocator(field){return [...(field.locator_candidates||[])].sort((a,b)=>(b.confidence||0)-(a.confidence||0))[0]||null;}
function compileBlueprint(inputs){
 const pages=inputs.page.nodes.map(p=>({page_id:p.page_id,page_role:p.page_role,url:p.url,title:p.title,evidence_status:p.evidence_status,confidence:p.confidence,components:inputs.component.nodes.filter(c=>c.page_id===p.page_id).map(c=>({component_id:c.component_id,component_role:c.component_role,locator:c.locator,evidence_status:c.evidence_status,confidence:c.confidence})),forms:inputs.form.forms.filter(f=>f.page_id===p.page_id).map(f=>({form_id:f.form_id,form_role:f.form_role,submit_locator:f.submit_locator,write_action:f.write_action,fields:f.fields.map(field=>({field_id:field.field_id,label:field.label,input_type:field.input_type,required:field.required,unit:field.unit||null,options:field.options||[],best_locator:bestLocator(field),canonical_candidate:inputs.mapping.canonical_fields.includes(field.field_id)?{status:'CANDIDATE',canonical_field:field.field_id,evidence:['A4_FIELD_ID_MATCH','CYCLE4_CANONICAL_FIELD'],confidence:Math.min(f.confidence||0.5,bestLocator(field)?.confidence||0.5)}:unknown('NO_EXACT_CANONICAL_FIELD_NAME_MATCH')}))})),states:inputs.state.regions.filter(s=>s.page_id===p.page_id).map(s=>({state_role:s.state_role,locator:s.locator,evidence_status:s.evidence_status,confidence:s.confidence}))}));
 return {schema_version:'AI_IMPLEMENTATION_BLUEPRINT_V1',compiler_version:'1.0.0-cycle5',pages,page_transitions:inputs.page.edges,feature_dependencies:{observed:[],candidates:[],policy:inputs.a5.feature,reason:'NO_CONCRETE_ACTION_ENDPOINT_BINDING_ROWS_IN_CYCLE5_INPUT'},api_bindings:[unknown('NO_CONCRETE_API_ENDPOINT_BINDING_ROWS_IN_CYCLE5_INPUT','A5_API_UI_BINDING_GRAPH_V1')],entity_relationships:[unknown('NO_CONCRETE_RESPONSE_ENTITY_PATH_ROWS_IN_CYCLE5_INPUT','A5_DATA_ENTITY_RELATIONSHIP_GRAPH_V1')],state_transition_policy:inputs.a5.state,authority_policy:{observed_relations_promoted:true,candidate_relations_preserve_confidence:true,business_rule_inference:'FORBIDDEN',unevidenced_fields:'UNKNOWN'},input_authority:inputs.manifest};
}
function compileAdapterSpec(inputs,blueprint){
 const rolePages=role=>blueprint.pages.filter(p=>p.page_role===role).map(p=>p.page_id);
 const makeMode=(mode,roles,contract)=>({mode,page_ids:roles.flatMap(rolePages),runtime:['Playwright','Crawlee'],shared_pipeline:inputs.multimode.shared_pipeline,allowed_actions:contract.allowed_actions||[],confirmation_policy:contract.confirmation_policy||null,blocked_final_actions:contract.blocked_final_actions||[],final_submit_execution:false});
 const fieldBindings=[]; for(const form of inputs.form.forms){for(const f of form.fields){const m=inputs.mapping.site_form_mapping[f.field_id];fieldBindings.push({form_id:form.form_id,field_id:f.field_id,canonical_field:inputs.mapping.canonical_fields.includes(f.field_id)?f.field_id:null,cycle4_site_form_field:m?.form_field||null,locator:bestLocator(f),binding_status:m?'CANDIDATE_COMPOSED':'UNKNOWN',confidence:m?Math.min(form.confidence||0.5,bestLocator(f)?.confidence||0.5):0,evidence:m?['A4_FORM_FIELD_OBSERVED','CYCLE4_CANONICAL_MAPPING']:['NO_CYCLE4_CANONICAL_MAPPING']});}}
 return {schema_version:'READ_WRITE_ADAPTER_SPEC_V1',adapter_version:'1.0.0-cycle5',modes:{READ:makeMode('READ',['PUBLIC_SEARCH','PUBLIC_LIST','PUBLIC_DETAIL'],{allowed_actions:['Navigate','Wait','Extract','Pagination']}),WRITE:makeMode('WRITE',['LISTING_CREATE'],{allowed_actions:['Navigate','Wait','Input','Select','UploadPreview'],blocked_final_actions:['submitCreate'],confirmation_policy:'USER_CONFIRM_REQUIRED'}),MY_LISTING:makeMode('MY_LISTING',['MY_LISTING_LIST','MY_LISTING_DETAIL'],{allowed_actions:['Navigate','Wait','Extract']}),EDIT:makeMode('EDIT',['LISTING_EDIT','LISTING_EXPIRE'],{allowed_actions:['Navigate','Wait','Input','Select','UploadPreview'],blocked_final_actions:['submitUpdate','delete','expire'],confirmation_policy:'USER_CONFIRM_REQUIRED'})},field_bindings:fieldBindings,api_execution:{status:'UNKNOWN',reason:'NO_CONCRETE_ACTION_TO_ENDPOINT_BINDING_ROWS',policy:inputs.a5.action_network},entity_execution:{status:'UNKNOWN',reason:'NO_CONCRETE_ENTITY_PATH_BINDINGS',policy:inputs.a5.entity},checkpoint_resume:{checkpoint_every_step:true,resume_from_failed_step:true,completed_step_reexecution:false,idempotency_key_fields:['command_id','mode','page_id','step_id','normalized_input']},final_action_policy:{submitCreate:'USER_CONFIRM_REQUIRED',submitUpdate:'USER_CONFIRM_REQUIRED',delete:'USER_CONFIRM_REQUIRED',expire:'USER_CONFIRM_REQUIRED'},source_blueprint_sha256:sha(blueprint)};
}
function replay(spec,{failStep=null,checkpoint=null}={}){
 const steps=[{step_id:'s01',page_id:'listing-create',kind:'Navigate'},{step_id:'s02',page_id:'listing-create',kind:'Wait'},{step_id:'s03',page_id:'listing-create',kind:'InputPreview'},{step_id:'s04',page_id:'listing-create',kind:'ConfirmationBoundary'}];
 let cp=checkpoint||{checkpoint_id:'cp-cycle5-fixture',last_completed_step:null,resume_from_step:0,completed:[],status:'RUNNING'};let executed=0,skipped=0;
 for(let i=cp.resume_from_step;i<steps.length;i++){const s=steps[i],key=sha({command_id:'cycle5-fixture',mode:'WRITE',page_id:s.page_id,step_id:s.step_id,normalized_input:s}); if(cp.completed.includes(key)){skipped++;continue;} if(failStep===s.step_id){cp.status='FAILED';cp.failed_step=s.step_id;cp.resume_from_step=i;return {checkpoint:cp,receipt:{status:'FAILED',failed_step:s.step_id,executed_step_count:executed,resume_from_step:i}};} cp.completed.push(key);cp.last_completed_step=s.step_id;cp.resume_from_step=i+1;executed++;}
 cp.status='COMPLETED';return {checkpoint:cp,receipt:{status:'PASS',executed_step_count:executed,skipped_completed_step_count:skipped,last_completed_step:cp.last_completed_step,resume_from_step:cp.resume_from_step,final_submit_execution:false}};
}
function main(){const root=process.argv[2]||'.';const inputs={manifest:read(path.join(root,'CYCLE5_INPUT_MANIFEST_V1.json')),page:read(path.join(root,'inputs/PAGE_GRAPH_V1.json')),component:read(path.join(root,'inputs/COMPONENT_ROLE_GRAPH_V1.json')),form:read(path.join(root,'inputs/FORM_FIELD_STRUCTURE_V1.json')),state:read(path.join(root,'inputs/UI_STATE_REGION_V1.json')),multimode:read(path.join(root,'inputs/CYCLE4_MULTIMODE.json')),mapping:read(path.join(root,'inputs/FIELD_MAPPING.json')),a5:read(path.join(root,'inputs/A5_POLICIES.json'))}; const bp=compileBlueprint(inputs),spec=compileAdapterSpec(inputs,bp);fs.mkdirSync(path.join(root,'generated'),{recursive:true});fs.writeFileSync(path.join(root,'generated/AI_IMPLEMENTATION_BLUEPRINT_V1.json'),JSON.stringify(bp,null,2)+'\n');fs.writeFileSync(path.join(root,'generated/READ_WRITE_ADAPTER_SPEC_V1.json'),JSON.stringify(spec,null,2)+'\n');const full1=replay(spec),full2=replay(spec),failed=replay(spec,{failStep:'s03'}),resumed=replay(spec,{checkpoint:JSON.parse(JSON.stringify(failed.checkpoint))});const receipt={schema_version:'A6_CYCLE5_COMPILER_VALIDATION_RECEIPT_V1',status:'PASS',fixture_compile_replay_1:'PASS',deterministic_replay_2_of_2:sha(full1)===sha(full2),blueprint_sha256:sha(bp),adapter_spec_sha256:sha(spec),full_replay_sha256:sha(full1),forced_failure_step:'s03',last_completed_before_failure:failed.checkpoint.last_completed_step,resume_from_step:failed.receipt.resume_from_step,resume_status:resumed.receipt.status,resume_executed_steps:resumed.receipt.executed_step_count,completed_steps_reexecuted:resumed.receipt.skipped_completed_step_count>0,final_submit_execution:false,unknown_api_preserved:bp.api_bindings[0].status==='UNKNOWN',unknown_entity_preserved:bp.entity_relationships[0].status==='UNKNOWN',business_rule_inference:'FORBIDDEN'};fs.writeFileSync(path.join(root,'artifacts/CYCLE5_VALIDATION_RECEIPT_V1.json'),JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify(receipt));}
module.exports={compileBlueprint,compileAdapterSpec,replay,sha};if(require.main===module)main();
