'use strict';
const fs=require('node:fs'); const path=require('node:path'); const crypto=require('node:crypto');
const MODES=new Set(['EVERY_X_MINUTES','AFTER_COMPLETION']);
function clone(v){return JSON.parse(JSON.stringify(v));}
function sha(v){return crypto.createHash('sha256').update(v).digest('hex');}
function req(v,n){if(typeof v!=='string'||!v.length)throw new Error(`INVALID_${n}`);return v;}
function targetKey(t){return `${t.group_id}\u0000${t.slot_id}`;}
function normalizeTargets(xs,now,mode){if(!Array.isArray(xs)||!xs.length)throw new Error('INVALID_TARGETS');const seen=new Set();return xs.map(x=>{const t={group_id:req(x.group_id,'GROUP_ID'),slot_id:req(x.slot_id,'SLOT_ID')};const k=targetKey(t);if(seen.has(k))throw new Error('DUPLICATE_TARGET');seen.add(k);return {...t,status:'ACTIVE',dispatch_count:0,awaiting_completion:false,last_dispatch_id:null,last_completed_dispatch_id:null,next_due_at_ms:mode==='EVERY_X_MINUTES'?now:null,updated_at_ms:now};});}
class RepeatCommandRuntime{
 constructor({statePath,now=()=>Date.now(),emit=()=>{}}={}){this.statePath=statePath||null;this.now=now;this.emit=emit;this.state={schema_version:'REPEAT_COMMAND_RUNTIME_STATE_V2',commands:{},receipts:[],work_control_log:[]};this._load();}
 _load(){if(!this.statePath||!fs.existsSync(this.statePath))return;const p=JSON.parse(fs.readFileSync(this.statePath,'utf8'));if(p.schema_version!=='REPEAT_COMMAND_RUNTIME_STATE_V2')throw new Error('STATE_SCHEMA_MISMATCH');this.state=p;}
 _persist(){if(!this.statePath)return;fs.mkdirSync(path.dirname(this.statePath),{recursive:true});const tmp=`${this.statePath}.tmp-${process.pid}`;fs.writeFileSync(tmp,`${JSON.stringify(this.state,null,2)}\n`);fs.renameSync(tmp,this.statePath);}
 _log(event,c,t,extra={}){this.state.work_control_log.push({at_ms:this.now(),event,command_id:c.command_id,role:c.role,group_id:t?.group_id||null,slot_id:t?.slot_id||null,...extra});}
 create(s){const id=req(s.command_id,'COMMAND_ID');if(this.state.commands[id]&&this.state.commands[id].status!=='END')throw new Error('ACTIVE_COMMAND_DUPLICATE');const role=req(s.role,'ROLE'),prompt=req(s.prompt,'PROMPT'),mode=req(s.trigger_mode,'TRIGGER_MODE');if(!MODES.has(mode))throw new Error('INVALID_TRIGGER_MODE');const interval=mode==='EVERY_X_MINUTES'?Number(s.interval_minutes):null;if(mode==='EVERY_X_MINUTES'&&(!Number.isFinite(interval)||interval<=0))throw new Error('INVALID_INTERVAL');const now=this.now();const c={command_id:id,role,prompt,prompt_byte_length:Buffer.byteLength(prompt),prompt_sha256:sha(Buffer.from(prompt)),trigger_mode:mode,interval_minutes:interval,status:'ACTIVE',created_at_ms:now,updated_at_ms:now,targets:normalizeTargets(s.targets,now,mode)};this.state.commands[id]=c;this._log('CREATED',c,null);this._persist();return clone(c);}
 get(id){return this.state.commands[id]?clone(this.state.commands[id]):null;}
 list(){return Object.values(this.state.commands).map(clone);}
 tick(at=this.now()){const out=[];for(const c of Object.values(this.state.commands)){if(c.status!=='ACTIVE')continue;for(const t of c.targets){if(t.status!=='ACTIVE'||t.awaiting_completion)continue;const due=c.trigger_mode==='EVERY_X_MINUTES'?at>=t.next_due_at_ms:t.dispatch_count===0;if(due)out.push(this._dispatch(c,t,at));}}if(out.length)this._persist();return out;}
 _dispatch(c,t,at){t.dispatch_count++;t.awaiting_completion=true;t.updated_at_ms=at;t.last_dispatch_id=`${c.command_id}:${t.group_id}:${t.slot_id}:${t.dispatch_count}`;if(c.trigger_mode==='EVERY_X_MINUTES')t.next_due_at_ms=at+c.interval_minutes*60000;const r={receipt_id:`receipt:${t.last_dispatch_id}`,dispatch_id:t.last_dispatch_id,command_id:c.command_id,role:c.role,group_id:t.group_id,slot_id:t.slot_id,prompt:c.prompt,prompt_byte_length:c.prompt_byte_length,prompt_sha256:c.prompt_sha256,dispatched_at_ms:at};this.state.receipts.push(r);this._log('DISPATCHED',c,t,{dispatch_id:r.dispatch_id});this.emit(clone(r));return clone(r);}
 complete({role,command_id:id,dispatch_id:did,status='REPORTED'}){const c=this.state.commands[id];if(!c)return{accepted:false,reason:'UNKNOWN_COMMAND'};if(role!==c.role)return{accepted:false,reason:'ROLE_MISMATCH'};if(!['REPORTED','END'].includes(status))return{accepted:false,reason:'INVALID_COMPLETION_STATUS'};const t=c.targets.find(x=>x.last_dispatch_id===did);if(!t||!t.awaiting_completion)return{accepted:false,reason:'DISPATCH_MISMATCH'};t.awaiting_completion=false;t.last_completed_dispatch_id=did;t.updated_at_ms=this.now();if(status==='END'){t.status='END';t.next_due_at_ms=null;}else if(c.trigger_mode==='AFTER_COMPLETION'){t.next_due_at_ms=t.updated_at_ms;}this._log(status==='END'?'TARGET_END':'COMPLETED',c,t,{dispatch_id:did});if(c.targets.every(x=>x.status==='END'))c.status='END';c.updated_at_ms=t.updated_at_ms;this._persist();return{accepted:true,command_status:c.status,target_status:t.status};}
 triggerAfterCompletion(id){const c=this.state.commands[id];if(!c)throw new Error('UNKNOWN_COMMAND');if(c.trigger_mode!=='AFTER_COMPLETION')throw new Error('NOT_AFTER_COMPLETION');if(c.status!=='ACTIVE')return[];const out=[];for(const t of c.targets){if(t.status==='ACTIVE'&&!t.awaiting_completion&&t.dispatch_count>0)out.push(this._dispatch(c,t,this.now()));}if(out.length)this._persist();return out;}
 pause(id){const c=this.state.commands[id];if(!c)throw new Error('UNKNOWN_COMMAND');if(c.status==='END')throw new Error('COMMAND_ENDED');c.status='PAUSED';c.updated_at_ms=this.now();this._log('PAUSED',c,null);this._persist();return clone(c);}
 resume(id){const c=this.state.commands[id];if(!c)throw new Error('UNKNOWN_COMMAND');if(c.status==='END')throw new Error('COMMAND_ENDED');c.status='ACTIVE';c.updated_at_ms=this.now();for(const t of c.targets)if(t.status==='ACTIVE'&&c.trigger_mode==='EVERY_X_MINUTES'&&t.next_due_at_ms<c.updated_at_ms)t.next_due_at_ms=c.updated_at_ms;this._log('RESUMED',c,null);this._persist();return clone(c);}
 delete(id){const c=this.state.commands[id];if(!c)return false;this._log('DELETED',c,null);delete this.state.commands[id];this._persist();return true;}
 snapshot(){return clone(this.state);}
}
class RepeatCommandBridgeAdapter{
 constructor({runtime,dispatchToPopup=()=>{},cModeQueue=[]}={}){if(!(runtime instanceof RepeatCommandRuntime))throw new Error('INVALID_RUNTIME');this.runtime=runtime;this.dispatchToPopup=dispatchToPopup;this.cModeQueue=cModeQueue;this.activeByWorker=new Map();this.repeatQueue=new Map();for(const c of runtime.list())for(const t of c.targets){if(t.awaiting_completion&&t.last_dispatch_id){const key=`${c.role}\u0000${t.group_id}\u0000${t.slot_id}`;const record={dispatch_id:t.last_dispatch_id,command_id:c.command_id,role:c.role,group_id:t.group_id,slot_id:t.slot_id,slot_key:key,state:'ACTIVE'};this.repeatQueue.set(record.dispatch_id,record);this.activeByWorker.set(key,record.dispatch_id);}}}
 parseRepeatResult(payload){if(!payload||payload.schema_version!=='W2_REPEAT_RESULT_V1')throw new Error('INVALID_REPEAT_RESULT_SCHEMA');const {role,command_id,dispatch_id,status}=payload;if(!role||!command_id||!dispatch_id||!['REPORTED','END'].includes(status))throw new Error('INVALID_REPEAT_RESULT');return{role,command_id,dispatch_id,status};}
 dispatch(receipt){const key=`${receipt.role}\u0000${receipt.group_id}\u0000${receipt.slot_id}`;if(this.repeatQueue.has(receipt.dispatch_id))throw new Error('DUPLICATE_DISPATCH_ID');if([...this.repeatQueue.values()].some(x=>x.slot_key===key&&x.state==='ACTIVE'))throw new Error('ACTIVE_COMMAND_PER_WORKER_SLOT_EXCEEDED');const record={dispatch_id:receipt.dispatch_id,command_id:receipt.command_id,role:receipt.role,group_id:receipt.group_id,slot_id:receipt.slot_id,slot_key:key,state:'ACTIVE'};this.repeatQueue.set(receipt.dispatch_id,record);this.activeByWorker.set(key,receipt.dispatch_id);this.dispatchToPopup(clone({...receipt,mode:'REPEAT_COMMAND'}));return clone(record);}
 flushRuntime(at){const receipts=this.runtime.tick(at);return receipts.map(r=>this.dispatch(r));}
 acceptRepeatResult(payload){const parsed=this.parseRepeatResult(payload);const record=this.repeatQueue.get(parsed.dispatch_id);if(!record)return{accepted:false,reason:'UNKNOWN_DISPATCH'};if(record.role!==parsed.role||record.command_id!==parsed.command_id)return{accepted:false,reason:'CORRELATION_MISMATCH'};const result=this.runtime.complete(parsed);if(!result.accepted)return result;record.state=parsed.status==='END'?'END':'COMPLETED';this.activeByWorker.delete(record.slot_key);return{accepted:true,...result};}
 enqueueCMode(item){const id=req(item.dispatch_id,'C_MODE_DISPATCH_ID');if(this.cModeQueue.some(x=>x.dispatch_id===id))return{accepted:false,reason:'C_MODE_DUPLICATE'};this.cModeQueue.push({...clone(item),mode:'C_MODE'});return{accepted:true};}
 cancelRepeat(dispatchId){const r=this.repeatQueue.get(dispatchId);if(!r)return false;r.state='CANCELLED';this.activeByWorker.delete(r.slot_key);return true;}
 snapshot(){return{repeat_queue:[...this.repeatQueue.values()].map(clone),c_mode_queue:clone(this.cModeQueue),active_worker_slots:[...this.activeByWorker.entries()]};}
}
module.exports={RepeatCommandRuntime,RepeatCommandBridgeAdapter};
