'use strict';
const assert=require('node:assert/strict');
const {build,LANES}=require('./real_site_live_binding.cjs');
let n=0; const eq=(a,b)=>{assert.deepEqual(a,b);n++}; const ok=x=>{assert.ok(x);n++};
const c6={schema_version:'A5_PRODUCT_API_DATA_FORM_IMPLEMENTATION_CONTRACT_RESULT_V1',implementation_digest:'c6digest',product_api_contract:{operations:[
 {operation_id:'OP-READ',action:{command_id:'C1',page_id:'P1',action_id:'A1'},request:{request_id:'R1',method:'GET',url_template:'https://fixture.local/api/items'},response_entities:[{entity_node_id:'ENTITY:E1',evidence_pointer:'c6://e1'}],ui_state_updates:[{component_id:'list'}]},
 {operation_id:'OP-WRITE',action:{command_id:'C2',page_id:'P2',action_id:'A2'},request:{request_id:'R2',method:'POST',url_template:'https://fixture.local/api/items'},response_entities:[{entity_node_id:'ENTITY:E2',evidence_pointer:'c6://e2'}],ui_state_updates:[{component_id:'list'}]}
]},data_model_implementation_spec:{entities:[{entity_id:'E1',record_path:'$.items[]',identifier_paths:['$.items[].id'],fields:[]},{entity_id:'E2',record_path:'$.record',identifier_paths:['$.record.id'],fields:[{source_field:'price'}]}],business_rules:{status:'UNKNOWN',reason:'BUSINESS_RULES_NOT_OBSERVED'}},form_write_binding_spec:{bindings:[{form_id:'F1',field_name:'price',application_canonical_candidate:{name:'price',authority:'APPLICATION_CANDIDATE_ONLY',confidence:.9,evidence_pointer:'c6://price'},read_transform:{status:'UNKNOWN',reason:'NOT_OBSERVED'},write_transform:{from:'price',to:'price',authority:'INFERRED',confidence:.8,evidence_pointer:'c6://write'},business_rule:{status:'UNKNOWN',reason:'RULE_NOT_OBSERVED'}}]}};
function fixture(liveWrite=true){return {schema_version:'A5_REAL_SITE_LIVE_EVIDENCE_BUNDLE_V1',cycle6_contract:c6,a3_live_evidence_pointer:'github://a3/live',a4_live_structure_pointer:'github://a4/live',operation_lane_map:{'OP-READ':'PUBLIC_READ','OP-WRITE':'WRITE'},form_lane_map:{'F1:price':'WRITE'},live_causal_events:[
 {type:'action.started',lane:'PUBLIC_READ',command_id:'C1',page_id:'P1',action_id:'A1',evidence_pointer:'live://a1',payload:{action_kind:'open'}},
 {type:'network.request',lane:'PUBLIC_READ',command_id:'C1',page_id:'P1',action_id:'A1',request_id:'R1',evidence_pointer:'live://r1',payload:{method:'GET',url_template:'https://fixture.local/api/items'}},
 {type:'network.response',lane:'PUBLIC_READ',command_id:'C1',page_id:'P1',action_id:'A1',request_id:'R1',evidence_pointer:'live://resp1',payload:{status:200,mime_type:'application/json'}},
 {type:'network.responseBody',lane:'PUBLIC_READ',command_id:'C1',page_id:'P1',action_id:'A1',request_id:'R1',evidence_pointer:'live://body1',payload:{entity_ids:['E1'],schema_paths:['$.items[]']}},
 {type:'ui.state',lane:'PUBLIC_READ',command_id:'C1',page_id:'P1',action_id:'A1',evidence_pointer:'live://state1',payload:{component_id:'list',state_before:'LOADING',state_after:'READY'}},
 ...(liveWrite?[{type:'action.started',lane:'WRITE',command_id:'C2',page_id:'P2',action_id:'A2',evidence_pointer:'live://a2',payload:{action_kind:'submit'}},{type:'network.request',lane:'WRITE',command_id:'C2',page_id:'P2',action_id:'A2',request_id:'R2',evidence_pointer:'live://r2',payload:{method:'POST',url_template:'https://fixture.local/api/items'}},{type:'network.response',lane:'WRITE',command_id:'C2',page_id:'P2',action_id:'A2',request_id:'R2',evidence_pointer:'live://resp2',payload:{status:200,mime_type:'application/json'}},{type:'network.responseBody',lane:'WRITE',command_id:'C2',page_id:'P2',action_id:'A2',request_id:'R2',evidence_pointer:'live://body2',payload:{entity_ids:['E2'],schema_paths:['$.record']}},{type:'ui.state',lane:'WRITE',command_id:'C2',page_id:'P2',action_id:'A2',evidence_pointer:'live://state2',payload:{component_id:'list',state_before:'READY',state_after:'UPDATED'}},{type:'form.write',lane:'WRITE',command_id:'C2',page_id:'P2',action_id:'A2',request_id:'R2',evidence_pointer:'live://form1',payload:{form_id:'F1',field_name:'price',write_transform:{from:'price',to:'price',location:'body'}}}]:[])
]};}
const a=build(fixture(true)),b=build(fixture(true));
eq(a.schema_version,'A5_REAL_SITE_LIVE_BINDING_RESULT_V1');eq(a.decision_status,'READY');eq(a.real_site_api_ui_state_binding.lanes.PUBLIC_READ.length,1);eq(a.real_site_api_ui_state_binding.lanes.WRITE.length,1);eq(a.real_site_api_ui_state_binding.lanes.MY_LISTING.length,0);eq(a.real_site_api_ui_state_binding.lanes.EDIT.length,0);eq(a.real_site_api_ui_state_binding.lanes.PUBLIC_READ[0].request.status,'OBSERVED');eq(a.real_site_api_ui_state_binding.lanes.WRITE[0].response.status,'OBSERVED');eq(a.real_site_data_entity_binding.lanes.PUBLIC_READ[0].entities[0].status,'OBSERVED');eq(a.real_site_data_entity_binding.lanes.WRITE[0].entities[0].status,'OBSERVED');eq(a.real_site_form_field_binding.lanes.WRITE[0].write_transform.status,'OBSERVED');eq(a.a5_to_a6_live_execution_handoff.lanes.PUBLIC_READ.status,'READY');eq(a.a5_to_a6_live_execution_handoff.lanes.WRITE.status,'READY');eq(a.raw_secret_value_count,0);eq(a.raw_pii_value_count,0);eq(a.live_binding_digest,b.live_binding_digest);ok(/^[a-f0-9]{64}$/.test(a.live_binding_digest));eq(LANES.join(','),'PUBLIC_READ,WRITE,MY_LISTING,EDIT');
const late=build(fixture(false));eq(late.decision_status,'READY_WITH_WAITING_INPUT');ok(late.unknown_business_rule_index.counts.waiting_input>0);ok(late.real_site_api_ui_state_binding.waiting_input_edges.some(x=>x.operation_id==='OP-WRITE'));eq(late.a5_to_a6_live_execution_handoff.lanes.WRITE.status,'PARTIAL_WAITING_INPUT');
const secret=fixture(true);secret.extra='Bearer SECRETSECRET';assert.throws(()=>build(secret),/RAW_SECRET_VALUE_REJECTED/);n++;
const pii=fixture(true);pii.customer={email:'person@example.com'};assert.throws(()=>build(pii),/RAW_PII_VALUE_REJECTED/);n++;
console.log(JSON.stringify({status:'PASS',fixture_replay_count:2,assertions:n,digest1:a.live_binding_digest,digest2:b.live_binding_digest,late_binding_wait_count:late.unknown_business_rule_index.counts.waiting_input}));
