import json, sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT))
from field_mapping_rule_validator import load_json, validate_catalog, run_fixture, catalog_rules, consumer_targets
catalog=load_json(ROOT/'TRANSFORMATION_RULE_CATALOG_V1.json')
consumer=load_json(ROOT/'FIELD_MAPPING_CONTRACT_CONSUMER_V1.json')
fixture=load_json(ROOT/'FIELD_MAPPING_FIXTURE_V1.json')
checks=[]
def check(name, cond):
 checks.append((name,bool(cond))); print(('PASS' if cond else 'FAIL'),name)
errors=validate_catalog(catalog,consumer)
check('catalog validator has no errors',errors==[])
check('rule count exact 69',catalog['rule_count']==69)
check('B rule count 31',catalog['package_rule_counts']['MATERIALIZED_DATABASE_PACKAGE_V1']==31)
check('C rule count 38',catalog['package_rule_counts']['KNOWLEDGE_CANDIDATE_BUNDLE_V1']==38)
check('all rule ids unique',len({r['RULE_ID'] for r in catalog_rules(catalog)})==69)
check('all target fields bound',len(consumer_targets(consumer))>=60)
check('D authority exact head',consumer['d_authority']['head']=='36848d3e641077e4905eccc17856369f0c494579')
check('D profile blob exact',consumer['d_authority']['contracts']['D_CANONICAL_SCHEMA_PROFILE_V1']['blob']=='93788d2685d25afae2d8e61c6b59e9615c51d22a')
check('D mapping blob exact',consumer['d_authority']['contracts']['D_INBOUND_FIELD_MAPPING_CONTRACT_V1']['blob']=='c2a3ae441ae0e2b44fb1bb9f95670cf0887bd8ed')
check('D ruleset blob exact',consumer['d_authority']['contracts']['D_INTAKE_VALIDATION_RULESET_V1']['blob']=='d21291ac77f44f84fffac6d935187f3ee4690dcd')
check('read only authority',consumer['mode']=='READ_ONLY_FAIL_CLOSED')
check('D schema mutation false',consumer['d_schema_mutation'] is False)
check('D canonical DB write false',consumer['d_canonical_db_write'] is False)
check('silent drop false',consumer['validation_behavior']['silent_drop'] is False)
check('C3 canonical ID generation forbidden',catalog['canonical_identifier_policy']['c3_may_generate_canonical_ids'] is False)
check('mapping version reproducible',all(r['MAPPING_VERSION']=='1.0.0' for r in catalog_rules(catalog)))
check('each rule has full trace',all(all(k in r for k in ['SOURCE_FIELD','TRANSFORMATION_RULE_ID','TARGET_ENTITY','TARGET_FIELD','TARGET_TYPE','FORMAT_CONVERSION','UNIT_CONVERSION','CODE_NORMALIZATION','IDENTIFIER_NORMALIZATION','RELATION_MAPPING','MAPPING_VERSION']) for r in catalog_rules(catalog)))
check('format category represented',any(r['FORMAT_CONVERSION']!='NONE' for r in catalog_rules(catalog)))
check('unit policy represented',catalog['unit_conversion_policy']['silent_unit_coercion'] is False)
check('code category represented',any(r['CODE_NORMALIZATION']!='NONE' for r in catalog_rules(catalog)))
check('identifier category represented',any(r['IDENTIFIER_NORMALIZATION']!='NONE' for r in catalog_rules(catalog)))
check('relation category represented',any(r['RELATION_MAPPING']!='NONE' for r in catalog_rules(catalog)))
results=run_fixture(catalog,fixture)
check('fixture case count 20',len(results)==20)
check('all fixture cases pass expected decision',all(r['pass'] for r in results))
check('unmapped field preserved',next(r for r in results if r['case_id']=='F020')['source_value_preserved']=='preserve me')
check('D ID generation deferred',next(r for r in results if r['case_id']=='F015')['status']=='D_GENERATION_REQUIRED')
check('invalid code rejected',next(r for r in results if r['case_id']=='F019')['reason_code']=='INVALID_CODE')
check('missing relation rejected',next(r for r in results if r['case_id']=='F018')['reason_code']=='FOREIGN_REFERENCE_MISSING')
check('B actual transformation pending',consumer['actual_b_record_transformation_ready'] is False)
passed=sum(v for _,v in checks)
output={'tests_total':len(checks),'tests_passed':passed,'tests_failed':len(checks)-passed,'catalog_errors':errors,'fixture_results':results}
(ROOT/'TEST_EXECUTION_DETAIL.json').write_text(json.dumps(output,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(f'RESULT {passed}/{len(checks)} PASS')
if passed!=len(checks): raise SystemExit(1)
