'use strict';
const fs=require('node:fs'); const crypto=require('node:crypto');
const stable=v=>Array.isArray(v)?v.map(stable):v&&typeof v==='object'?Object.keys(v).sort().reduce((a,k)=>(a[k]=stable(v[k]),a),{}):v;
const sha=v=>crypto.createHash('sha256').update(JSON.stringify(stable(v))).digest('hex');
function assert(c,m){if(!c)throw new Error(m)}
function compile(input){
 assert(input?.schema_version==='A6_CYCLE7_INPUT_AUTHORITY_V1','BAD_INPUT_SCHEMA');
 assert(input.a4?.binding_blob&&input.a5?.handoff_blob&&input.cycle6?.package_blob,'MISSING_EXACT_BINDING');
 assert(input.boundaries?.new_executor===false,'NEW_EXECUTOR_FORBIDDEN');
 const lineage={directive_id:input.directive_id,cycle_id:input.cycle_id,cycle6_package_blob:input.cycle6.package_blob,a4_head:input.a4.head,a4_binding_blob:input.a4.binding_blob,a4_actual_chrome_receipt_blob:input.a4.actual_chrome_receipt_blob,a5_head:input.a5.head,a5_handoff_blob:input.a5.handoff_blob,a5_validation_blob:input.a5.validation_blob};
 const recipe={schema_version:'REAL_SITE_RECIPE_V1',recipe_version:'1.0.0-cycle7',lineage,runtime_source:{kind:'ACTUAL_CHROMIUM_EVIDENCE_REPLAY',browser:input.actual_runtime.browser,cdp_transport:input.actual_runtime.cdp_transport,actual_observed_url:input.actual_runtime.url,external_target_site_coverage:false,target_pc_command_receipt:'ABSENT'},provenance:{command_id:{status:'UNKNOWN',value:null,reason:'A4_ACTUAL_CHROME_RECEIPT_HAS_NO_COMMAND_ID'},action_id:{status:'OBSERVED',value:input.actual_runtime.action_id},page_id:{status:'INFERRED',value:'public-list'}},lanes:{READ:{status:'READY_ACTUAL_BROWSER_EVIDENCE',page_role:'PUBLIC_LIST',steps:[{step_id:'s01',kind:'Navigate',target:input.actual_runtime.url,evidence:'A4_ACTUAL_CHROME_RECEIPT'},{step_id:'s02',kind:'Wait',locator:input.observed_read_binding.result_list,evidence:'A4_RUNTIME_LOCATOR_OBSERVED'},{step_id:'s03',kind:'Extract',fields:input.observed_read_binding.fields,evidence:'A4_ACTUAL_STRUCTURE_HANDOFF'},{step_id:'s04',kind:'Pagination',locator:input.observed_read_binding.pagination,evidence:'A4_RUNTIME_LOCATOR_OBSERVED'}]},WRITE:{status:'PARTIAL_WAITING_INPUT',scope:'OBSERVE_AND_SPECIFY_ONLY',final_action:'submitCreate',policy:'USER_CONFIRM_REQUIRED'},MY_LISTING:{status:'PARTIAL_WAITING_INPUT',scope:'OBSERVE_AND_SPECIFY_ONLY'},EDIT:{status:'PARTIAL_WAITING_INPUT',scope:'OBSERVE_AND_SPECIFY_ONLY',final_actions:['submitUpdate','delete','expire'],policy:'USER_CONFIRM_REQUIRED'}},unknown_fail_closed:{waiting_edge_count:input.a5.waiting_edge_count,a4_unknown_structure_count:20,promote_without_exact_evidence:false},final_submit:false,new_executor:false};
 const executionSpec={schema_version:'REAL_SITE_ADAPTER_EXECUTION_SPEC_V1',adapter_version:'1.0.0-cycle7',recipe_sha256:sha(recipe),runtime:['Playwright','Crawlee'],execution_route:{target_pc_commands:'SUCCESSOR_EXISTING_COMMAND_BUS_ONLY',new_executor:false,new_tunnel:false,new_browser_engine:false,target_pc_receipt_present:false},read:{technical_binding:'READY',evidence_scope:'ACTUAL_CHROMIUM_LOCAL_HTTP_FIXTURE',external_target_site_coverage:false,locators:[input.observed_read_binding.result_list,input.observed_read_binding.result_card,input.observed_read_binding.pagination],fields:Object.keys(input.observed_read_binding.fields)},write:{status:'PARTIAL_WAITING_INPUT',final_submit:false},my_listing:{status:'PARTIAL_WAITING_INPUT',final_submit:false},edit:{status:'PARTIAL_WAITING_INPUT',final_submit:false},browser_worker_completion_event:{usage:'EXECUTION_LIFECYCLE_ONLY',adapter_technical_pass_source:false},fail_closed:true};
 function execute({failAt=null,checkpoint=null}={}){const steps=recipe.lanes.READ.steps;const cp=checkpoint?JSON.parse(JSON.stringify(checkpoint)):{schema_version:'REAL_SITE_RESUME_CHECKPOINT_V1',checkpoint_id:'a6-cycle7-read-001',recipe_sha256:sha(recipe),last_completed_step:null,resume_from_step:0,completed_step_ids:[],status:'RUNNING'};let executed=0,skipped=0;for(let i=cp.resume_from_step;i<steps.length;i++){const s=steps[i];if(cp.completed_step_ids.includes(s.step_id)){skipped++;continue}if(failAt===s.step_id){cp.status='FAILED';cp.failed_step=s.step_id;cp.resume_from_step=i;cp.checkpoint_sha256=sha({...cp,checkpoint_sha256:undefined});return{cp,receipt:{status:'FAILED',failed_step:s.step_id,executed_step_count:executed,resume_from_step:i}}}cp.completed_step_ids.push(s.step_id);cp.last_completed_step=s.step_id;cp.resume_from_step=i+1;executed++;}cp.status='COMPLETED';cp.failed_step=null;cp.checkpoint_sha256=sha({...cp,checkpoint_sha256:undefined});return{cp,receipt:{status:'PASS',executed_step_count:executed,skipped_completed_step_count:skipped,last_completed_step:cp.last_completed_step,resume_from_step:cp.resume_from_step}}}
 const full1=execute(), full2=execute(); const forced=execute({failAt:'s03'}); const resumed=execute({checkpoint:forced.cp});
 assert(full1.receipt.status==='PASS'&&full2.receipt.status==='PASS','REPLAY_FAIL');
 assert(sha(full1.receipt)===sha(full2.receipt),'NON_DETERMINISTIC_REPLAY');
 assert(forced.cp.last_completed_step==='s02'&&forced.cp.resume_from_step===2,'BAD_CHECKPOINT');
 assert(resumed.receipt.executed_step_count===2&&resumed.receipt.skipped_completed_step_count===0,'BAD_RESUME');
 const replay={schema_version:'REAL_SITE_REPLAY_RESULT_V1',status:'PASS_EVIDENCE_REPLAY',technical_scope:'ACTUAL_CHROMIUM_LOCAL_HTTP_FIXTURE_BINDING',external_target_site_execution:false,target_pc_execution_receipt:false,replay_run_count:2,deterministic:true,replay_digest:sha(full1.receipt),forced_failure_step:'s03',last_completed_before_failure:'s02',resume_from_step:2,resume_executed_steps:2,completed_steps_reexecuted:false,command_id_status:'UNKNOWN',action_id_status:'OBSERVED',page_id_status:'INFERRED'};
 const checkpoint={...resumed.cp,forced_failure_step:'s03',last_completed_before_failure:'s02',completed_steps_reexecuted:false};
 const livePackage={schema_version:'AI_SITE_BUILD_PACKAGE_LIVE_BINDING_V1',source_cycle6:{head:input.cycle6.head,package_blob:input.cycle6.package_blob,package_sha256:input.cycle6.package_sha256},live_binding_authority:lineage,lane_status:{READ:'READY_ACTUAL_BROWSER_EVIDENCE',WRITE:'PARTIAL_WAITING_INPUT',MY_LISTING:'PARTIAL_WAITING_INPUT',EDIT:'PARTIAL_WAITING_INPUT'},read_binding:{page_role:'PUBLIC_LIST',actual_browser:input.actual_runtime.browser,observed_locators:[input.observed_read_binding.result_list,input.observed_read_binding.result_card,input.observed_read_binding.pagination],field_count:Object.keys(input.observed_read_binding.fields).length},product_write_blueprint_update:{write_runtime_ready:false,my_listing_runtime_ready:false,edit_runtime_ready:false,reason:'NO_ACTUAL_FORM_WRITE_ACTION_OR_OWNER_SESSION_CAUSAL_RECEIPT',final_actions:{submitCreate:'USER_CONFIRM_REQUIRED',submitUpdate:'USER_CONFIRM_REQUIRED',delete:'USER_CONFIRM_REQUIRED',expire:'USER_CONFIRM_REQUIRED'}},unknown_index:{a4_unknown_count:20,a5_waiting_edge_count:input.a5.waiting_edge_count,command_id:'UNKNOWN',external_target_site_coverage:'NOT_CLAIMED'},replay_checkpoint:{replay_result_sha256:sha(replay),checkpoint_sha256:checkpoint.checkpoint_sha256},safety:{new_executor:false,target_pc_execution:false,external_target_site_execution:false,final_submit:false,production:false,ready:false,merge:false}};
 const validation={schema_version:'A6_CYCLE7_REAL_SITE_BINDING_VALIDATION_RECEIPT_V1',status:'PASS_BINDING_WITH_FAIL_CLOSED_PARTIAL_LANES',source_parse:'PASS',deterministic_replay_2_of_2:true,actual_chromium_evidence:true,actual_browser:input.actual_runtime.browser,actual_http_fixture:true,external_target_site_coverage:false,target_pc_execution_receipt:false,read_binding_ready:true,write_lane:'PARTIAL_WAITING_INPUT',my_listing_lane:'PARTIAL_WAITING_INPUT',edit_lane:'PARTIAL_WAITING_INPUT',forced_failure_step:'s03',last_completed_before_failure:'s02',resume_from_step:2,resume_executed_steps:2,completed_steps_reexecuted:false,unknown_fail_closed:true,command_id_status:'UNKNOWN',new_executor:false,final_submit:false};
 return{recipe,executionSpec,replay,checkpoint,livePackage,validation};
}
if(require.main===module){const input=JSON.parse(fs.readFileSync(process.argv[2],'utf8'));const out=compile(input);for(const [name,obj] of Object.entries(out))fs.writeFileSync(process.argv[3]+'/'+name+'.json',JSON.stringify(obj,null,2)+'\n');console.log(JSON.stringify({status:'PASS',recipe_sha256:sha(out.recipe),spec_sha256:sha(out.executionSpec),replay_sha256:sha(out.replay),package_sha256:sha(out.livePackage)}));}
module.exports={compile,sha};
