/* eslint-env browser */
"use strict";
const api = window.yollaLogAnalyzer;
const $ = id => document.getElementById(id);
let snapshot = null;
function set(id,value){const node=$(id);if(node)node.textContent=String(value==null?"-":value)}
function esc(value){return String(value==null?"":value).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")}
function renderIssues(){const root=$("issues");const rows=snapshot&&snapshot.analysis&&snapshot.analysis.collision_signals||[];root.innerHTML=rows.length?rows.slice(0,12).map(row=>`<div class="issue ${row.severity==="WARN"?"warn":""}"><b>${esc(row.message)}</b> <span>${esc(row.at||"")}</span>${row.details?`<div>${esc(JSON.stringify(row.details))}</div>`:""}</div>`).join(""):'<div class="empty">현재 충돌·오류 신호가 없습니다.</div>'}
function renderLog(){const root=$("log");let rows=snapshot&&snapshot.entries||[];if($("errors-only").checked)rows=rows.filter(row=>row.severity==="ERROR"||row.severity==="WARN");root.innerHTML=rows.length?rows.map(row=>`<article class="row ${esc(row.severity)}"><div class="meta">${esc(row.at||"-")} · ${esc(row.source||"runtime")} · ${esc(row.severity||"INFO")}</div><div class="message">${esc(row.message||"")}</div>${row.details?`<pre>${esc(JSON.stringify(row.details,null,2))}</pre>`:""}</article>`).join(""):'<div class="empty">기록된 로그가 없습니다.</div>';if($("autoscroll").checked)root.scrollTop=root.scrollHeight}
function render(value){snapshot=value||{};const a=snapshot.analysis||{};const counts=a.counts||{};const c=snapshot.c_mode||{};const w=snapshot.worker_counts||{};set("errors",counts.error||0);set("warnings",counts.warn||0);set("signals",a.collision_signal_count||0);set("completed",c.completed_task_count||0);set("c-status",c.status||"IDLE");set("wave",c.wave||0);set("missing",c.missing_count||0);set("duplicates",c.duplicate_dispatch_count||0);set("workers",w.total||0);set("observed",snapshot.observed_at||"-");renderIssues();renderLog()}
async function refresh(){try{render(await api.getSnapshot())}catch(error){set("export-result",`분석 실패: ${error.message||error}`)}}
$("refresh").addEventListener("click",refresh);$("errors-only").addEventListener("change",renderLog);$("open-folder").addEventListener("click",()=>api.openFolder());$("export").addEventListener("click",async()=>{const b=$("export");const prior=b.textContent;b.disabled=true;b.textContent="ZIP 생성 중";set("export-result","");try{const result=await api.exportDiagnostics();if(result&&result.canceled){set("export-result","저장 취소")}else{set("export-result",`${result.file_path} · ${result.size} bytes · SHA256 ${result.sha256}`)}}catch(error){set("export-result",`저장 실패: ${error.message||error}`)}finally{b.disabled=false;b.textContent=prior}});api.onEvent(()=>refresh());refresh();setInterval(refresh,2000);
