'use strict';
const assert=require('node:assert/strict');
const {buildRecipe}=require('./structure_to_endpoint_schema_binding.cjs');
let n=0;const eq=(a,b)=>{assert.deepEqual(a,b);n++};const ok=x=>{assert.ok(x);n++};
function fixture(includeBody=true){return {schema_version:'A5_A3_A4_EVIDENCE_BUNDLE_V1',command_id:'CMD-001',run_id:'C3-SMOKE-001',a3_observation_pointer:'github://a3/receipt',a4_structure_pointer:'github://a4/receipt',a3_observation_receipt:{schema_version:'CDP_OBSERVATION_RUN_RECEIPT_V1',status:'PASS',run_id:'A3-RUN-1',page_identity:{page_id:'page-1',target_type:'page',title:'Fixture',url:'https://fixture.local/list'},artifacts:{dom_snapshot_pointer:{path:'dom.json'},request_response_metadata_pointer:{path:'network.ndjson'},redacted_response_body_pointer:{path:'body.ndjson'},frame_navigation_pointer:{path:'frames.ndjson'}},timestamps:{started_at:'x',finished_at:'y'},retry_count:0,retry_policy:'NO_INTERNAL_RETRY'},a3_artifact_pointers:{request_response_metadata:'github://a3/network',redacted_response_body:'github://a3/body'},a3_resolved_artifacts:{request_response_metadata:[{type:'network.request',page_id:'page-1',request_id:'r1',action_id:'ACT-9',payload:{method:'GET',url:'https://fixture.local/api/items?page=1',headers:{Cookie:'<REDACTED>'}}},{type:'network.response',page_id:'page-1',request_id:'r1',action_id:'ACT-9',payload:{status:200,mime_type:'application/json'}}],redacted_response_body:includeBody?[{type:'network.responseBody',page_id:'page-1',request_id:'r1',action_id:'ACT-9',payload:{mime_type:'application/json',redacted_body:{records:[{record_id:'R1',name:'Alpha'}]}}}]:[]},a4_structure_receipt:{schema_version:'STRUCTURE_INFERENCE_RUN_RECEIPT_V1',request_id:'A4-RUN-1',page_identity:{page_id:'page-1',url:'https://fixture.local/list'},fields:[{field_id:'f1',name:'record_id',source_locator:'article.item',confidence:.9,value_type:'text'},{field_id:'f2',name:'name',source_locator:'h2.name',confidence:.9,value_type:'text'},{field_id:'f3',name:'detail_url',source_locator:'a.detail',confidence:.9,value_type:'url'}],locator_candidates:[{field_id:'f1',locator:'locator("article.item")',strategy:'css',stability_score:.9},{field_id:'f2',locator:'locator("h2.name")',strategy:'css',stability_score:.9},{field_id:'f3',locator:'locator("a.detail")',strategy:'css',stability_score:.9}],repeated_regions:[{region_id:'r',item_count:3,confidence:.9}],pagination_candidates:[{type:'NEXT',detected:true,confidence:.96,stop_condition:'NEXT_LINK_ABSENT'}],evidence_pointer:{path:'a4.json'}}};}
function makeReceipt(req){const rows=req.observation_pointer.receipt.network_request_stream||[];const endpoint_candidates=rows.map((r,i)=>({endpoint_id:'EP'+(i+1),method:r.method,url_template:r.url.split('?')[0],parameters:[],evidence_pointer:req.observation_pointer.uri}));let schema_fields={status:'UNKNOWN',reason:'OPTIONAL_RESPONSE_BODY_POINTER_ABSENT_OR_UNRESOLVED'};if(req.response_body_pointer){const body=req.response_body_pointer.receipt.response_bodies?.[0]?.body;if(body){const out=[];const walk=(v,p='$')=>{out.push({path:p,types:[Array.isArray(v)?'array':v===null?'null':typeof v]});if(Array.isArray(v))v.slice(0,1).forEach(x=>walk(x,p+'[]'));else if(v&&typeof v==='object')for(const[k,x]of Object.entries(v))walk(x,p+'.'+k)};walk(body);schema_fields=out;}}const st=req.structure_pointer.receipt;const names=(st.fields||st.fieldCandidates||[]).map(x=>x.name);const has=Array.isArray(schema_fields);return {decision_status:has?'PASS':'PASS_CONFIDENCE_DEGRADED',endpoint_candidates,schema_fields,identifier_map:{primary_key:names.includes('record_id')?{field:'record_id'}:{status:'UNKNOWN'},relations:names.includes('detail_url')?[{relation:'LIST_TO_DETAIL'}]:[]},session_requirements_reference:{requirements:[{type:'COOKIE_JAR_REFERENCE'}]},mode_scores:{DOM:.7,API:has?.8:.18,HYBRID:has?.68:.15},recommended_mode:has?'HYBRID':'DOM',confidence_state:has?'FULL_EVIDENCE':'CONFIDENCE_DEGRADED_RESPONSE_BODY_MISSING',unknown_fields:has?[]:['schema_fields']};}
const deps={makeReceipt};
const a=buildRecipe(fixture(true),deps),b=buildRecipe(fixture(true),deps);
eq(a.schema_version,'RECIPE_DECISION_INPUT_V1');eq(a.decision_status,'READY');eq(a.provenance.command_id,'CMD-001');eq(a.provenance.page_id,'page-1');eq(a.provenance.action_id,'ACT-9');eq(a.mode_decision.recommended_mode,'HYBRID');eq(a.a6_direct_consume.compile_allowed,true);eq(a.pagination_binding.type,'NEXT');eq(a.raw_secret_value_count,0);eq(a.decision_digest,b.decision_digest);ok(/^[a-f0-9]{64}$/.test(a.decision_digest));
const degraded=buildRecipe(fixture(false),deps);eq(degraded.decision_status,'INSUFFICIENT_EVIDENCE');eq(degraded.response_binding.schema_fields.status,'UNKNOWN');eq(degraded.a6_direct_consume.compile_allowed,false);eq(degraded.mode_decision.recommended_mode,'DOM');
const mismatch=fixture(true);mismatch.a4_structure_receipt.page_identity.page_id='other';assert.throws(()=>buildRecipe(mismatch,deps),/page_id mismatch/i);n++;
const secret=fixture(true);secret.a3_resolved_artifacts.request_response_metadata[0].payload.headers.Authorization='Bearer SECRETSECRET';assert.throws(()=>buildRecipe(secret,deps),/Raw secret-like/i);n++;
console.log(JSON.stringify({status:'PASS',fixture_replay_count:2,assertions:n,digest_run1:a.decision_digest,digest_run2:b.decision_digest,recommended_mode:a.mode_decision.recommended_mode,degraded_mode:degraded.mode_decision.recommended_mode}));
