#!/usr/bin/env node
'use strict';
const fs=require('node:fs');const path=require('node:path');const crypto=require('node:crypto');const {spawnSync}=require('node:child_process');const {runSampleScenario}=require('./runtime/scenario-runner.cjs');
const ROOT=__dirname;
function sha256File(f){return crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex');}
function verifyPackage(){const m=JSON.parse(fs.readFileSync(path.join(ROOT,'PRODUCT_MANIFEST.json'),'utf8'));const fail=[];for(const x of m.members){const f=path.join(ROOT,x.path);if(!fs.existsSync(f)){fail.push(`${x.path}:MISSING`);continue;}if(sha256File(f)!==x.sha256)fail.push(`${x.path}:SHA256_MISMATCH`);}if(fail.length)throw new Error(`PRODUCT_VERIFY_FAILED:${fail.join('|')}`);return{status:'PASS',member_count:m.members.length,product_id:m.product_id,single_launcher:'launcher.cjs'};}
function electronExecutable(){try{const e=require('electron');return typeof e==='string'?e:null;}catch{return null;}}
function runElectron(){const e=electronExecutable();if(!e)throw new Error('ELECTRON_MODULE_NOT_INSTALLED_USE_NODE_CHROMIUM_MODE');const r=spawnSync(e,[path.join(ROOT,'electron/main.cjs')],{stdio:'inherit',cwd:ROOT});if(r.error)throw r.error;process.exitCode=r.status??1;}
async function runSample(){const receipt=await runSampleScenario({root:ROOT});console.log(JSON.stringify({terminal:'B1_SITE_ANALYZER_WAVE2_SINGLE_PRODUCT_SAMPLE_PASS',runtime_result:receipt.runtime_result,extracted_record_count:receipt.adapter.exact_record_count,network_event_count:receipt.node_http_runtime_bridge.network_event_count+receipt.chromium_cdp.network_event_count,response_body_count:receipt.node_http_runtime_bridge.response_body_count+receipt.chromium_cdp.response_body_count,recorded_action_count:receipt.chromium_cdp.recorded_action_count,mode:receipt.inference.mode,parity:receipt.preview_export.parity,preview:'outputs/preview.html'},null,2));return receipt;}
async function main(){const cmd=process.argv[2]||'auto';if(cmd==='verify'){console.log(JSON.stringify(verifyPackage(),null,2));return;}if(cmd==='test'){const r=spawnSync(process.execPath,['--test','tests/*.test.cjs'],{cwd:ROOT,stdio:'inherit',shell:true});process.exitCode=r.status??1;return;}if(cmd==='electron'){runElectron();return;}if(cmd==='auto'&&electronExecutable()){runElectron();return;}if(!['auto','sample','chromium','node'].includes(cmd))throw new Error(`UNKNOWN_COMMAND:${cmd}`);await runSample();}
main().catch(e=>{console.error(e.stack||e.message);process.exitCode=2;});
