'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const ui = require('./panel_liveness_row_view_model.cjs');

let assertions = 0;
function eq(actual, expected, message) { assertions += 1; assert.deepEqual(actual, expected, message); }
function ok(value, message) { assertions += 1; assert.ok(value, message); }

const fixture = JSON.parse(fs.readFileSync(path.join(__dirname, 'PANEL_LIVENESS_ROW_FIXTURE_V1.json'), 'utf8'));
const view = ui.buildPanelLivenessViewModel(fixture);
const stateByRole = Object.fromEntries(view.current.map(row => [row.role_id, row.state]));
eq(stateByRole, fixture.expected_states, 'five-state projection');
eq(view.allowed_states, ['WAITING','WORKING','RESULT_PENDING','COMPLETED','REVIEW_REQUIRED'], 'allowed states exact');
ok(view.current.every(row => view.allowed_states.includes(row.state)), 'no other state');
eq(view.current.find(row => row.role_id === 'W2').generating, true, 'working bound to generating');
eq(view.current.find(row => row.role_id === 'W6').state, 'WAITING', 'missing result alone is waiting');
eq(view.current.find(row => row.role_id === 'W5').state, 'REVIEW_REQUIRED', 'explicit review only');
eq(view.current.find(row => row.role_id === 'W4').github_result.label, 'RESULT_COMMENT #5200547394', 'result comment priority');
eq(view.current.find(row => row.role_id === 'W7').github_result.label, 'RESULT_KEY 520054999900', 'result key fallback');
eq(view.current.find(row => row.role_id === 'W2').elapsed, '25m', 'working elapsed');
eq(view.current.find(row => row.role_id === 'W4').elapsed, '1h 20m', 'completed elapsed stops at result');
eq(view.current.find(row => row.role_id === 'W1').elapsed, '—', 'waiting elapsed absent');
eq(view.historical.length, fixture.expected_historical_rows, 'historical rows separate');
ok(view.historical.every(row => row.wave_id !== fixture.current_wave_id), 'historical excludes current wave');
ok(view.current.every(row => row.current_wave_id === fixture.current_wave_id), 'current wave bound');
const html = ui.renderPanelLivenessTable(view);
ok(html.includes('ROLE</th><th scope="col">상태'), 'column order begins role state');
ok(html.includes('경과시간'), 'elapsed column');
ok(html.includes('마지막확인'), 'last check column');
ok(html.includes('채팅열기'), 'chat column');
ok(html.includes('GitHub결과'), 'github column');
eq((html.match(/data-wave-scope="current"/g) || []).length, view.current.length + 1, 'current scope tbody plus rows');
eq((html.match(/data-wave-scope="historical"/g) || []).length, view.historical.length + 1, 'history scope tbody plus rows');
eq((html.match(/data-liveness-state="WORKING"/g) || []).length, 1, 'one working row');
eq((html.match(/aria-label="생성 중"/g) || []).length, 1, 'generating indicator exactly one');
ok(html.includes('RESULT_COMMENT #5200547394'), 'current github result');
ok(html.includes('RESULT_COMMENT #5200000004'), 'historical github result');
ok(!html.includes('legacy_profile_status'), 'legacy source not rendered');
ok(!html.includes('data-mode="A"') && !html.includes('data-mode="E"'), 'legacy modes absent');
const container = { innerHTML: '' };
const mounted = ui.mountPanelLiveness(container, fixture);
eq(mounted.current.length, 7, 'mount rows');
ok(container.innerHTML === html, 'deterministic mount');
assert.throws(() => ui.mountPanelLiveness(null, fixture), /LIVENESS_CONTAINER_REQUIRED/); assertions += 1;
const missingOnly = ui.buildRoleLivenessViewModel({role_id:'WX', results:[]}, {current_wave_id:fixture.current_wave_id,now_at:fixture.now_at});
eq(missingOnly.state, 'WAITING', 'no result is not review');
const historicalOnly = ui.buildRoleLivenessViewModel({role_id:'WY',results:[{wave_id:'OLD',status:'END',result_comment_id:1}]},{current_wave_id:fixture.current_wave_id,now_at:fixture.now_at});
eq(historicalOnly.state, 'WAITING', 'historical completion does not complete current wave');
eq(historicalOnly.historical_results.length, 1, 'historical retained');
const currentCompleted = ui.buildRoleLivenessViewModel({role_id:'WZ',results:[{wave_id:fixture.current_wave_id,status:'END',result_comment_id:9,result_key:'x'}]},{current_wave_id:fixture.current_wave_id,now_at:fixture.now_at});
eq(currentCompleted.state, 'COMPLETED', 'current terminal completes');
eq(currentCompleted.github_result.type, 'RESULT_COMMENT', 'comment reference type');
const css = fs.readFileSync(path.join(__dirname, 'panel_liveness_row.css'), 'utf8');
for (const state of view.allowed_states) ok(css.includes(`.state-${state.toLowerCase()}`), `css ${state}`);
ok(css.includes('[data-wave-scope=historical]'), 'history css separated');
ok(css.includes('@keyframes liveness-pulse'), 'generation pulse css');
console.log(JSON.stringify({status:'PASS',assertion_count:assertions,current_rows:view.current.length,historical_rows:view.historical.length,allowed_states:view.allowed_states}, null, 2));
