const clone=v=>v===undefined?undefined:structuredClone(v);
export class RuntimeInspectorBridge {
  constructor(win=globalThis.window,{sessionId='B2-WAVE3'}={}){this.win=win;this.sessionId=sessionId;this.handlers=new Map();this.seq=0;this.received=new Set();this.port=null;this.state={connected:false,inbound:0,outbound:0,duplicates:0,transport:null};}
  on(topic,fn){const s=this.handlers.get(topic)||new Set();s.add(fn);this.handlers.set(topic,s);return()=>s.delete(fn);}
  dispatch(topic,payload,env){for(const fn of this.handlers.get(topic)||[])fn(clone(payload),clone(env));for(const fn of this.handlers.get('*')||[])fn(topic,clone(payload),clone(env));}
  receive(message,transport='UNKNOWN'){if(!message||typeof message!=='object')return false;const topic=String(message.topic||'');if(!topic.startsWith('analyzer:'))return false;const env={topic,payload:clone(message.payload||{}),sequence:Number(message.sequence||0),sessionId:String(message.sessionId||'runtime'),source:String(message.source||'runtime')};const key=`${env.sessionId}:${env.sequence}:${topic}`;if(env.sequence&&this.received.has(key)){this.state.duplicates++;return false;}if(env.sequence)this.received.add(key);this.state.connected=true;this.state.inbound++;this.state.transport=transport;this.dispatch(topic,env.payload,env);return true;}
  publish(topic,payload={}){const msg={topic,payload:clone(payload),sequence:++this.seq,sessionId:this.sessionId,source:'B-2',timestamp:new Date().toISOString()};if(this.port){this.port.postMessage(msg);this.state.outbound++;return msg;}this.win.dispatchEvent(new this.win.CustomEvent('yolla-analyzer-ui-outbound',{detail:msg}));this.state.outbound++;return msg;}
  connect(){this._message=e=>{if(e.data?.type==='YOLLA_ANALYZER_RUNTIME_PORT'&&e.ports?.[0]){this.port=e.ports[0];this.port.onmessage=ev=>this.receive(ev.data,'MESSAGE_PORT');this.port.start?.();this.state.connected=true;this.state.transport='MESSAGE_PORT';this.publish('analyzer:b2-runtime-ready',{version:'WAVE3_INSPECTOR_V1'});return;}this.receive(e.data,'WINDOW_MESSAGE');};this.win.addEventListener('message',this._message);return this.state;}
}
