import {VisualInspectorSyncModel} from './inspector_sync_model.mjs';
import {RuntimeInspectorBridge} from './runtime_inspector_bridge.mjs';
const q=new URLSearchParams(location.search); const model=new VisualInspectorSyncModel({mode:q.get('mode')||'embedded'}); const bridge=new RuntimeInspectorBridge(window); const $=s=>document.querySelector(s); const frame=$('#browser'); let picker=false; let mutationObserver=null; const boundDocs=new WeakSet();
function selectorFor(el){if(el.id)return `#${el.id}`;const rid=el.getAttribute?.('data-record-id');if(rid)return `${el.tagName.toLowerCase()}[data-record-id="${rid}"]`;const cls=[...(el.classList||[])][0];return cls?`${el.tagName.toLowerCase()}.${cls}`:el.tagName.toLowerCase();}
function attrs(el){return Object.fromEntries([...el.attributes].map(a=>[a.name,a.value]));}
function reapplySelection(){const s=model.state.selection;if(!s)return;const doc=frame.contentDocument;if(!doc)return;doc.querySelectorAll('[data-b2-selected]').forEach(n=>n.removeAttribute('data-b2-selected'));let el=null;try{el=doc.querySelector(s.selector);}catch{} if(el)el.setAttribute('data-b2-selected','1');}
function injectStyle(doc){if(doc.getElementById('b2-wave3-style'))return;const st=doc.createElement('style');st.id='b2-wave3-style';st.textContent='[data-b2-selected]{outline:4px solid #ff6b00!important}[data-b2-field]{box-shadow:inset 0 0 0 2px #339af0!important}[data-b2-repeat]{outline:2px solid #845ef7!important}';doc.head.append(st);}
function applyHighlights(){const doc=frame.contentDocument;if(!doc)return;injectStyle(doc);doc.querySelectorAll('[data-b2-field],[data-b2-repeat]').forEach(n=>{n.removeAttribute('data-b2-field');n.removeAttribute('data-b2-repeat')});for(const r of model.state.structure.repeatedRegions){try{doc.querySelectorAll(r.selector).forEach(n=>n.setAttribute('data-b2-repeat','1'));}catch{}}for(const f of model.state.structure.fields){try{doc.querySelectorAll(f.selector).forEach(n=>n.setAttribute('data-b2-field',f.id));}catch{}}reapplySelection();}
function attachDocument(doc,framePath='main'){if(!doc||boundDocs.has(doc))return;boundDocs.add(doc);injectStyle(doc);const view=doc.defaultView; if(view && !view.__b2PopupBound){view.__b2PopupBound=true;view.addEventListener('message',e=>{if(e.data?.type==='fixture-popup-ready'){model.recordPopup(e.data.url);render();}});}doc.addEventListener('click',e=>{if(!picker)return;e.preventDefault();e.stopPropagation();const t=e.target;const p={selector:selectorFor(t),framePath,recordId:t.closest?.('[data-record-id]')?.getAttribute('data-record-id')||null,networkRequestId:t.closest?.('[data-source-request-id]')?.getAttribute('data-source-request-id')||t.getAttribute?.('data-source-request-id')||null,text:t.textContent,attributes:attrs(t)};model.selectElement(p);picker=false;$('#picker').textContent='Picker';bridge.publish('analyzer:b2-element-selected',model.state.selection);render();applyHighlights();},true);doc.querySelectorAll('iframe').forEach((child,i)=>{child.addEventListener('load',()=>{try{model.recordIframe(`${framePath}/iframe:${i}`);attachDocument(child.contentDocument,`${framePath}/iframe:${i}`);render();}catch{}})});}
function attachFrame(){const doc=frame.contentDocument;if(!doc)return;attachDocument(doc);mutationObserver?.disconnect();mutationObserver=new MutationObserver(list=>{model.recordDynamicMutation(list.length);applyHighlights();render();});mutationObserver.observe(doc.documentElement,{subtree:true,childList:true});frame.contentWindow.addEventListener('scroll',()=>model.recordScroll(frame.contentWindow.scrollY));render();applyHighlights();}
window.addEventListener('message',e=>{if(e.data?.type==='fixture-popup-ready'){model.recordPopup(e.data.url);render();}});
frame.addEventListener('load',attachFrame); if(frame.contentDocument?.readyState==='complete')attachFrame(); else setTimeout(()=>{try{if(frame.contentDocument?.readyState==='complete')attachFrame();}catch{}},0); $('#picker').onclick=()=>{picker=!picker;$('#picker').textContent=picker?'Picker ON':'Picker';};
bridge.on('analyzer:browser-state',p=>{model.ingestBrowserState(p);render();});bridge.on('analyzer:a3-event',p=>{model.ingestA3(p);render();});bridge.on('analyzer:a4-candidates',p=>{model.ingestA4(p);render();applyHighlights();});bridge.on('analyzer:a5-inference',p=>{model.ingestA5(p);render();});bridge.on('analyzer:b3-workflow',p=>{model.ingestB3(p);render();});bridge.on('analyzer:b5-preview',p=>{model.ingestB5(p);render();});bridge.connect();
function render(){const s=model.state;$('#status').textContent=s.runtime.connected?`LIVE ${s.runtime.inbound}`:'WAIT_RUNTIME';$('#mode').textContent=s.schema.mode;$('#network').innerHTML=s.network.map(n=>{const r=s.responses.find(x=>x.requestId===n.requestId);const b=s.responseBodies.find(x=>x.requestId===n.requestId);return `<div class="row ${s.selectedNetworkId===n.requestId?'selected':''}" data-rid="${n.requestId}"><b>${n.method}</b> ${n.url}<small> ${r?`${r.status??''} ${r.mimeType||''}`:'pending'}${b?` · body ${b.sizeBytes}B`:''}</small></div>`}).join('');document.querySelectorAll('#network .row').forEach(r=>r.onclick=()=>{model.selectNetwork(r.dataset.rid);render();reapplySelection();});$('#fields').innerHTML=s.structure.fields.map(f=>`<div class="row ${s.selectedFieldId===f.id?'selected':''}">${f.name}<small> ${f.selector}</small></div>`).join('')+s.structure.locators.map(l=>`<div class="row">↳ ${l.fieldId}: ${l.selector}</div>`).join('');$('#schema').innerHTML=`<b>${s.schema.status}</b> · ${s.schema.mode}<br>Endpoints ${s.schema.endpointGroups.length} / Schemas ${s.schema.responseSchemas.length}`;$('#workflow').innerHTML=s.workflow.map((w,i)=>`<div class="row">${i+1}. ${w.label||w.type||w.action||'step'}</div>`).join('');$('#selection').textContent=JSON.stringify(s.selection,null,2);const cols=s.preview.columns.map(c=>c.name||c.label||c.key||c);$('#preview').innerHTML=cols.length?`<table><thead><tr>${cols.map(c=>`<th>${c}</th>`).join('')}</tr></thead><tbody>${s.preview.rows.map((r,i)=>{const data=r.data||r;return `<tr class="${s.preview.selectedRow===i?'selected':''}">${cols.map(c=>`<td>${data[c]??''}</td>`).join('')}</tr>`}).join('')}</tbody></table>`:'<i>waiting preview</i>';document.documentElement.dataset.b2Ready='true';}
window.b2Wave3={model,bridge,select:(p)=>{model.selectElement(p);render();return model.snapshot();},state:()=>model.snapshot(),applyHighlights};render();
