'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const {buildReceipt} = require('./build_wave9_projection_receipt.cjs');
const root = __dirname;
const receipt = buildReceipt(path.join(root,'../wave8/candidate_ui_truth_bridge.cjs'),path.join(root,'W3_WAVE9_EXPECTED_RECEIPT.json'));
assert.equal(receipt.assertions_all_pass,true);
assert.equal(receipt.registry_sequence,9);
assert.equal(receipt.target_version,'5.10.2.4.2-rc3');
assert.equal(receipt.scenarios.length,2);
const idle = receipt.scenarios.find(x=>x.name==='disabled_idle_truth');
assert.equal(idle.counts.working,0);
assert.equal(idle.counts.idle,6);
const mixed = receipt.scenarios.find(x=>x.name==='mixed_acceptance_truth');
assert.deepEqual(mixed.counts,{working:4,current:1,historical:1,awaiting:1,missing:1,duplicate:1,error:1,end:1,idle:1,c:1,command:1});
assert.equal(mixed.projections[2].display_result_reference,'RESULT_COMMENT #5194248288');
assert.equal(mixed.projections[5].state,'REPORT_MISSING');
assert.equal(mixed.projections[9].legacy_profile_status_ignored,true);
const schema = JSON.parse(fs.readFileSync(path.join(root,'W3_WAVE9_TARGET_PC_UI_ACCEPTANCE_V1.schema.json'),'utf8'));
assert.equal(schema.properties.live_pass_claimed.const,false);
assert.equal(schema.properties.registry_sequence.const,9);
assert.equal(schema.properties.target_version.const,'5.10.2.4.2-rc3');
const ps = fs.readFileSync(path.join(root,'Collect-W3Wave9TargetPcUiAcceptance.ps1'),'utf8');
for(const token of ['ScreenshotPaths','RegistrySnapshotPath','before_restart','after_restart','LIVE_PASS_CLAIMED=false']) assert.ok(ps.includes(token),`missing ${token}`);
assert.ok(ps.includes("result_key='519440526200'"));
assert.ok(fs.readFileSync(path.join(root,'W3_WAVE9_EXPECTED_RECEIPT.json'),'utf8').includes('RESULT_COMMENT'));
console.log('W3_WAVE9_ACCEPTANCE_PACK_PASS assertions=17');
