#!/usr/bin/env node
'use strict';
const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),assert=require('node:assert');
const root=path.resolve(__dirname,'..'),gen=path.join(root,'generated'),tmp=path.join(root,'tests','.tmp');fs.rmSync(tmp,{recursive:true,force:true});fs.mkdirSync(tmp,{recursive:true});
function run(name,extra=[]){const out=path.join(tmp,`${name}.result.json`),trace=path.join(tmp,`${name}.trace.json`);const r=cp.spawnSync(process.execPath,[path.join(gen,'adapter.cjs'),'--api-fixture',path.join(root,'fixtures/public-api-posts.response.json'),'--dom-fixture',path.join(root,'fixtures/dom-fallback.html'),'--max-records','20','--output',out,'--trace',trace,...extra],{encoding:'utf8'});if(r.status!==0)throw new Error(`${name} failed: ${r.stderr}`);return {result:JSON.parse(fs.readFileSync(out)),trace:JSON.parse(fs.readFileSync(trace))};}
const normal=run('normal');assert.equal(normal.result.record_count,1);assert.equal(normal.result.mode,'HYBRID');assert.equal(normal.result.records[0].id,1);
const repaired=run('repaired',['--override-items-path','data.posts']);assert.equal(repaired.result.record_count,1);assert.ok(repaired.result.repair_count>=1);assert.ok(repaired.trace.events.some(e=>e.type==='STEP_REPAIRED'&&e.step==='api-items-path'));
const bad=JSON.parse(fs.readFileSync(path.join(root,'fixtures/public-api-posts.response.json')));delete bad[0].id;fs.writeFileSync(path.join(tmp,'bad.json'),JSON.stringify(bad));const out=path.join(tmp,'bad.result.json'),tr=path.join(tmp,'bad.trace.json');const fail=cp.spawnSync(process.execPath,[path.join(gen,'adapter.cjs'),'--api-fixture',path.join(tmp,'bad.json'),'--dom-fixture',path.join(root,'fixtures/dom-fallback.html'),'--max-records','20','--output',out,'--trace',tr],{encoding:'utf8'});assert.equal(fail.status,0);const hybridRepair=JSON.parse(fs.readFileSync(out));assert.equal(hybridRepair.record_count,1);assert.equal(String(hybridRepair.records[0].id),'1');
const receipt={schema_version:'A6_EXECUTABLE_ADAPTER_REPLAY_TEST_RECEIPT_V1',status:'PASS',tests:{normal_replay:'PASS',failed_items_path_partial_repair:'PASS',hybrid_missing_id_dom_fill:'PASS'},generated_executable_adapter_count:1,replay_success_count:3,real_sample_record_count:normal.result.record_count,trace_event_count:normal.trace.events.length+repaired.trace.events.length,partial_repair_event_count:repaired.result.repair_count};fs.writeFileSync(path.join(root,'replay-test-receipt.json'),JSON.stringify(receipt,null,2)+'\n');fs.copyFileSync(path.join(tmp,'repaired.trace.json'),path.join(root,'traces/replay-trace.json'));console.log(JSON.stringify(receipt,null,2));
