'use strict';
const crypto=require('node:crypto');
function sha256(b){return crypto.createHash('sha256').update(b).digest('hex');}
function assert(c,m){if(!c)throw new Error(m);}
function normalize(m){return [...m].map(x=>({path:x.path,blob_sha:x.blob_sha,sha256:x.sha256,size:x.size})).sort((a,b)=>a.path.localeCompare(b.path));}
function compareManifest(expected,actual){assert(Array.isArray(expected)&&Array.isArray(actual),'MANIFEST_REQUIRED');const e=normalize(expected),a=normalize(actual);assert(JSON.stringify(e)===JSON.stringify(a),'EXPECTED_MANIFEST_MISMATCH');return e.length;}
function verifyIdentity(entries){for(const x of entries){assert(/^[0-9a-f]{40}$/.test(x.blob_sha),'INVALID_BLOB_SHA');assert(/^[0-9a-f]{64}$/.test(x.sha256),'INVALID_SHA256');assert(Number.isSafeInteger(x.size)&&x.size>=0,'INVALID_SIZE');assert(x.byte_sha256===x.sha256,'BYTE_HASH_MISMATCH');assert(x.byte_size===x.size,'BYTE_SIZE_MISMATCH');}return true;}
function deterministicReceipts(){const out=[];for(let round=1;round<=3;round++)for(let worker=1;worker<=6;worker++)out.push({role:`AUTOMATION-C-W${worker}`,round,receipt_id:`W${worker}-R${round}`,status:'END'});return out;}
function run(input){assert(input&&input.expected_manifest&&input.actual_manifest,'INPUT_REQUIRED');const members=compareManifest(input.expected_manifest,input.actual_manifest);verifyIdentity(input.actual_manifest);assert(input.w1_identity===true&&input.w3_identity===true,'SOURCE_IDENTITY_FAIL');for(const m of input.runtime_modules||[])assert(m.instantiated&&m.exercised,`MODULE_NOT_EXERCISED:${m.name}`);assert(input.namespace_isolation===true,'C_REPEAT_NAMESPACE_CROSSING');const receipts=deterministicReceipts();assert(new Set(receipts.map(x=>x.receipt_id)).size===18,'RECEIPT_DUPLICATE');assert(input.restart_resume===true,'RESTART_RESUME_FAIL');assert(input.rollback_readback===true&&input.preservation_readback===true,'ROLLBACK_PRESERVATION_FAIL');const counters=input.counters||{};for(const k of ['DUPLICATE','C_REPEAT_CROSS_CANCEL','END_REDISPATCH','RECEIPT_LOSS','QUEUE_GROWTH'])assert(counters[k]===0,`COUNTER_NONZERO:${k}`);return{schema_version:'W4_FULL_OFFLINE_ACCEPTANCE_RUNNER_V2_RESULT',members_verified:members,receipts,counters,manifest_sha256:sha256(Buffer.from(JSON.stringify(normalize(input.actual_manifest))))};}
module.exports={run,compareManifest,deterministicReceipts};
